### ISSUE TITLE
CCIDDriver.read_serial() raises struct.error if a YubiKey has its read-serial# API call disabled

### ISSUE THREAD

**Issue by gurnec** [Yubico/yubikey-manager#113]
Steps to reproduce (I used a YubiKey NEO):
1. Start the YubiKey Personalization Tool.
2. Plug YubiKey in.
3. Go to Settings and disable the Serial # Visibility API call.
4. Go to Update Settings and Update Config Slot 1.
5. Verify that the Serial Number is no longer displayed on the right side of the Personalization Tool.
6. Start a tool which uses the most recent version of the ykman library, such as YubiKey Authenticator 4.3.4 or YubiKey Manager 0.5.1. The tool fails to get past the `Connecting to YubiKey...` message.

With debug logging enabled, this traceback is produced:
```
Traceback (most recent call last):
  File "qrc:///py/yubikey.py", line 124, in refresh
    else TRANSPORT.CCID)
  File "C:\Program Files (x86)\Yubico\Yubico Authenticator\pymodules\ykman\descriptor.py", line 90, in open_device
    dev = YubiKey(self, drv)
  File "C:\Program Files (x86)\Yubico\Yubico Authenticator\pymodules\ykman\device.py", line 217, in __init__
    serial = driver.read_serial()
  File "C:\Program Files (x86)\Yubico\Yubico Authenticator\pymodules\ykman\driver_ccid.py", line 125, in read_serial
    return struct.unpack('>I', serial)[0]
struct.error: unpack requires a buffer of 4 bytes
```

It looks like this commit removed the [highlighted line here](https://github.com/Yubico/yubikey-manager/commit/4160333d2fe89e3a31bc99d47bb465f6bfcc5bd1#diff-eac76d44800ad2fb0ea99a710ce4ff0dL124) which probably should have remained in... placing it back fixes both the Authenticator and Manager tools for me.

**Comment by dagheyman** [comment]
Thanks, there is an [unreleased fix for this](https://github.com/Yubico/yubikey-manager/commit/61018db3d2243cd6a4c4fa2cd56637e082eed1c2) on the master branch. Upcoming releases of Authenticator and Manager will include the fix.
