### ISSUE TITLE
Tests fail under sbuild

### ISSUE THREAD

**Issue by nbraud** [Yubico/yubikey-manager#116]
This is an issue I ran into while packaging yubikey-manager in Debian: the tests fail when run under sbuild:
```
[...]
running build_ext
Run tests sequentially
0:00:00 load avg: 6.90 [1/1] test
test test crashed -- Traceback (most recent call last):
  File "/usr/lib/python3.6/test/libregrtest/runtest.py", line 157, in runtest_inner
    clear_caches()
  File "/usr/lib/python3.6/test/libregrtest/refleak.py", line 200, in clear_caches
    stream.flush()
ValueError: underlying buffer has been detached

test failed

1 test failed:
    test

Total duration: 39 ms
Tests result: FAILURE
E: pybuild pybuild:336: test: plugin distutils failed with: exit code=2: python3.6 setup.py test 
dh_auto_test: pybuild --test -i python{version} -p 3.6 returned exit code 13
make: *** [debian/rules:3: build] Error 25
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
```

I worked around it for now by disabling the tests during the package build, but this is less than ideal.

**Comment by dagheyman** [comment]
Not sure how to reproduce this, I don't see any specific test referenced in the error message here. Our [Dockerfile](https://github.com/Yubico/yubikey-manager/blob/master/docker/xenial/Dockerfile) that builds the debian packages seems to run the tests fine.

**Comment by nbraud** [comment]
@dagheyman Oops, yes, that looks like the testing framework you are using gets confused when its stdin/stdout/stderr aren't a pty or something.  I will try to hunt that one down at some point.
