### ISSUE TITLE
Debian installation dependencies documentation

### ISSUE THREAD

**Issue by KaliszAd** [Yubico/yubikey-manager#127]
it should be noted, what packages are needed e.g. on Debian for the pip3 installation.
I found, pcscd and libpcsclite-dev are needed in order to be able to continue.

**Comment by emlun** [comment]
Hi,

Do you mean for installing with pip (`$ pip install yubikey-manager`) or as a Debian package?

**Comment by dagheyman** [comment]
It's noted in the development doc here: https://github.com/Yubico/yubikey-manager/blob/master/doc/development.adoc#linux-debian-based-distributions

Also note that yubikey-manager is now being packaged by debian in unstable: https://packages.debian.org/sid/main/yubikey-manager
