### ISSUE TITLE
yubikey-manager-0.7.1.tar.gz is missing some files

### ISSUE THREAD

**Issue by heirecka** [Yubico/yubikey-manager#136]
The fix in 7584219 which should've fixed #111 apparently didn't work. test/util.py is still missing and in addition the files from test/files which were part of 0.7.0 are also missing.

**Comment by emlun** [comment]
Thanks for the report!

**Comment by dagheyman** [comment]
The 1.0.0 release should have these files.

**Comment by heirecka** [comment]
Just to confirm: It actually has them. Thanks.
