### ISSUE TITLE
Could not find device while inserted 

### ISSUE THREAD

**Issue by butterl** [Yubico/yubikey-manager#14]
Hi ，

I'm using yubikey neo and after error click a USB something selection in gnubbyd(a chrome plugin), the key is no more recognized as HID,and keeping searching  yubikey driver ,and is recognized as an unknown device named “Yubico WinUSB gnubby(gnubby1)”

yubikey-manager do not recognize it too.
Is these an solution for this situation ? How can I make it to HID again？

**Comment by dagheyman** [comment]
Thanks for the report. This doesn't look like a YubiKey NEO, but like a YubiKey from a custom order, not supported by this software. Please contact whoever gave you the device.
