### ISSUE TITLE
USB Interface Configuration button is greyed out

### ISSUE THREAD

**Issue by ruant** [Yubico/yubikey-manager#145]
Trying to get `Security Key` working with Windows login.
It states that you have to enable CCID mode, the guide says you should hit Configuration under USB Interface in the Manager.
But it's greyed out.

**Comment by emlun** [comment]
Sorry, the [Security Key][sky] does not have the CCID functions and cannot be used for Windows login. For that you will need a [YubiKey 4][yk4] or [YubiKey NEO][neo], which both do have the needed functions.

If your Security Key is of version 2 (if it has a "2" etched on the front), it will be usable with Windows Hello once that is released. The version 1 Security Key (without the etched "2") might also work with Windows Hello, but I'm not sure about it.

If you have further questions about this, please direct them at [Yubico Support][support].

[sky]: https://www.yubico.com/product/security-key-by-yubico/#security-key
[yk4]: https://www.yubico.com/product/yubikey-4-series/
[neo]: https://www.yubico.com/product/yubikey-neo/
[support]: https://support.yubico.com/support/home
