### ISSUE TITLE
Debian: Again, dependency on `python-fido2`.

### ISSUE THREAD

**Issue by LDVSOFT** [Yubico/yubikey-manager#153]
1.0.0 release, like in #135, depends on `python-fido2` instead of `python3-fido2`:
```
Package: python3-yubikey-manager
Version: 1.0.0~ppa1~bionic1
Priority: optional
Section: python
Source: yubikey-manager
Maintainer: Debian Authentication Maintainers <pkg-auth-maintainers@lists.alioth.debian.org>
Installed-Size: 213 kB
Depends: python-fido2, python3-click, python3-cryptography, python3-openssl, python3-pyscard, python3-six, python3-usb, python3:any (>= 3.4~), libykpers-1-1
Recommends: pcscd
Download-Size: 35,8 kB
APT-Sources: http://ppa.launchpad.net/yubico/stable/ubuntu bionic/main amd64 Packages
Description: Python 3 library for configuring a YubiKey
```

**Comment by dagheyman** [comment]
Thank you (again), looking in to it.

**Comment by dagheyman** [comment]
New packages published, should be correct.

**Comment by LDVSOFT** [comment]
Yep. Just out of curiosity — what causes that bug?

**Comment by emlun** [comment]
We're not sure, but our best guess is that it seems like `${python3:Depends}` was expanded to the wrong Python dependencies somehow. See https://github.com/Yubico/yubikey-manager/commit/f6ee562a3b9038fed3803f2f75398c1d2c276b20#diff-d837a1c17de0268bcea321239ddbed47
