### ISSUE TITLE
Copying between slots

### ISSUE THREAD

**Issue by mmb** [Yubico/yubikey-manager#17]
Is there a way to program an OTP credential in one slot and then copy it to the other slot?

I'd like to have the same credential in both slots so that both short press and long press work.

**Comment by dagheyman** [comment]
No, it's only possible to delete a slot configuration or swap places between the slots. Please note that even if you program both slots with the same credentials, the [counters](https://developers.yubico.com/OTP/OTPs_Explained.html) will go out of sync. I'd recommend deleting the slot you don't want to use.

**Comment by mmb** [comment]
Thanks for the explanation.
