### ISSUE TITLE
I want to use Yubikey  on my physical server

### ISSUE THREAD

**Issue by weiwei34** [Yubico/yubikey-manager#179]
HI Guys：
       I have installed some very important programs on my server. In order to prevent someone from stealing my password and accessing this information on the physical machine terminal, I hope to use YubiKey to restrict physical machine terminal login. Currently there is no https://developers .yubico.com find the answer I want, please give pointers on how I should do this to achieve this function. Thank You！

**Comment by dagheyman** [comment]
Hi,

I'd suggest opening a ticket with [Yubico Support](https://support.yubico.com/support/tickets/new), and they should be able to provide further guidance.
