### ISSUE TITLE
fido2 0.4.0 not working on macos

### ISSUE THREAD

**Issue by origliante** [Yubico/yubikey-manager#182]
Just attaching here the exception:

$ ykman list
Exception ignored in: <bound method MacOsHidDevice.__del__ of <fido2._pyu2f.macos.MacOsHidDevice object at 0x105efa400>>
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fido2/_pyu2f/macos.py", line 459, in __del__
    self.in_report_buffer,
AttributeError: 'MacOsHidDevice' object has no attribute 'in_report_buffer'

**Comment by origliante** [comment]
You're welcome @dagheyman 

Installed today with
port selfupdate
port install yubikey-manager

version is 0.4.0

**Comment by dagheyman** [comment]
And this is on macOS 10.14 Mojave?

**Comment by origliante** [comment]
Yes

Il giorno gio 22 nov 2018, 16:34 Dag Heyman <notifications@github.com> ha
scritto:

**Comment by dagheyman** [comment]
Sorry, I can't reproduce this at all. Installed yubikey-manager from macports on a fresh macOS Mojave install, and everything seems to work fine. Does this happen every time for you?

**Comment by origliante** [comment]
@dagheyman my fault, I checked again now with stock python, and it works, probably the 3.6 that I was calling above had no access to the system libraries or something like that? I would suggest to add two lines of checking and warning on the initialization of MacOsHidDevice

**Comment by dagheyman** [comment]
Glad it worked out, thanks!
