### ISSUE TITLE
Error: No PyUSB backend detected

### ISSUE THREAD

**Issue by jsatk** [Yubico/yubikey-manager#185]
I only use YubiKeys for GPG. Since OTP via YubiKey isn't supported in Firefox or Safari as of this writing I don't use it. Unfortunately when I attempt to disable OTP via USB it throws this error.
```
$ ykman config usb --disable OTC
Usage: ykman [OPTIONS] COMMAND [ARGS]...

Error: No PyUSB backend detected!
```

Also when I inquire about the version I get this warning:

```
$ ykman -v
YubiKey Manager (ykman) version: 1.0.1
Libraries:
    libykpers not found!
    <pyusb backend missing>
```

I've done an install and reinstall of both `ykman` and `ykpers`.

I've tried searching for a resolution to this but to no avail. Any help on disabling OTC for this Yubikey 4 nano would be greatly appreciated.

**Comment by dagheyman** [comment]
How did you install ykman? 
```    
libykpers not found!
<pyusb backend missing>
```
indicates that the c-libraries are not available. See the installation [instructions](https://github.com/Yubico/yubikey-manager#installation). If you are using macOS for example, I'd recommend `$ brew install ykman`.

**Comment by dagheyman** [comment]
>  Any help on disabling OTC for this Yubikey 4 nano would be greatly appreciated.

The correct command, once ykman is installed, would be
`$ ykman mode CCID+FIDO`

**Comment by dagheyman** [comment]
Any other issues, please contact [Yubico Support](https://support.yubico.com/support/tickets/new).

**Comment by jsatk** [comment]
<img width="504" alt="image" src="https://user-images.githubusercontent.com/1005550/49759604-0cbfbc00-fc77-11e8-8379-e9280719a41a.png">

**Comment by dagheyman** [comment]
Now it seems to find libykpers at least.

Could you try `$ brew reinstall libusb` ?

**Comment by jsatk** [comment]
That did it @dagheyman. No idea what the issue was or why it got b0rked. Odd. 

Thank you so much.

**Comment by jsatk** [comment]
Resolution is to reinstall libusb via `brew reinstall libusb`.
