### ISSUE TITLE
To reset PUK you don't need to reset PIV.

### ISSUE THREAD

**Issue by smrt28** [Yubico/yubikey-manager#199]
I blocked PUK by
```
$ yubico-piv-tool -a change-puk -P 000000 -N 000001
```
Executed four times. The PIN is not blocked. Reasonably, any attempt to change the PUK fails. 

```
$ yubico-piv-tool -a change-puk
Enter puk: 
Enter new puk: 
Verifying - Enter new puk: 
The puk code is blocked, you will have to reinitialize the application.
```

However, the error message is actually not true since I can reset the PUK if I know the PIN by setting PIN retries.

```
ykman piv set-pin-retries 3 3
```

This command resets the PIN and PUK to default 123456/12345678 values and so makes PUK functional again. Is it expected behavior? Tested on Yubikey 5.

**Comment by dagheyman** [comment]
`Thanks for the report.

This is expected behavior, since setting the PIN and PUK retries requires the PIN. The message `The puk code is blocked, you will have to reinitialize the application.` assumes that the PIN is actually lost, might need some clarification.

**Comment by dagheyman** [comment]
See also https://developers.yubico.com/PIV/Introduction/Yubico_extensions.html#_set_pin_retries
