### ISSUE TITLE
YubiKey 4 has disabled CCID under Win7 Pro but under Win10 Pro, it's still showing CCID enabled

### ISSUE THREAD

**Issue by oscarso** [Yubico/yubikey-manager#2]
With YubiKey 4, under Win 7 Pro, disable CCID and verified CCID is disabled.
Unplug and re-plug YubiKey 4 under Win 10 Pro, but YubiKey Manager is still showing CCID enabled.

**Comment by dainnilsson** [comment]
@oscarso can you try some troubleshooting for me? On both Windows 7 and 10, with the YubiKey inserted, open the Device Manager and look for an entry under "Smart card readers". If available, right-click on the item and select "Properties". Click on the "Details" tab and select "Hardware Ids". Please provide us with the content in the Value box (as seen in the screenshot below) for each OS:
![device_manager_hw_ids](https://cloud.githubusercontent.com/assets/140781/17884501/ea6f8426-6918-11e6-88f1-f6a71a9d3229.png)
