### ISSUE TITLE
ykman not working on Fedora 29

### ISSUE THREAD

**Issue by andyneff** [Yubico/yubikey-manager#201]
- YubiKey Manager (ykman) version: 0.6.0
- How was it installed?: `yum install yubikey-manager`
- Operating system and version: Fedora 29
- YubiKey model and version: Yubikey 4, 4.3.7
- Bug description summary: PIV commands are not working

Steps to reproduce
---

I recently updating my Fedora 29 to the latest on all packages (which might not be related...), but now all `ykman piv` commands fail

Expected result
---

`ykman piv info` works

Actual results and logs
---

```
ykman piv info
Usage: ykman [OPTIONS] COMMAND [ARGS]...

Error: Failed connecting to the YubiKey.
```

Other info
---

I have tried several yubikeys, reinserting, and rebooted, nothing has worked once today. This was working prior to my updates, back in December 2018

`sudo journalctl -u pcscd` reveals

```
Jan 07 13:32:36 viola.vsi-ri.com systemd[1]: Started PC/SC Smart Card Daemon.
Jan 07 13:32:36 viola.vsi-ri.com pcscd[10121]: 00000000 ifdhandler.c:150:CreateChannelByNameOrChannel() failed
Jan 07 13:32:36 viola.vsi-ri.com pcscd[10121]: 00000082 readerfactory.c:1106:RFInitializeReader() Open Port 0x200000 Failed (usb:1050/0407:libudev:0:/dev/bus/usb/003/007)
Jan 07 13:32:36 viola.vsi-ri.com pcscd[10121]: 00000012 readerfactory.c:376:RFAddReader() Yubico YubiKey OTP+FIDO+CCID init failed.
Jan 07 13:32:36 viola.vsi-ri.com pcscd[10121]: 00008437 ifdhandler.c:150:CreateChannelByNameOrChannel() failed
Jan 07 13:32:36 viola.vsi-ri.com pcscd[10121]: 00000010 readerfactory.c:1106:RFInitializeReader() Open Port 0x200000 Failed (usb:1050/0407:libudev:1:/dev/bus/usb/003/007)
Jan 07 13:32:36 viola.vsi-ri.com pcscd[10121]: 00000003 readerfactory.c:376:RFAddReader() Yubico YubiKey OTP+FIDO+CCID init failed.
```

I believe CCID is installed. The following package is already installed `pcsc-lite-ccid-1.4.30-1.fc29.x86_64`

**Comment by emlun** [comment]
Thanks for reporting! This looks like a duplicate of Yubico/yubioath-desktop#318.

**Comment by andyneff** [comment]
Ah, looks like it. I just made a virtualenv with ykman 1.0.1, and that did work. Thanks
