### ISSUE TITLE
Clarify release procedure

### ISSUE THREAD

**Issue by Foxboron** [Yubico/yubikey-manager#202]
Today `yubikey-manager-2.0.0` was tagged. But in the `NEWS` it's marked as unreleased. However `yubikey-manager-1.0.1` has been retagged previously and changed from `unreleased`  to `released` in the `NEWS` file with no signature file in the github release page.

Would it be possible to streamline the release procedures so it's easier to understand when software has been release? Along with getting reliable signatures for the release tarballs? Personally i'd like to see the current release tagged with `yubikey-manager-2.0.0-rc1`.

**Comment by dagheyman** [comment]
Hi, 

in general, for third party packaging, don't rely on the git tags or the GitHub release page, but on source releases and signatures found here: https://developers.yubico.com/yubikey-manager/Releases/

Will look into documenting this better.

**Comment by dagheyman** [comment]
Added a note about this in the development doc https://github.com/Yubico/yubikey-manager/blob/master/doc/development.adoc#packaging
