### ISSUE TITLE
new feature: openpgp touch displays all current policies

### ISSUE THREAD

**Issue by git14** [Yubico/yubikey-manager#203]
- YubiKey Manager (ykman) version: next
- Feature description: command `ykman openpgp touch` displays all keys and the current policy for each.

Currently three commands have to be executed to get the current policy for a YubiKey. Just lazy and would like one command to show me how a YubiKey is configured for touch.

**Comment by dagheyman** [comment]
Thanks for the suggestion, I make sure we'll look into it.

**Comment by dagheyman** [comment]
This is now possible with ykman 2.1.0:
```
$ ykman openpgp info
OpenPGP version: 5.1.0
PIN tries remaining: 3
Reset code tries remaining: 0
Admin PIN tries remaining: 3

Touch policies
Signature key           OFF
Encryption key          OFF
Authentication key      OFF
```
