### ISSUE TITLE
REPL mode

### ISSUE THREAD

**Issue by akerl** [Yubico/yubikey-manager#21]
Currently using this on a low-resource system (Raspberry Pi), where each ykman invocation takes double-digit seconds to run, as it loads up all the relevant libraries and such. Would rock if I could launch a REPL and run the commands in sequence instead of paying the load price w/ each invocation

**Comment by akerl** [comment]
It looks like https://github.com/click-contrib/click-repl may make this relatively straightforward

**Comment by dagheyman** [comment]
Thanks for the suggestion and the PR. I'm not sure I agree that a REPL is the best way to solve this performance issue. It would introduce extra third-party dependencies, and as you mentioned in #22, introduces some issues with the connection modes.

It sounds weird that the ykman commands takes 10+ seconds to run, could you give some more information about your system (Raspberry Pi version, OS)?. Maybe something else can be done about that.

**Comment by akerl** [comment]
It's a Raspberry Pi Model A+, running Archlinux ARM. The slowness isn't unique to this script, it affects most anything that requires reading a decent number of files into memory off the SD card. This script just ends up feeling the pain more than others, because each of the subcommands is single-purpose, so to set up a yubikey I end up running a large number of `ykman` calls.

**Comment by dagheyman** [comment]
Thanks for the explanation. 

So for now, no REPL-related PRs will be merged, for the following reasons:
 - adds extra complexity
 - adds more third-party dependencies
 - not enough demand

This might be reconsidered in the future, if demand is high.
