### ISSUE TITLE
Discrepancy between Github and Yubico based tarball contents

### ISSUE THREAD

**Issue by gktrk** [Yubico/yubikey-manager#217]
- YubiKey Manager (ykman) version: 2.0.0
- How was it installed?:
- Operating system and version: Gentoo Linux
- YubiKey model and version:
- Bug description summary:

The version 2.0.0 tarball is available through two different sources:
Github: https://github.com/Yubico/yubikey-manager/archive/yubikey-manager-2.0.0.tar.gz
Yubico: https://developers.yubico.com/yubikey-manager/Releases/yubikey-manager-2.0.0.tar.gz

The contents of these tarballs differ and it is confusing for distro maintainers. Primarily, the Yubico tarball does not contain `man/ykman.1` whereas the Github tarball does. They should be identical IMO so that one source can serve as the failover for the other. They also untar to different directories (`yubikey-manager-yubikey-manager-2.0.0` vs `yubikey-manager-2.0.0`).

Steps to reproduce
---

Download both tarballs and unpack them to a common directory. The Github tarball unpacks to `yubikey-manager-yubikey-manager-2.0.0` and the Yubico tarball unpacks to `yubikey-manager-2.0.0`. Look at the diff between the two directories:

```
$ diff -u <(cd yubikey-manager-2.0.0 && find | sort) <(cd yubikey-manager-yubikey-manager-2.0.0 && find | sort)
```

Expected result
---

Expected the file list to be identical. At the very least, the manpage should be available in both tarballs.

Actual results and logs
---

The following is the diff output:

```
$ diff -u <(cd yubikey-manager-2.0.0 && find | sort) <(cd yubikey-manager-yubikey-manager-2.0.0 && find | sort)
--- /dev/fd/63	2019-01-31 19:08:09.413045945 -0500
+++ /dev/fd/62	2019-01-31 19:08:09.413045945 -0500
@@ -1,10 +1,32 @@
 .
+./appveyor.yml
 ./COPYING
+./debian
+./debian/changelog
+./debian/compat
+./debian/control
+./debian/copyright
+./debian/python3-yubikey-manager.install
+./debian/python-yubikey-manager.install
+./debian/rules
+./debian/source
+./debian/source/format
+./debian/yubikey-manager.install
+./debian/yubikey-manager.manpages
 ./doc
 ./doc/development.adoc
+./docker
+./docker/xenial
+./docker/xenial/Dockerfile
+./.github
+./.github/ISSUE_TEMPLATE.md
+./.gitignore
+./lgtm.yml
+./man
 ./MANIFEST.in
+./man/ykman.1
 ./NEWS
-./PKG-INFO
+./.pre-commit-config.yaml
 ./README.adoc
 ./setup.cfg
 ./setup.py
@@ -46,6 +68,7 @@
 ./test/test_scancodes.py
 ./test/test_util.py
 ./test/util.py
+./.travis.yml
 ./ykman
 ./ykman/cli
 ./ykman/cli/config.py
@@ -84,12 +107,6 @@
 ./ykman/scancodes/modhex.py
 ./ykman/scancodes/us.py
 ./ykman/settings.py
+./ykman.spec
 ./ykman/util.py
 ./ykman/VERSION
-./yubikey_manager.egg-info
-./yubikey_manager.egg-info/dependency_links.txt
-./yubikey_manager.egg-info/entry_points.txt
-./yubikey_manager.egg-info/PKG-INFO
-./yubikey_manager.egg-info/requires.txt
-./yubikey_manager.egg-info/SOURCES.txt
-./yubikey_manager.egg-info/top_level.txt
```

`man/ykman.1` only exists in the Github tarball.

Other info
---

[Anything else you would like to add?]

**Comment by dagheyman** [comment]
Two things:
1. The tarball on developers.yubico.com is the official one, and the one recommended for packagers to rely on. The one on GitHub is automatically created for each tag (no way to turn this off unfortunately).
2. The missing manpage is a bug, thanks for pointing it out. Will address it in the next release.

**Comment by nbraud** [comment]
@dagheyman While we are on the topic of discrepancies, the official tarball's `NEWS` file marked version 2.0.0 as unreleased.

I patched your upstream changelog in Debian to remove the mention of the (missing) manpage and set the release date.  Looking forward to having a manpage next release  <3

**Comment by dagheyman** [comment]
@nbraud Thanks, I look into that as well. The reason is that the tagging is done before updating the NEWS file (which is mirrored on developers as release notes), but it probably makes more sense to update NEWS and then tag.

**Comment by nbraud** [comment]
@dagheyman Yes, probably.  FWIW, if you were to generate the tarball with `git archive` it should be pretty difficult to accidentally diverge from what's in version control.

**Comment by dagheyman** [comment]
https://developers.yubico.com/yubikey-manager/Releases/yubikey-manager-2.1.0.tar.gz includes the manpage. Closing this, feel free to report additional issues.
