### ISSUE TITLE
ykman cannot detect yubikey after disabling piv

### ISSUE THREAD

**Issue by hongkongkiwi** [Yubico/yubikey-manager#229]
- YubiKey Manager (ykman) version:
2.1.0 (also 2.0.0)
- How was it installed?:
Origionally installed 2.0.0 using homebrew (brew install ykman), but then did a source install on MacOSX to test 2.1.0
- Operating system and version:
OSX 10.12.6
- YubiKey model and version:
Both Nano 5 & NFC 5
- Bug description summary:
I've been writing a script to disable/enable different features using ykman. Somehow I have disabled reading of the yubikey completely on the computer.

This is fixed by restarting the computer.

Curiously, when using the yubikey manager qt, it will detect when I have multiple yubikeys plugged in (although I still can't actually do anything with them), however if I just insert one of the messed up yubikeys I cannot do anything with them until reboot.

Steps to reproduce
---
You can run my script to reproduce.
https://gist.github.com/hongkongkiwi/bdedf600219280d1692ff22cce4286ad

[Please explain what you did when the bug appeared, and if and how you have been
able to reproduce it.]

Expected result
---

[What did you expect to happen when you did the above?]

Actual results and logs
---

[What actually happened?]
I'm not sure which command messed it up, but it was one of the following:
`ykman -d myserial piv reset -f > /dev/null`
`ykman -d myserial piv set-ccc -m "010203040506070801020304050607080102030405060708"`
`ykman -d myserial piv set-chuid -m "010203040506070801020304050607080102030405060708"`

After running these commands, we cannot detect any yubikey anymore using the ykman info command.

I restarted the computer and all yubikeys can read.

**Comment by dagheyman** [comment]
Hi, thanks for the report.

I can actually run your script just fine (on Ubuntu), my guess is that the CCID drivers on macOS is causing problems in some way. Maybe you can run the commands with the flag `--log-level DEBUG` to see if it gives any clues?

```
$ bash ykman-setup 
# Checking System Setup
# Checking for Yubikeys
 - Found Device Device: YubiKey 5 NFC [OTP+FIDO+CCID] Serial: 7800303
# Analysing Yubikey
*** WARNING ***
 This will completely reset your Yubikey. Are you sure? [y/N] y
# Updating Interfaces (USB & NFC)
 - NFC is enabled on this Yubikey - For security we will disable it
 - Disable OTP Function
 - Disable FIDO2 U2F Function
 - Disable USB OATH Function
 - Disable USB FIDO2 Function
 - Disable USB PIV Function
 - Set USB mode to CCID
# Resetting OpenPGP Data
# Resetting PIV Data
# All Done
$ ykman info
Device type: YubiKey 5 NFC
Serial number: 7800303
Firmware version: 5.1.0
Form factor: Keychain (USB-A)
Enabled USB interfaces: CCID
NFC interface is disabled.

Applications	USB     	NFC     
OTP     	Disabled	Disabled	
FIDO U2F	Disabled	Disabled	
OpenPGP 	Enabled 	Disabled	
PIV     	Enabled 	Disabled	
OATH    	Enabled 	Disabled	
FIDO2   	Disabled	Disabled
```

**Comment by hongkongkiwi** [comment]
After rebooting everything worked fine. It is like something crashed or a
daemon locked up, but I'm unsure exactly what it was, but saw on a forum
that scdaemon can cause this problem (I checked that but no such such
daemon on osx).

I did try to use the debug trace, but it simply couldn't find the card
reader at all.

Curiously, this applied to all my yubikeys including previously working
ones.

**Comment by dagheyman** [comment]
Yes, the CCID drivers on macOS can be a bit shaky sometimes in my experience. It might be worth looking into updating macOS as well (I see that you are running Sierra), the smart card support does seem to improve a bit in every release.

**Comment by hongkongkiwi** [comment]
That makes sense, thank you for the help. I will close this issue now and re-open if I have anymore information or can consistently reproduce.
