### ISSUE TITLE
Support for remembering OATH passwords

### ISSUE THREAD

**Issue by rickard-von-essen** [Yubico/yubikey-manager#23]
`yubioath` supports `-R` to remember a password so you don't have to enter it every time.

```
$ yubioath -h
[...]
  -R, --remember     Remember any entered access key for later use.
```

It would be great to have such functionality here too.

**Comment by dainnilsson** [comment]
This feature is now in master, and will be in the next release of ykman (no current ETA).

**Comment by rickard-von-essen** [comment]
Great!
