### ISSUE TITLE
Git PGP signing using wrong key

### ISSUE THREAD

**Issue by stevenroose** [Yubico/yubikey-manager#238]
So I have a setup of a master key and 3 subkeys (one signing, one encryption and one authentication). I have been signing my git commits with the signing subkey successfully using a software GPG setup, using the `user.signingkey` git property.

Now I purchased a Yubikey Nano 5 and put those 3 keys on the smartcard. Somehow, the Yubikey seems to be signing my Git commits with the Authentication key instead of the Signing key. Even though the `user.signingkey` is still the fingerprint of the signing subkey.

I don't know where to report this.

**Comment by dagheyman** [comment]
Please contact our [technical support](https://support.yubico.com/support/tickets/new), they should be able to help you.

**Comment by CPerezz** [comment]
Hey have the same exact issue @stevenroose 

Have you figured out the solution by any chance?
