### ISSUE TITLE
FYI: Homebrew formula

### ISSUE THREAD

**Issue by rickard-von-essen** [Yubico/yubikey-manager#24]
I added a formula for Homebrew. When it is merged it would be great change the readme for macOS install to use that.

See Homebrew/homebrew-core#18524

**Comment by dagheyman** [comment]
Great, thanks for letting us know!

**Comment by rickard-von-essen** [comment]
This have been merged in homebrew/homebrew-core@ea80c8612f2f8e8ebb2661ce0968282e6a82f40b

**Comment by emlun** [comment]
Thanks! Installation instructions have been updated: #25
