### ISSUE TITLE
[Question] Detecting that Yubikey is waiting for a touch via an external script

### ISSUE THREAD

**Issue by maximbaz** [Yubico/yubikey-manager#26]
I have YubiKey 4 Nano and the blinking light is not always visible, so I often find myself missing a time window to touch Yubikey when there is a prompt "Please touch the device". This happens for example when I begin some long-running task that will finish with a sudo command (e.g. build and install an app).

I'm writing a script that could detect when YubiKey is waiting for a touch. I have some partial success, and it looks like this:

![yubikey_indicator](https://user-images.githubusercontent.com/1177900/31579601-c212a3ea-b139-11e7-818d-eed56cf7e09e.gif)

Detection for `gpg` and `sudo` operations is very different, both methods are very hacky and have their downsides, so I want to describe how I made it and ask you for suggestions, maybe you can come up with some improvement ideas.

#### GPG:
I noticed that command `gpg --card-status` normally returns instantly, but if YubiKey is waiting for a touch for another `gpg` operation (like `gpg --sign`), then `gpg --card-status` will hang until I touch the device. So I implement detection in a following way:
1. Every second or even less, try to call `gpg --card-status`.
2. If the command returns instantly, YubiKey is **not** waiting for a touch - repeat step 1
3. Otherwise, mark that YubiKey is waiting for a touch and wait until the command returns.
4. When it returns, mark that YubiKey is no longer waiting for a touch.

The problems with this approach:
- Lots of wasted CPU cycles (I want the detection to happen as fast as possible)
- The fact that YubiKey is always active, it has to respond to `gpg --card-status` a lot of times and thus the light indicator is always constantly on.

**UPDATE**: I came up with a yet another hack to drastically reduce the number of CPU cycles. Instead of always constantly running `gpg --card-status`, I first use `inotifywait` to monitor access to `~/.gnupg/pubring.kbx` (for `sign` and `encrypt`) and `~/.ssh/known_hosts` (for `auth`), and only if any of these two files were opened, then I try `gpg --card-status` in a loop within 5 seconds. The rest of the algorithm remains the same.

Any suggestions on how to better do this?

#### sudo (pam-u2f):
I opened [a separate question](https://github.com/Yubico/pam-u2f/issues/77) about this topic on `pam-u2f` repo, but I'll describe it here as well, as here it is a different audience and most of links on ArchWiki point to this repo anyway.

Since to configure `pam-u2f` it is needed to create `~/.config/Yubico/u2f_keys` file, it is obvious to assume that this file will be read every time Yubikey will be used. Good news, this does happen, so setting up a simple `inotifywait` for `OPEN` event for this file will instantly let me know when `sudo` access is being requested. No wasted CPU cycles in this approach, I like it.

However, the problem that I was unable to solve so far is how to detect that YubiKey is stopped waiting for a touch (user touched the device, or timeout happened). With `gpg` it was easy, but here I cannot find a way to detect this.

**UPDATE:** I made [a fork of pam-u2f](https://github.com/maximbaz/pam-u2f) that allows to watch the event of completed authorization. It was [not merged in the upstream](https://github.com/Yubico/pam-u2f/pull/78), because that project is being rewritten, but hopefully this functionality will be present in the new project. But using the fork allows to monitor when `~/.config/Yubico/u2f_keys` was opened to indicate that authorization was completed.

Any better suggestions here?

-----

Of course it would be awesome if one of the yubikey CLI tools provided such information out of the box, it is a really useful feature in my mind and I've seen [other people requesting this](https://forum.yubico.com/viewtopic.php?f=35&t=2397). But I understand that it might be simply impossible to implement in a proper way.

**Comment by emlun** [comment]
Thank you for your work on this, and sorry for the slow response. I think your solutions are probably as good as they get for the time being; even if we wanted to add these features to `ykman` we'd be at the mercy of what the backend drivers support.

For GPG on Arch Linux the backend is pcsclite, so there might be some feature of pcscd or pcsc-tools you could use. `pcsc-spy` (from the `pcsclite` package) looks promising, but I wasn't able to get anything out of it in my short examination of it.

For U2F the backend is libu2f-host, and I don't think we want to complicate it with whatever would be necessary to provide some kind of event engine. But your updated solution seems like a pretty elegant one, so it's probably the best one available for the foreseeable future (until the pam-u2f rewrite is willing to accept your PRs). :)

Anyway, thanks for figuring these things out! I'm sure they'll be useful to someone even if we can't support them in our official tools.

**Comment by maximbaz** [comment]
Thanks for your response 🙂 I'll have a look at `pcsc-spy` to see if I can get something useful out of it.

I'll close the ticket since the questions are answered, but please consider adding this feature request to the backlog for `ykman`. I've been using my custom script for a few weeks now and I simply can't express how helpful this indicator is, I finally stopped missing touch requests, even when I put my laptop aside and use an external screen 🙂

**Comment by maximbaz** [comment]
In case someone is interested, I created a standalone app for detecting when YubiKey is waiting for a touch. It is designed to be run as a background service and to be easily integrated with third-party apps that can use it to display a visible indicator.

https://github.com/maximbaz/yubikey-touch-detector

A big improvement comparing to what I described above is that now it can also detect when a physical touch is requested due to the use of `ssh` on a *remote host* with forwarded `ssh-agent`.

**Comment by semente** [comment]
I found that the command `ykinfo -s` returnsthe error message "Yubikey core error: timeout" when waiting for a touch. I would use this in a script but I don't think this is reliable in long term.

Couldn't yubikey-manager provide a `-T` option which will exit with status 0 when the device is waiting for a touch?

**Comment by semente** [comment]
Sorry, `ykinfo` is part of yubikey-personalization. There is an open request for this feature at https://github.com/Yubico/yubikey-personalization/issues/154

**Comment by semente** [comment]
> I found that the command `ykinfo -s` return the error message "Yubikey core error: timeout" when waiting for a touch. I would use this in a script but I don't think this is reliable in long term.
> 
> Couldn't yubikey-manager provide a `-T` option which will exit with status 0 when the device is waiting for a touch?

Sorry, ykinfo is part of yubikey-personalization. There is an open request for this feature at https://github.com/Yubico/yubikey-personalization/issues/154
