### ISSUE TITLE
`ykman piv generate-certificate` uses local time as if it is UTC time

### ISSUE THREAD

**Issue by aviben01** [Yubico/yubikey-manager#267]
- YubiKey Manager (ykman) version: 2.1.0
- How was it installed?: Windows installer
- Operating system and version: Windows 10
- YubiKey model and version: YubiKey 5 NFC
- Bug description summary: 
`ykman piv generate-certificate` command uses local time as if it is UTC time.
This may cause certificate to be temporarily invalid in case UTC offset value is positive, since `valid from` in certificate is expected to be UTC

Steps to reproduce
---
Using GIT bash or similar:
```
# Force reset piv
"C:\Program Files\Yubico\YubiKey Manager\ykman.exe" piv reset --force
# Generating PIV key
"C:\Program Files\Yubico\YubiKey Manager\ykman.exe" piv generate-key -P 123456 -m 010203040506070801020304050607080102030405060708 9a publickey.pem
# Generating PIV certificate
"C:\Program Files\Yubico\YubiKey Manager\ykman.exe" piv generate-certificate -d 365 -s "my-key" -P 123456 -m 010203040506070801020304050607080102030405060708 9a publickey.pem
# Print current UTC time
TZ=UTC date
# Print start time in certificate
"C:\Program Files\Yubico\YubiKey Manager\ykman.exe" piv export-certificate 9a - | openssl x509 -noout -startdate
```

Expected result
---
Certificate `notBefore` value shall match current UTC time.

Actual results and logs
---
With local time UTC+3, certificate will only be valid in 3 hours:
```
$ # Print current UTC time
$ TZ=UTC date
Sun, Jul 14, 2019  6:44:52 AM
$ # Print start time in certificate
$ "C:\Program Files\Yubico\YubiKey Manager\ykman.exe" piv export-certificate 9a - | openssl x509 -noout -startdate
notBefore=Jul 14 09:44:52 2019 GMT
$
```

Other info
---

Can be worked-around by providing `TZ` environment variable to `ykman` process:
```
env TZ=UTC "C:\Program Files\Yubico\YubiKey Manager\ykman.exe" piv generate-certificate -d 365 -s "my-key" -P 123456 -m 010203040506070801020304050607080102030405060708 9a publickey.pem
```

**Comment by dagheyman** [comment]
Thanks for the report! I can reproduce, and indeed, it should use UTC for this. Will be fixed in next release.
