### ISSUE TITLE
Not able to set initial PIN with PIV?

### ISSUE THREAD

**Issue by sellout** [Yubico/yubikey-manager#27]
I plugged in a new Yubikey 4C and attempted to use it for PIV. I didn’t see an option for creating a new pin, so I tried using `change-pin`, and pressing return without entering any numbers for the current pin, then using an 8-digit number for the new pin. Here’s the interaction:

```
$ ykman piv change-pin
Enter your current PIN: 
Enter your new PIN: 
Repeat for confirmation: 
Usage: ykman piv change-pin [OPTIONS]

Error: Changing the PIN failed.
$ 
```

**Comment by emlun** [comment]
Sorry for the slow response. Did you try the default PIN `123456`? You can use `ykman piv reset` to reset the PIV settings to factory defaults if needed.

**Comment by sellout** [comment]
Thanks! I needed to do the `reset` before the default would work.
