### ISSUE TITLE
ykman mode "CCID+FIDO+OTP" problem

### ISSUE THREAD

**Issue by alexandre1985** [Yubico/yubikey-manager#272]
- YubiKey Manager (ykman) version: 
```
YubiKey Manager (ykman) version: 3.0.0
Libraries:
    libykpers 1.20.0
    libusb 1.0.22
```
- How was it installed?: `pacman`
- Operating system and version: Manjaro Deepin
- YubiKey model and version: Yubikey 5 NFC
- Bug description summary:

```
$ ykman info | grep "Enabled USB interfaces"
Enabled USB interfaces: OTP+FIDO+CCID

$ ykman mode "CCID+FIDO+OTP"
Mode is already OTP+FIDO+CCID, nothing to do...
(what??)

$ ykman info | grep "Enabled USB interfaces"
Enabled USB interfaces: OTP+FIDO+CCID
```
:-1:

Is this a bug or am I not understanding something? Isn't `ykman mode` supposed to change the order of yubikey applications access?

**Comment by dagheyman** [comment]
Thanks for the report.

No, the mode command enables and disables the different USB transports (OTP, FIDO, CCID), there is no order configurable. The devices come with all three transports enabled out of the box.

With a YubiKey 5 NFC it is also possible to enable/disable different applications as such, over USB and NFC. Look into the `ykman config` commands for that feature.

**Comment by alexandre1985** [comment]
Thank you 😀
