### ISSUE TITLE
Documentation for set-touch `fixed`, `cached-fixed`, and `cached` options

### ISSUE THREAD

**Issue by timkeeler** [Yubico/yubikey-manager#277]
- YubiKey Manager (ykman) version: 3.1.0
- How was it installed?: `brew`
- Operating system and version: OSX
- YubiKey model and version: 5c Nano / 5.1.0
- Bug description summary: Documentation

Is there updated documentation for what `fixed`, `cached-fixed`, and `cached` do?

According to #30 I understand these features may only be available in firmware `5.2.3`, but I may consider updating if I understand what functionality is implemented!

On a side note, is it possible to determine the firmware version before purchasing a new key?

```
> ykman openpgp set-touch aut -h
Usage: ykman openpgp set-touch [OPTIONS] KEY POLICY

  Set touch policy for OpenPGP keys.

  KEY     Key slot to set (sig, enc, aut or att).
  POLICY  Touch policy to set (on, off, fixed, cached or cached-fixed).

Options:
  -a, --admin-pin TEXT  Admin PIN for OpenPGP.
  -f, --force           Confirm the action without prompting.
  -h, --help            Show this message and exit.
```

**Comment by dagheyman** [comment]
Hi, thanks for the report!

I agree, the help text should be updated. The functionality roughly match the [touch policies](https://developers.yubico.com/PIV/Introduction/Yubico_extensions.html) in the PIV application. A cached touch policy is useful when doing multiple operations, for example signing a lot of files. 

Any new order on the web store should have a firmware version with 5.2.3 or higher, and thus support this feature.

**Comment by hashier** [comment]
This explains on/off/cached, but what does `fixed` do?

**Comment by dagheyman** [comment]
@hasier `fixed` means that the touch policy can not be changed without doing a full openpgp reset (which will delete all keys from the device).

**Comment by jmooo** [comment]
How do you know if it's `fixed` to `on` or to `off`?

**Comment by zacheryph** [comment]
@jmooo `ykman openpgp info` tells the current status for each key type

**Comment by trishankatdatadog** [comment]
> Any new order on the web store should have a firmware version with 5.2.3 or higher, and thus support this feature.

Hi Dag, do you know if the FIPS model will ever support the `cached` touch policy?

**Comment by peterbabic** [comment]
I am sorry for a bump, but this is the only real "discussion" about this topic I have found so far:

Could anyone point me to a use case for the `fixed` and `cached-fixed` use case? Why would I want to make sure it is not possible to turn these off, only complete reset? The ADMIN password is still required to change the policy, so it is not like an attacker would just turn this off, so there probably had to be some other reason.

**Comment by relative** [comment]
> I am sorry for a bump, but this is the only real "discussion" about this topic I have found so far:
> 
> Could anyone point me to a use case for the `fixed` and `cached-fixed` use case? Why would I want to make sure it is not possible to turn these off, only complete reset? The ADMIN password is still required to change the policy, so it is not like an attacker would just turn this off, so there probably had to be some other reason.

If a user left their yubikey plugged in and an attacker had remote access to their machine the attacker could change the touch policy if the admin pin was keylogged
