### ISSUE TITLE
YubiKey Manger does not accept complex subjects in PIV certificate requests

### ISSUE THREAD

**Issue by leonard-timmons** [Yubico/yubikey-manager#278]
- YubiKey Manager (ykman) version: 1.1.1
- How was it installed?: using yubikey-manager-qt-1.1.3-win32.exe
- Operating system and version: Windows 10 Pro, 32 bit running in VMWare workstation 15
- YubiKey model and version: Yubikey 5 NFC, Firmware 5.1.2
- Bug description summary:
YubiKey Manager is missing a critical feature of YubKey PIV tool: The ability to create complex subjects in certificate requests. For some reason only the CN is allowed in a certificate request when using the YubiKey Manager. It seems that I have relied on Yubico's assertion that the YubiKey manager would do everything that the YubiKey PIV tool would do to my detriment. I opened case #69485 and the result was that they agreed the functionality was not present. They are under the impression that this functionality is only absent from the graphical tool, but it seems to be missing from the command line as well. 

Steps to reproduce
---
1) Erased the Yubikey 5 using the YubiKey Manager graphical interface
  Click: Applications-->PIV
  Click: Reset PIV, Popup: This action cannot be undone, Click: YES
2) Set the management key
  Click: Configure PINs
  Click: Change Management Key
  Select: Use default
  Click: Generate: a35fa8745984664fd1e412e77997f82ea8c4dead6ec41d67
  Deselect: Protect with PIN
  Click: Finish
3) Set the PUK
  Click: Change PUK
  Select: Use default
  New PUK: RunRam^2
  Confirm new PUK: RunRam^2
  Click: Change PUK
4) Set the PIN
  Click: Change PIN
  Select: Use default
  New PIN: Consul$9
  Confirm new PIN: Consul$9
  Click: Change PIN
5) Generate the public/private keypair
  Open a command line window (non-elevated)
  Browse to C:\Program Files\Yubico\YubiKey Manager
  Issue the command to use slot slot 9a
  ykman piv generate-key --management-key "a35fa8745984664fd1e412e77997f82ea8c4dead6ec41d67" --algorithm RSA2048 9a "Z:\Keys\public.pem"
6) Generate the complex certificate request:
  ykman piv generate-csr --pin "Consul$9" --subject "/CN=Firstname Lastname(Department)/emailAddress=firstname.lastname@ourcompany.com/OU=co-abbr.department/O=Full Company Name Inc/L=Our Town/ST=Georgia/C=US" 9a "Z:\Keys\public.pem" "Z:\Keys\Firstname LastName.csr"

[Please explain what you did when the bug appeared, and if and how you have been
able to reproduce it.]
This occurred on the first use of the YubiKey 5. I did not expect different behavior from the Yubikey 5 with respect to the Yubikey 4. Yubico documentation stated that the YubiKey Manager would do what the YubiKey PIV tool did. I worked the issue with Yubico support and they provided work-arounds that did not work. Eventually admitting that the graphical tool would not accept a complex subject.

Expected result
---
I expected that a parse of the CSR would work the same as the YubiKey PIV Tool.

[What did you expect to happen when you did the above?]
A certificate request with a complex subject that I could submit to any certificate authority.

Actual results and logs
---
Firstname LastName.csr contains the following:

-----BEGIN CERTIFICATE REQUEST-----
MIIC/zCCAecCAQAwgagxgaUwgaIGA1UEAwyBmi9DTj1GaXJzdG5hbWUgTGFzdG5h
bWUoRGVwYXJ0bWVudCkvZW1haWxBZGRyZXNzPWZpcnN0bmFtZS5sYXN0bmFtZUBv
dXJjb21wYW55LmNvbS9PVT1jby1hYmJyLmRlcGFydG1lbnQvTz1GdWxsIENvbXBh
bnkgTmFtZSBJbmMvTD1PdXIgVG93bi9TVD1HZW9yZ2lhL0M9VVMwggEiMA0GCSqG
SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDK3YTvz4p9b7UgXptIMXRd036iHx2j0e+z
8WcPKJSI12urTOi+xXbo14ROy8eUYUOWadyTPN42ff2AQNmRkxsHUuIqIxCNTclC
5HXhEGAbKZd7vEfPQzXFH7Cjg8SSW19YSxZyLoa/ED7Ejt+LTEELreOX0xAYxuKy
rMw4PlTZP1lV5qUjUg+QBw4H8EtGmG59R37SxV7adnbxXHt1BNGUPLmwqhqaG38/
0r8/zb9AI4dFFbP/a/LRukSwLC+6wV0QGEs7mgtjbV97g0P0tcT6oNA1Mr0eNHHg
og0+8SPZgy6olJ6tgBTTC/nzIzeLRXih0pSYz4cZC3mHF85XUKurAgMBAAGgETAP
BgkqhkiG9w0BCQ4xAjAAMA0GCSqGSIb3DQEBCwUAA4IBAQDI/CsLHh+7fnbADQBo
9WQURjvMlyBpcPzWtf1/Y/LgNSpLhgeaTpmnFvIKREd7u/RxOZBMgwqwB+idJ6rJ
2SmwL6RF1SAcuVbb0QgGGvK8xL5z6nkNmBWa4UD/i3Zm/CSyAhpgrA/O30hdwu8V
+o3P/8Qt7CSR0V8iBnphQbzyvFOUQDZp5+sV48QLLCcGvdj6JfRaz91BSR77vFkq
B8psEFXXg/aGbl41q4LRchaldi62xbJRCyYy3+TtKSnP+APfyavpPr8jc+O5xkMB
0HOHsyiCaLOzGaFlX5Nbyh9nanAhPdCbU2No68J2D/tPRnHT4ETiuZZmSAnKH41f
AryV
-----END CERTIFICATE REQUEST-----

[What actually happened?]
When decoded, the CN is everything in the "--subject" parameter without interpretation

Other info
---
I didn't really expect the support staff to try to resolve this issue. 

[Anything else you would like to add?]

I've used this functionality as the basis of a complex infrastructure. I never imagined that someone would forcibly set a subject line for a certificate request to the CN and CN only. I mean, it's not really the subject, it is the CN and the "--subject" is a misnomer. Yubico has retired the Yubikey 4 and they are no longer available. The YubiKey PIV manager will not work with the Yubikey 5. So I'm kind of stuck. If the functionality i'm looking for is available with the Yubikey 5, but in Linux, I could make that work.

**Comment by dagheyman** [comment]
Hi, thanks for the report. This is a known limitation right now, and we do want to add this functionality. 

What is stopping you from using yubico-piv-tool as a workaround in the meantime? I guess it's the "protect management key with PIN" functionality, since that is not supported in yubico-piv-tool? Maybe the CSR can be created before storing the management key on the device?

But yes, there is at least two issues with ykman here:
- missing support for creating CSR with complex subjects (in both GUI and CLI)
- confusing argument name (--subject) when it only sets the CN

**Comment by leonard-timmons** [comment]
Hi dagheyman and thanks for the reply. Unless I'm missing something, the yubico-piv-tool does not support the Yubikey 5 devices. At least the graphical tool does not see them. Now if I can get the command line to work, then I'd be in heaven. I don't need the "protect management key with PIN" as I turned that off in my example above.

The thing that kept me and Yubico support from figuring this out earlier, I think, is the removal of this functionality with respect to the YubiKey PIV tool. But we're thinking that the Yubikey Manager is a successor to the Yubikey PIV tool, when it may be a successor to the Yubikey PIV Manager which had no such functionality. Of course, the new Yubikey Manager may have been written from scratch, which might explain the loss of functionality since the focus seems to have been moved to windows compatibility/functionality.

My problem is that I've purchased the Yubikey 5 devices and made commitments to customers with the assurance from Yubico that there was no loss of functionality from the Yubikey PIV Tool to the Yubikey Manager. That was a mistake, but I actually could not imagine and still cannot imagine that a smartkey would not be able to create a CSR properly.

I'll try the yubico-piv-tool command line with the Yubikey 5 and see what happens. My only other option is to purchase Yubikey 4 keys from eBay and hope no one notices that they have "Wired" emblazoned on them.

**Comment by dagheyman** [comment]
> Unless I'm missing something, the yubico-piv-tool does not support the Yubikey 5 devices.

yubico-piv-tool (CLI) **is** definitely compatible with the YubiKey 5 Series, and still maintained. If you find documentation that states otherwise, please let me know so we can fix it. There is windows builds of the latest version available here: https://developers.yubico.com/yubico-piv-tool/Releases/

YubiKey PIV Manager (GUI) on the other hand is deprecated and not supported anymore.

**Comment by leonard-timmons** [comment]
Thanks dagheyman,, that makes my week! I figured I was stuck after working with support. Since they didn't mention the work-around, I'm guessing they don't know.

**Comment by dainnilsson** [comment]
ykman 4.0 now supports this using the format specified in https://tools.ietf.org/html/rfc4514

**Comment by bajtpop** [comment]
Hi, sorry for opening old issue. Are you sure ykman support rfc4514 ?
I'm trying set
` ykman piv certificates request -s "CN=test,C=PL,ST=something" 9a`
result
`Subject: CN = "CN=test,C=PL,ST=something"`
`YubiKey Manager (ykman) version: 4.0.0a1`

**Comment by leonard-timmons** [comment]
Noted. I’ll upgrade.

-leonard

Leonard Timmons | Manager IT/OT
D: +1 770 409 4225  |  M: +1 404 702 0970 |  Helpdesk: +1 800 241 7317
