### ISSUE TITLE
ykman missing support for openpgp configuration with kdf enabled pins

### ISSUE THREAD

**Issue by bradyellison** [Yubico/yubikey-manager#279]
- YubiKey Manager (ykman) version: 3.1.0
- How was it installed?: homebrew
- Operating system and version: OSX 10.15 (19A583)
- YubiKey model and version: 5C nano, 5.2.3
- Bug description summary:
Firmware 5.2.3 enabled kdf openpgp pins but once they are set ykman is unable to authenticate against them.

Steps to reproduce
---

```
gpg --edit-card --expert
> admin
> kdf-setup

ykman openpgp set-touch SIG on
```

Before kdf-setup, the management tool works fine. After enabling kdf, the tool is unable to transmit derived credentials and instead fails the pin verification request by attempting to always send the pin utf-8 encoded.

Expected result
---

Touch can be edited with the admin openpgp key after kdf is enabled on the card.

Actual results and logs
---

Admin PIN fails to verify

**Comment by dagheyman** [comment]
Thanks! Yes, we should look into adding support for this in ykman.

**Comment by emilazy** [comment]
Is there any workaround for this (e.g. can `gpg --card-edit` do it)? I tried running `ykman openpgp set-touch` before the `kdf-setup`, but it seems like the settings are lost in the conversion.

**Comment by maximbaz** [comment]
Personally I ended up factory-resetting the card...

**Comment by dkrm0** [comment]
Is there an ETA for the release of this fix?

**Comment by milpog** [comment]
I've installed 12efa59 version via pip using this command and can confirm that `ykman` is working properly with `kdf-setup` enabled. I am using Yubikey 5C nano with 5.2.6 firmware. Would be nice to release new version of `yubikey-manager` so we can also install it via brew or version tag.

```shell
pip3 install git+git://github.com/Yubico/yubikey-manager.git@12efa59#egg=yubikey-manager
```

**Comment by kirelagin** [comment]
That’s actually a big deal. I spent half an hour trying to figure out what is going on and if I am going crazy...
This change is big enough to deserve a release.
