### ISSUE TITLE
"Security Key NFC" only works with ykman with elevated privileges

### ISSUE THREAD

**Issue by DaveMiddleton** [Yubico/yubikey-manager#282]
- YubiKey Manager (ykman) version: 3.1.0
- How was it installed?: Installed with the Yubikey Manager GUI (Qt)
- Operating system and version: Windows 10 Pro 64-bit 1903 Build 18362.418
- YubiKey model and version: Security Key NFC version 5.1.2
- Bug description summary: YKMAN cannot connect to "Security Key NFC" if not in Elevated Mode

Steps to reproduce
---

1. Open a Powershell window in user mode and type: ykman.exe info. The result is a failed  connection to the "Security Key NFC".
2. Now open a Powershell window in Elevated Mode (Admin) and do the same. No issue with connecting  to the "Security Key NFC".

Note:
 **There is no issue with the YubiKey 4 version 4.3.4**.

[Please explain what you did when the bug appeared, and if and how you have been
able to reproduce it.]

Was using the YubiKey Manager GUI for the  Security Key NFC in my work account which is a "normal" user account. It failed to connect. So I tried the CLI.

Expected result
---
Firmware version: 5.1.2
Form factor: Keychain (USB-A)
Enabled USB interfaces: FIDO
NFC interface is enabled.

Applications    USB             NFC
OTP             Not available   Not available
FIDO U2F        Enabled         Enabled
OpenPGP         Not available   Not available
PIV             Not available   Not available
OATH            Not available   Not available
FIDO2           Enabled         Enabled

[What did you expect to happen when you did the above?]

- I expect the YubiKey Manager to connect to any YubiKey in any privilege mode.

Actual results and logs
---

- The YubiKey Manager GUI shows a screen with "Insert your YubiKey".
- The CLI shows "Error: Failed connecting to Security Key by Yubico [FIDO]"

[What actually happened?]

Other info
---

[Anything else you would like to add?]

Once you know how to use the YubiKey Manager for the "Security Key NFC" there is no issue. However, if you don't you may report a malfunctioning key or YubiKey Manager application.

**Comment by dagheyman** [comment]
Thanks. Unfortunately there is no way to access a FIDO device without elevated privileges on Windows 10, but we will look into improving the error messages / user experience around this.

**Comment by dainnilsson** [comment]
Error handling has been improved in ykman 4.0 to make it more clear why it's failing.
