### ISSUE TITLE
ykman throws exception when pcscd.socket and pcscd.service units stopped

### ISSUE THREAD

**Issue by gbcox** [Yubico/yubikey-manager#283]
From https://bugzilla.redhat.com/show_bug.cgi?id=1684945

Stopped pcscd.socket and pcscd.service units. Ran ykman list.

reporter:       libreport-2.10.1
cmdline:        /usr/bin/python3 /usr/bin/ykman list
crash_function: __init__
exception_type: smartcard.pcsc.PCSCExceptions.EstablishContextException
executable:     /usr/bin/ykman
interpreter:    python3-3.7.4-1.fc30.x86_64
kernel:         5.3.6-200.fc30.x86_64
package:        yubikey-manager-2.1.0-2.gitb44d719.fc30
reason:         PCSCContext.py:40:__init__:smartcard.pcsc.PCSCExceptions.EstablishContextException: 'Failure to establish context: Service not available.'
runlevel:       N 5
type:           Python3
uid:            5242

**Comment by fdennis** [comment]
Hi.
Could you please elaborate a bit more regarding the specific issue? What is the problem and what is the expected behavior? pcscd needs to be running for CCID. That's why you get an exception when running ykman list if pcscd is stopped.

**Comment by rathann** [comment]
@fdennis The problem is that the exception is unhandled. The expected behaviour would be writing out a nice error message (with a suggestion to run `systemctl start pcscd.service` perhaps) instead of getting a python stack trace which you have to sift through to see the actual error. I think that's a reasonable expectation, wouldn't you agree?

**Comment by rathann** [comment]
Looks good, thank you!

**Comment by lrenaud** [comment]
May I request this gets tagged in the documentation somewhere? I'm an AppImage user, and adding the `pcscd` daemon fixed the issue, but I was surprised I needed to install anything to use the AppImage given that it's supposed to be a contained bundle.

I'm not asking for a change in behavior, but highlighting this bug somewhere in the documentation as a limitation of some of the distribution formats will likely prevent confusion in the future.
