### ISSUE TITLE
Suppress "Usage:" in stderr when yubikey not found

### ISSUE THREAD

**Issue by ghicks-rmn** [Yubico/yubikey-manager#296]
- YubiKey Manager (ykman) version: 3.1.0
- How was it installed?: Homebrew
- Operating system and version: MacOS Catalina 
- YubiKey model and version: Yubikey 5C
- Bug description summary:

When ykman fails due to "No YubiKey Detected!" the stderr output includes usage text, even though the actual command is valid - it just can't be executed because there's no key to query.

I'm using ykman within a script to automatically pull TOTP codes, and ideally I'd like for it to report ONLY the error message on failure. Printing usage text for a hidden subcommand just ends up confusing things for the end user when they run my script. At the very least, it'd be nice to have an argument to suppress that part of the output.

Steps to reproduce
---

Run the following command with no yubikey connected:
```
$ ykman oath code -s "mycode"
```

Expected result
---

```
$ ykman oath code -s "mycode"
Error: No YubiKey detected!

```

Actual results and logs
---

```
$ ykman oath code -s "mycode"
Usage: ykman [OPTIONS] COMMAND [ARGS]...
Try "ykman -h" for help.

Error: No YubiKey detected!

```

Other info
---

It's worth noting that this behavior does NOT occur for other errors. Same command, this time with a Yubikey connected but no matching oath code configured:

```
$ ykman oath code -s "mycode"
Error: Multiple matches, please make the query more specific.

```

**Comment by dagheyman** [comment]
Thanks for the report. I agreed that the usage text should be suppressed when the actual command is valid.

**Comment by dainnilsson** [comment]
ykman 4.0 no longer shows usage for non-usage related errors.
