### ISSUE TITLE
cached touch policy

### ISSUE THREAD

**Issue by deadc0de6** [Yubico/yubikey-manager#30]
Is there a way to set the touch policy to *cached* when using a yubikey for pgp and ssh ?

Found a way to do it for PIV (https://developers.yubico.com/PIV/Introduction/Yubico_extensions.html) but `ykman` doesn't seem to provide that option.

**Comment by emlun** [comment]
Sorry, no, there isn't. The hardware supports this for PIV only. We might add this feature (still for PIV only) to `ykman` sometime, but nothing is decided about it at this point.

**Comment by emlun** [comment]
Wait, sorry, actually it's already implemented in `ykman`. Still only for PIV, though.

**Comment by deadc0de6** [comment]
ok thanks

**Comment by dagheyman** [comment]
@tyhicks Happy to inform you that any device [with firmware version 5.2.3](https://www.yubico.com/2019/08/whats-new-in-yubikey-firmware-5-2-3/) or higher supports cached touch policy for OpenPGP. You'll need ykman 3.1.0 to set it.
