### ISSUE TITLE
Support --json output

### ISSUE THREAD

**Issue by jonasfj** [Yubico/yubikey-manager#31]
A simple option like `--json` or `--yaml` would be nice for many of the outputs.

Examples include `ykman oath list --json` and `ykman oath code --json`

I would also support `ykman oath code 'name of token' --raw` to just output the raw code.

**Comment by emlun** [comment]
Thanks for the suggestion, we'll definitely consider it. In the meantime, your `--raw` suggestion is already implemented in master as the `--single` flag which will be in the next release.

**Comment by dagheyman** [comment]
After some internal discussion we decided that json output support will not be added to this tool for now, the python API is recommended for scripting purposes.
