### ISSUE TITLE
Set U2F mode only, now can't see device

### ISSUE THREAD

**Issue by headius** [Yubico/yubikey-manager#33]
After reading instructions in #20 about how to set the yubikey modes to disable OTP, I set mine to only be in u2f mode. That command succeeded, but I soon realized my key was no longer visible for logging into macOS. I have tried to use ykman to restore ccid mode, but I always get the following error:

```
[] ~ $ ykman mode u+c
Usage: ykman [OPTIONS] COMMAND [ARGS]...

Error: Failed connecting to the YubiKey.
```

This occurs even if I wake the key first by touching it.

I am using the nano C version of Yubikey on a 2016 MacBook Pro running latest macOS.

Help!

**Comment by headius** [comment]
Ping? I'm kinda stuck here. I tried to use tools from Windows to reset the key, but they were unable to see it.

**Comment by dainnilsson** [comment]
Hmm, does U2F work in Chrome?

The behavior seems to indicate that ykman can't open the device over the U2F transport. I'd suggest trying it with a different computer, but if I understand you correctly you've tried this on a Windows PC with the same result as well? Or was the Windows attempt on the same PC? In a VM?

You could try using libu2f-host as well: https://developers.yubico.com/libu2f-host/Mode_switch_YubiKey.html

**Comment by headius** [comment]
Ok, either the libu2f command line fixed it, or something else changes to make it work. Either way, it appears I have access to my key again!

FWIW, the Windows attempt was made on the same MacBook Pro 2016, using a bootcamp partition (not a VM).
