### ISSUE TITLE
Yubikey button not working

### ISSUE THREAD

**Issue by warzyxz** [Yubico/yubikey-manager#333]
- YubiKey Manager (ykman) version:
- How was it installed?: Windows Installer
- Operating system and version: Windows 10
- YubiKey model and version:
- Bug description summary:

Hey guys, my yubikey button stoped working for a while now, I cannot login . How can I use the yubikey manager to trigger the button ? Thank you.

**Comment by dagheyman** [comment]
Sorry, this is not the right place for this type of issues, I'd suggest opening a support ticket here: https://support.yubico.com/support/tickets/new
