### ISSUE TITLE
keyboard-layout FR in ykman (like GUI)

### ISSUE THREAD

**Issue by trollsroyce** [Yubico/yubikey-manager#339]
More a feature request but,

Have you planned to add the option FR in ykman with opt static function (like the GUI does) ?

Thank you

**Comment by dagheyman** [comment]
Hi,
Yes, this is actually [added](https://github.com/Yubico/yubikey-manager/commit/d995c2ca10a7a83a7a37f7b1cbdb561c4ba69020#diff-3c15116a2ca7cb642199a7eeacf72290) on the master branch, it's just not released yet. Will be in the next release.

**Comment by trollsroyce** [comment]
Hi,

don't won't to bother you about this, but have you an estimated release
date of the next release of ykman.

We really need the functionality to use our yubikey.

Thank you.

**Comment by fdennis** [comment]
@trollsroyce 
Hi,
Thanks for letting us know that this is a valuable feature.
We are currently planning the next releases.  I will let you know regarding an estimated release date as soon as I can.

**Comment by dainnilsson** [comment]
This has been included in ykman 4.0, now released.
