### ISSUE TITLE
Serial number doesn't show 

### ISSUE THREAD

**Issue by ElijahLynn** [Yubico/yubikey-manager#340]
This is a follow up from your internal Zendesk tracker > #208990. 

- YubiKey Manager (ykman) version:
```
❯ ykman -v
YubiKey Manager (ykman) version: 3.1.1
Libraries:
    libykpers 1.20.0
    libusb 1.0.23
```

- How was it installed?: 
`yay --sync yubikey-manager` https://aur.archlinux.org/packages/yubikey-manager-git

- Operating system and version:
Arch Linux 
```
❯ uname -a
Linux archlinux 5.6.13-arch1-1 #1 SMP PREEMPT Thu, 14 May 2020 06:52:53 +0000 x86_64 GNU/Linux
```
- YubiKey model and version:
Yubikey Nano 

- Bug description summary:
Can't see serial number with CLI tool. 

Steps to reproduce
---

[Please explain what you did when the bug appeared, and if and how you have been
able to reproduce it.]

```
❯ ykman list --serials
YubiKey NEO [OTP+FIDO]
<no serial>
```

Expected result
---

[What did you expect to happen when you did the above?]
Serial number shows

Actual results and logs
---

[What actually happened?]

Other info
---

[Anything else you would like to add?]

**Comment by ElijahLynn** [comment]
K, so it works if I remove and reinsert it both with `ykman` AND the GUI Personalization tool. This works for now, closing.

**Comment by xornet-sl** [comment]
But this functionality still doesn't work!!!
I have a hedless server and can not list any keys normally. All I see is `YubiKey 5 [OTP+FIDO+CCID]` How can I get a serial number?
