### ISSUE TITLE
No complex subject allowed in "ykman piv generate-csr"

### ISSUE THREAD

**Issue by cornelinux** [Yubico/yubikey-manager#342]
- YubiKey Manager (ykman) version: 3.1.1
- How was it installed?: Ubuntu Repository
- Operating system and version: Ubuntu 18.04
- YubiKey model and version: 5.1.2
- Bug description summary: Can not create CSR with a more complex subject

# Steps to reproduce

1. Create a key pair on the yubikey:
 
~~~~bash
ykman piv generate-key --algorithm RSA2048 9a user.pub
~~~~

2. Now create a CSR with this public key:

~~~~bash
ykman piv generate-csr -s "/CN=user/DC=example/DC=com" 9a user.pub user.req
~~~~
The resulting CSR has the subject

    CN = "/CN=user/DC=example/DC=com"

# Expected result

I would expect that I get a CSR and a certificate with a subject like

    CN = user, DC = example, DC= com

# Actual results and logs

The value specified in -s is always put completely into the CN field. It is not possible to define subjects, that consist of CN, OU and DC.

However, this is necessary for several use cases.

**Comment by dagheyman** [comment]
Thanks, yes this is currently a limitation in the tool. Duplicate of #278

**Comment by cornelinux** [comment]
I did not see this. The other issue is well documented. Closing mine.
