### ISSUE TITLE
Copy OATH code to clipboard

### ISSUE THREAD

**Issue by jochenchrist** [Yubico/yubikey-manager#355]
- YubiKey Manager (ykman) version: 3.1.1
- How was it installed?: bew
- Operating system and version: macOS

Feature-Request:
Copy the OATH code to clipboard after succesful touch.

```
ykman oath code myservice
```

sothat `pbpaste` can be used to paste the code.

If there are multiple credential defined, use the first one. 
 You might consider defining an option (such as --clipboard) for security reasons.

**Comment by nevun** [comment]
Just a comment, not officially answering for Yubico, have you tried `yank` ?

 $ brew install yank
 $ ykman oath code | yank -g "[0-9]+"

See it in action: https://asciinema.org/a/55dugmxm90yoP8zKq2Lvay6E9

**Comment by jochenchrist** [comment]
Maybe it also would be sufficient to write only the code to stdout.

Then tools like `pbcopy` can be used to copy it to clipboard or integrate it in other CLI tools directly.

**Comment by ronniewood** [comment]
johenchrist - i think this is a great feature request and believe yubico team may solve it - 

For today, here is how i do it in a bash script, for a solution that works even in case you have multiple credentials.  If you only have one credential, you do not need to pass in the first variable.  I am on a mac and pbcopy will copy to my clipboard.  The awk command separates the 2 fields in the output and pipes the second field with the token code to the clipboard. 
ykman oath code $1 |awk '{print $2}' |pbcopy

**Comment by dainnilsson** [comment]
I just wanted to point out that there's already a `--single/-s` flag which will ensure that only one credential is matched, and (if successful) output the code part only. The purpose of it is to be able to pipe the output directly to something else, like pbcopy.

**Comment by jochenchrist** [comment]
@dainnilsson Awesome, this is what I was looking for.

This works for me with version 3.1.1:
```
ykman oath code --single MyService | pbcopy
```

**Comment by dainnilsson** [comment]
Great! Sorry I didn't see this sooner!

**Comment by ronniewood** [comment]
Thanks!   the single flag works great for a workaround until they add this.

**Comment by emlun** [comment]
See also this related utility (not an official Yubico project): https://github.com/emlun/yubikey-oath-dmenu
