### ISSUE TITLE
Yubikey security on setting it up

### ISSUE THREAD

**Issue by Impeekay** [Yubico/yubikey-manager#356]
- YubiKey Manager (ykman) version: 1.1.5
- How was it installed?: AppImage
- Operating system and version: ubuntu 20.04 LTS
- YubiKey model and version: yubikey 5 nfc 5.2.6
- Bug description summary:
 This is more of a doubt that I have. So I'm setting up a yubikey, I set up all the applications with the preferred settings. After that how do I ensure that someone doesn't just use the yubikey-manager and just reset it and use it on their own? I am aware of the config lock `set-config-lock` but that just seems to lock the configs and types of enabled configs. Any help would be appreciated.

**Comment by fdennis** [comment]
Hi. I'm not quite sure what your concern is. Maybe you could be a bit more specific of what you're worried about? Typically you wouldn't give anyone you don't trust access to your YubiKey, by keeping it with you on a keychain or similar. Anyway, for questions about our products that don't strictly relate to this tool, please check out our support page: https://support.yubico.com/support/home

**Comment by Impeekay** [comment]
Cool, yea that makes sense as to strangers might not have access to the keys anyways. Thanks for that.
