### ISSUE TITLE
Error during config change

### ISSUE THREAD

**Issue by Impeekay** [Yubico/yubikey-manager#357]
- YubiKey Manager (ykman) version: 1.1.5
- How was it installed?: AppImage
- Operating system and version: Ubuntu 20.04 LTS
- YubiKey model and version: 5 NFC 5.2.6
- Bug description summary:

Before using the Yubikey-manager, by the directions of an old post of yubikey, I used the Yubikey personalization tool, using which I enabled protection on the configuration slots with the serial number of the device, which I'm not sure how to remove as of now since in the personalization tool it is not working. 

But when I come to change the configs on the yubikey manager, it prompts me for a lock code and upon searching, I figured it would be padded hexadecimal of my serial number(assumption). So I try other codes and if I enter those it says wrong code. whereas, If I enter what I might think is the correct password it throws an error on the terminal as
`qml: Unmapped error: null APDU error: SW=0x6983`

Kindly, help me out resolve this, either clear the access code entirely because yubikey personalization tool doesn't seem to do it.

**Comment by fdennis** [comment]
This sounds like something our customer support team can take a look at. You can reach them here https://yubi.co/support-ticket
