### ISSUE TITLE
ykman fido delete fails: does not detect fullmatch if two resident cred's share same substring

### ISSUE THREAD

**Issue by Sebi2020** [Yubico/yubikey-manager#370]
- YubiKey Manager (ykman) version: 3.1.1
- How was it installed?: Through the Ubuntu PPA
- Operating system and version: #64~18.04.1-Ubuntu SMP Wed Dec 9 17:11:11 UTC 2020
- YubiKey model and version: Yubikey 5 NFC with Firmware 5.2.7
- Bug description summary:
If you have multiple FIDO2 residental credentials stored with the same prefix, for example "test" and "testuser" it's impossible to delete "test" because you get an error, saying that the request `ykman fido delete test` matches multiple entries. test and *test*user

## Steps to reproduce
1. Register with Webauthn on webauthn.io with residental credentials (advanced section) two times with usernames, one as a prefix and one which consists of prefix + suffix. For example test and testuser.
2. Try to run `ykman fido delete [insert username prefix here]` to delete the resident credential.
3. It will fail because ykman does not use the smallest full match.

## Expected result
ykman (or the firmware,  I don't know, would be bad, because firmware updates are not possible) should be able to delete the credential, because ykman/firmware should recognize that the prefix "test" is a full match.

## Actual results and logs
You are forced to delete "testuser" first to delete "test".
```
--- SNIP ---
2021-01-02T16:33:21+0100 DEBUG [ykman.cli.fido.delete:169] Failed to delete resident credential
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ykman/cli/fido.py", line 164, in delete
    ctx.fail('Multiple matches, make the query more specific.')
  File "/home/sebi/.local/lib/python3.6/site-packages/click/core.py", line 550, in fail
    raise UsageError(message, self)
click.exceptions.UsageError: Multiple matches, make the query more specific.
Usage: ykman fido delete [OPTIONS] QUERY
Try 'ykman fido delete -h' for help.

Error: Failed to delete resident credential.
```

**Comment by fdennis** [comment]
Hi,
I agree that this can cause issues. When you execute `ykman fido list` you will get back two parameters for every entry: `username `and `rp.id`. We recently (https://github.com/Yubico/yubikey-manager/pull/359) added a third parameter to this, `user.id`, which should be unique. I think that will solve your problem. This will be released in the next version.

**Comment by Sebi2020** [comment]
@fdennis I think these are two issues. One with the implementation if you use multiple partially matching usernames on the same RP and one with the documentation, which does not explain the QUERY parameter format in detail. For example "how do I (as a user) specify `username`, `rp.id` or `user.id` to `ykman fido delete`. For example I've tried to delete the user `test` with `ykman fido delete "test (webauthn.io)"`, but that failed.

**Comment by fdennis** [comment]
@Sebi2020 The command you wrote should work, and does work for me. See example:
`$ ykman fido list`
`testuser (webauthn.io)`
`test (webauthn.io)`
`$ ykman fido delete "test (webauthn.io)"`
`Delete credential test (webauthn.io)? [y/N]:`
I tried this on Windows, ykman 3.1.1. 

Could you try my example and see how that goes?

**Comment by Sebi2020** [comment]
@fdennis I'm going to replay these commands and post the results.

**Comment by Sebi2020** [comment]
@fdennis Okay, it works if you add the rp.id.

**Comment by dainnilsson** [comment]
This should behave better in ykman 4.0.
