### ISSUE TITLE
ykman fido forces you to set a fido2 PIN

### ISSUE THREAD

**Issue by Sebi2020** [Yubico/yubikey-manager#373]
- YubiKey Manager (ykman) version:
  ```
  YubiKey Manager (ykman) version: 3.1.1
  Libraries:
    libykpers 1.20.0
    libusb 1.0.22
   ```
-  How was it installed?: Windows Installer
- Operating system and version: Windows 10 Home - Version: 1909, Build: 18363.1256
- YubiKey model and version: Yubikey 5 NFC
- Bug description summary:
  Yubico Manager does not allow you to list resident credentials if you haven't setup a PIN. If you look at the documentation, there is no evidence that a FIDO2 PIN is required. Even the FIDO2/CTAP 2 spec does not require a PIN to be set.

Steps to reproduce
1. Plug in a fresh  Yubikey (5 NFC) with FIDO2 support 
  1.1 If you don't have a fresh yubikey, reset the fido2 application (`ykman fido reset`)
2. Start a command prompt with admin privileges.
3. Go to ykman`s binary directory
4. Enter `ykman fido list [QUERY]` and/or `ykman fido info`.3

Expected result
ykman should not complain about yubikeys without a pin because the specs doesn't require a pin to be set. You should be able to manage the fido2/u2f application without a pin. (It currently looks like ykman considers the key to be unconfigured if you do not set a fido2 pin.

**Comment by dainnilsson** [comment]
I believe you are correct. We'll look at fixing this for the next version of ykman!

**Comment by dainnilsson** [comment]
Upon looking at this a bit closer, I don't think there's anything wrong here. While a PIN does not need to be set for normal use, any commands involving CredentialManagement (`ykman fido list` etc.) DO require a PIN. As for `ykman fido info` - it work's with or without PIN, however the only "info" it provides is whether or not a PIN is set, and how many PIN attempts remain if one is set.

**Comment by Sebi2020** [comment]
> DO require a PIN
Is this documented somewhere?

**Comment by dainnilsson** [comment]
https://fidoalliance.org/specs/fido2/fido-client-to-authenticator-protocol-v2.1-rd-20191217.html#authenticatorCredentialManagement - this command requires `pinUvAuthParam` to be present, which need a PIN to be obtained.

**Comment by Sebi2020** [comment]
Sorry, maybe my question was misleading. I mean if this is documented for ykman in the command line reference. It wasn't clear to me, but maybe I've missed it in the manual.

**Comment by dainnilsson** [comment]
Ah, I see what you mean. I've made sure it's now more explicit in the --help output for the commands in the coming 4.0.0 version.
