### ISSUE TITLE
NFC interface not available with YK Neo

### ISSUE THREAD

**Issue by ajs256** [Yubico/yubikey-manager#374]
- YubiKey Manager (ykman) version: 3.1.1
- How was it installed?: Homebrew
- Operating system and version: macOS 11.1
- YubiKey model and version: YubiKey NEO 3.5.0
- Bug description summary:

When trying to run `ykman otp ndef 2`, I get an error that the "NFC interface is not available".

Steps to reproduce
---

Run `ykman otp ndef 2` as a normal user or root.

Expected result
---

The command to work.

Actual results and logs
---

```
% ykman otp ndef 2 
Usage: ykman otp ndef [OPTIONS] [1|2]
Try "ykman otp ndef -h" for help.

Error: NFC interface not available.
```

**Comment by ajs256** [comment]
Scanning the key with my iPhone 8 prompts me to open a `(null)` link.

**Comment by fdennis** [comment]
Hi,
It does indeed seem to be some problems with this. Fortunately, we have been working on a new version of ykman and the same issues do not appear in that one. It has not yet been released, however if you want to try to build it yourself you can find it in the `next` [branch](https://github.com/Yubico/yubikey-manager/tree/next).

**Comment by ajs256** [comment]
Hey @fdennis, thanks for getting back to me. I'm not that familiar with Python build processes, so could you please tell me where I could find a built binary? The CI doesn't appear to upload after it builds.

**Comment by ajs256** [comment]
Could someone please help me with this error:
`AttributeError: dlsym(RTLD_DEFAULT, IOObjectRelease): symbol not found`

**Comment by fdennis** [comment]
@ajs256 Thank you for testing and reporting back. You found a bug and we have now fixed it. You have to do a `git pull` in the yubikey-manager repository to get the latest updates. Then run
`pip3 uninstall fido2`
`pip3 install .`
This should fix it for you.

**Comment by ajs256** [comment]
It doesn't crash now, but running `ykman otp ndef 2` (or even `ykman otp info`) says "Error: No YubiKey found with the given interface(s).". Is there a way to "reset" the OTP interface? Or do I need a whole new key?

**Comment by ajs256** [comment]
This is fixed now, I will close the issue.
