### ISSUE TITLE
New key signing releases with missing trust path.

### ISSUE THREAD

**Issue by Foxboron** [Yubico/yubikey-manager#379]
Yo!

There is a new key from `Dain Nilsson <dain@yubico.com>` that is signing releases for this software. I haven't been able to find a trust path from `Dag Heyman <dag@yubico.com>` or `Emil Lundberg (Software Developer) <emil@yubico.com>` to that key.

It would be great if there could be some cross-signatures for this key, or a statement about the new key could be made like `libvirt` recently did. https://libvirt.org/downloads.html#keys

**Comment by dainnilsson** [comment]
Hi! We list the keys used for signing releases on this page: https://developers.yubico.com/Software_Projects/Software_Signing.html

**Comment by Foxboron** [comment]
Ahhh, I realized I probably have asked the same question previously in 2019 or 2020 :/ Sorry for the noise!
