### ISSUE TITLE
yubikey-manager requires python-fido2 < 0.90 but Fedora 34 uses python-fido2 0.90-2

### ISSUE THREAD

**Issue by gbcox** [Yubico/yubikey-manager#382]
Refer to:  https://github.com/Yubico/yubikey-manager/issues/378

Currently F34 is being built for testing and it includes python-fido2 0.90-2.  
F34 is schedule to be released approximately, April 2021.

Will a compatible version be released in time?  Thanks much!

**Comment by dainnilsson** [comment]
Thanks for the heads up! We aim to have yubikey-manager 4.0 out by April (probably towards the end of March). Barring any big delays we should be able to meet this.

**Comment by gbcox** [comment]
Thank you very much.  In the meantime if you have a beta build available, please let me know and I'll put it in the F34 repository so people can use it to test.

**Comment by nbraud** [comment]
OK; that would probably be too late for Debian bullseye (though maybe I can squeeze in a last update if I ask the release team nicely) so I'll roll back python-fido2 0.9.0 tomorrow or so

**Comment by dainnilsson** [comment]
@nbraud is there a specific date when a ykman 4.0 release would have to be done by to make it into Bullseye?

**Comment by nbraud** [comment]
The date for full freeze is yet to be announced, but hard freeze will be on March 12th.

**Comment by dainnilsson** [comment]
We're looking at moving the release date for this to target the end of Feb instead. Would that mean we still have a shot at making it into Bullseye?

**Comment by nbraud** [comment]
Yeah, definitely.  Thanks  <3

**Comment by dainnilsson** [comment]
I've now released an alpha: `4.0.0a1`. It's published to PyPI and also tagged in this repo.
Note that we also just released python-fido2 0.9.1 to include some error code definitions that were missing in the 0.9.0 release.

There are substantial build-system changes to ykman 4.0.0, I hope these do not cause issues for packaging. If they do, let us know and we'll see what we can do about it!

**Comment by nbraud** [comment]
> I've now released an alpha: `4.0.0a1`. It's published to PyPI and also tagged in this repo.

Thanks a lot, this does save me a lot of work  :)


> Note that we also just released python-fido2 0.9.1 to include some error code definitions that were missing in the 0.9.0 release.
> There are substantial build-system changes to ykman 4.0.0, I hope these do not cause issues for packaging. If they do, let us know and we'll see what we can do about it!

OK; I'll have a stab at packaging that shortly, and I'll let you know how it goes.

**Comment by nbraud** [comment]
[Done.] This wasn't entirely easy (Poetry isn't packaged in Debian yet, and I hit some `dh-python` bug when using a `setup.py` file generated by `dephell`) and I had to disable automated tests for the moment (test dependencies not packaged in Debian yet) but I'll try to improve the situation soonish.

[Done.]: https://tracker.debian.org/news/1227482/accepted-yubikey-manager-400a1-1-source-into-unstable/

**Comment by gbcox** [comment]
Should I be building from 4.0.0a1 or next?  I noticed some errors on 4.0.0a1...
Thanks!

**Comment by dainnilsson** [comment]
What kind of errors? Development will continue on next where any issues we find i the alpha will be addressed. So far there's a commit or two, but nothing major, and 4.0.0a1 should work just fine, so I'd suggest targeting that for packaging for now.

**Comment by gbcox** [comment]
Well, when I unzipped the archive, it didn't have a setup.py

**Comment by nbraud** [comment]
> Well, when I unzipped the archive, it didn't have a setup.py

Yes, ykman switched to using the Poetry build system.

**Comment by gbcox** [comment]
> > Well, when I unzipped the archive, it didn't have a setup.py
> 
> Yes, ykman switched to using the Poetry build system.

ok, I have no idea what that is... need to research.  Thanks!

**Comment by gbcox** [comment]
> ... I had to disable automated tests for the moment (test dependencies not packaged in Debian yet) but I'll try to improve the situation soonish.

Yeah, I got multiple test failures, so I commented it out for the time being: 

ImportError: Failed to import test module: tests.device
ImportError: Failed to import test module: tests.test_piv
ImportError: Failed to import test module: tests.test_scancodes
ImportError: Failed to import test module: tests.test_util
ImportError: Failed to import test module: ykman

I did notice when doing a test install that yubioath-manager stopped working.   The yubikey wasn't recognized.  Will yubioath need to be upgraded at the same time as manager?

**Comment by dainnilsson** [comment]
Yes, yubioath will also need a new version to be compatible with ykman 4.0. Unfortunately that one is a bit further out. We package it together with its dependencies (installers for Windows and MacOS, and as a Snap package) so I hadn't considered the impact here. I take it there's no way of doing something similar for Fedora and Debian, or of having multiple versions of a package available?

**Comment by dainnilsson** [comment]
Quick update on this: 4.0.0a3 has just been released. No major changes, but some fixes and tweaks based on our testing of the earlier build. It looks like we'll be targeting March 2nd for release of the final 4.0.0 version. Is that ok with you @nbraud for getting it into Bullseye?

**Comment by dainnilsson** [comment]
ykman 4.0.0 has now been released.
