### ISSUE TITLE
Warnings that cryptography.utils.int_from_bytes is deprecated

### ISSUE THREAD

**Issue by jay0lee** [Yubico/yubikey-manager#386]
- YubiKey Manager (ykman) version: latest
- How was it installed?: pip
- Operating system and version: Linux Debian Buster
- YubiKey model and version: 5c
- Bug description summary: cryptography library complains to stderr on every import of yubikey.piv and yubikey.opgp:that cryptography.utils.int_from_bytes is deprecated

Steps to reproduce
---
1) ```pip install yubikey-manager```
2) cryptography is installed as a requirement and this issue occurs with latest versions of it (since Dec 9th). Ensure it is up to date also in order to repro issue ```pip install --upgrade cryptography```

researched the issue with cryptography library and found: https://github.com/pyca/cryptography/pull/5609

Expected result
---
No deprecation warnings to stderr

Actual results and logs
---
```
$ python3 -c "import ykman.piv"
/home/pi/.local/lib/python3.7/site-packages/ykman/piv.py:39: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_to_bytes, int_from_bytes
```

Other info
---

I'm currently working around this issue with a bit of an ugly hack:
```
python3 -c "import sys; import cryptography.utils; sys.modules['cryptography.utils'].int_from_bytes = int.from_bytes; import ykman.piv"
```
this suppresses the warning

**Comment by jay0lee** [comment]
Submitted: https://github.com/Yubico/yubikey-manager/pull/385 to resolve this but I'll need some guidance as to how the project wants to handle Python 2.x. If the goal is to keep 2.x around then cryptography should probably be pinned to an older version.

**Comment by dainnilsson** [comment]
Thank you for your contribution. This has already been changed in the `next` branch, which is where active development of the coming version is being done. Support for Python 2 has been dropped (Python >= 3.6 will be required).

**Comment by Mexx77** [comment]
I am getting the error now with a recent Arch Linux.

```
ykman --version

/usr/lib/python3.9/site-packages/ykman/opgp.py:40: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_to_bytes, int_from_bytes
/usr/lib/python3.9/site-packages/ykman/piv.py:39: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_to_bytes, int_from_bytes
YubiKey Manager (ykman) version: 3.1.2
Libraries:
    libykpers 1.20.0
    libusb 1.0.24

python --version
Python 3.9.2
```

**Comment by dainnilsson** [comment]
That's expected since 3.1.2 came out before this was addressed. If you update to ykman 4.0.0 (released today) you should no longer get these warnings.
