### ISSUE TITLE
ykman config fido turn on any disabled fido application

### ISSUE THREAD

**Issue by git14** [Yubico/yubikey-manager#388]
- YubiKey Manager (ykman) version: 3.1.1
- How was it installed?: from yubico.com
- Operating system and version: Win10 20H2
- YubiKey model and version: yk 5 nano 5.2.4
- Bug description summary: Feature request - turn on all FIDO applications for ykman mode FIDO

Steps to reproduce
---

1. disable FIDO2 with ```ykman config usb -d fido2```
2. run ```ykman mode fido```

Expected result
---

fido2 would be turned on

Actual results and logs
---

Mode is already FIDO, nothing to do...

Other info
---

This is a nice to have, it would be easier to type ykman mode fido to turn on any disabled fido application if one of them is disabled.

For testing I frequently turn off and on FIDO applications.

**Comment by gbdlin** [comment]
Those 2 settings are separate things and IMO should be kept that way. For one, disabling FIDO2 but leaving U2F enabled (or the other way around) may be needed. Making the change you've proposed will make this configuration impossible or very hard to achieve (depending on the actual scope of this change).

**Comment by dainnilsson** [comment]
I don't think this would change any command, rather it would make the existing command work in a configuration where it currently does not. However, the `mode` subcommand is really intended for YubiKeys prior to 5, where the configuration is less fine-grained and several applications are toggled in bulk. Starting with YubiKey 5, the other `config ...` commands offer more control and should be used instead. I don't see much benefit to this change as you could just use `config usb -e u2f -e fido2` to achieve the same thing.
