### ISSUE TITLE
ykman config target all interfaces

### ISSUE THREAD

**Issue by git14** [Yubico/yubikey-manager#389]
- YubiKey Manager (ykman) version: 3.1.1
- How was it installed?: from yubic.com
- Operating system and version: Win10 20H2
- YubiKey model and version: yk5nfc 5.2.4
- Bug description summary: Feature request for ykman config command to target all interfaces

Steps to reproduce
---

Initial set up.

1. `ykman config usb -d fido2`
2. `ykman config nfc -d fido2`
3. `ykman config usb -e u2f`
4. `ykman config nfc -e u2f`

Do some testing, then switch to the other protocol.

1. `ykman config usb -e fido2`
2. `ykman config nfc -e fido2`
3. `ykman config usb -d u2f`
4. `ykman config nfc -d u2f`

Repeat to test just FIDO2 again.

Expected result
---

Would like to have a combined command like this:

1. `ykman config all -d fido2`
2. `ykman config all -e u2f`

Do work

1. `ykman config all -e fido2`
2. `ykman config all -d u2f`

Repeat 

Actual results and logs
---

Lots of commands typed to swap from only having FIDO2 and U2F enabled

Other info
---

Nice to have feature request to reduce the number of commands needed to swap from only having FIDO2 to only having U2F enabled.

**Comment by dainnilsson** [comment]
I don't think we'll be implementing this as switching configuration isn't typically done often enough to warrant multiple commands for doing so. However, you can combine multiple `-e` and `-d` flags in a single invocation, simplifying things somewhat:

`ykman config usb -e fido2 -d u2f`
`ykman config nfc -e fido2 -d u2f`

**Comment by git14** [comment]
Thanks for the example of the combined enable and disable. That helps.
