### ISSUE TITLE
Is it normal who fails to export enc key to check claim being curve25519?

### ISSUE THREAD

**Issue by tigernero79** [Yubico/yubikey-manager#391]
I used these commands from cli with latest yubikey manager 1.1.5 windows, 

```
ykman openpgp attest enc yubikey-5c-attestation-encryption.cert
ykman openpgp attest sig yubikey-5c-attestation-encryption.cert
ykman openpgp attest aut yubikey-5c-attestation-encryption.cert
```

and on the attestation keys for signature and authentication I can export,

them while the same command for encryption (enc) returns me 

`ykman openpgp attest enc yubikey-5c-attestation-encryption.cert`

```
C: \ Program Files \ Yubico \ YubiKey Manager> ykman openpgp attest enc yubikey-5c-attestation-encryption.cert
Enter PIN:
Touch your YubiKey ...
Usage: ykman openpgp attest [OPTIONS] KEY CERTIFICATE
Try 'ykman openpgp attest -h' for help.

Error: Attestation failed
```

I would like to know this why I use curves ed25519? i read that i can't generate attestation key in curve25519 but i can attest to a curve25519 key or am I wrong? in this case why the enc command is not performed?

**Comment by dainnilsson** [comment]
It looks to me like you may have generated the `sig` and `aut` keys but imported the `enc` key (as in, generated the key on the host PC, and imported it into the YubiKey). This is often standard practice to be able to make a backup of the encryption key since if it is lost all encrypted data is no longer decryptable, whereas the other keys can merely be re-issued. Attestation is only available for keys generated on the YubiKey.

**Comment by tigernero79** [comment]
Absolutely no.

All keys including that enc was generated directly on yubikey, command generate.

I only used elliptical curves ed25519 not rsa, but it should attest to it instead gives me an error

**Comment by dainnilsson** [comment]
We can do some additional troubleshooting, but it requires ykman CLI 4.0, which isn't yet released. If you can download the build from here: https://github.com/Yubico/yubikey-manager/actions/runs/589492191 and extract the ykman-main.exe from it, you can test the following command:

`.\ykman-main.exe apdu -a openpgp CA00DE`

The output should look similar to this:
```
SELECT AID: D2 76 00 01 24 01
RECV (SW=9000)

SEND: 00 CA 00 DE
RECV (SW=9000):
01 00 02 00 03 00 81 02                           ········
```

If you can provide the last line (`01 00 02 00 03 00 81 02` from my example) then that should help us narrow down what's going on.

**Comment by tigernero79** [comment]
Here is the data

```
Microsoft Windows [Versione 10.0.19042.804]
(c) 2020 Microsoft Corporation. Tutti i diritti sono riservati.

C:\WINDOWS\system32>cd..

C:\Windows>cd ..

C:\>ykman-main.exe apdu -a openpgp CA00DE
SELECT AID: D2 76 00 01 24 01
RECV (SW=9000)

SEND: 00 CA 00 DE
RECV (SW=9000):
01 01 02 02 03 01 81 02                           ········

C:\>
```

**Comment by dainnilsson** [comment]
Thanks! The command sends the GET_DATA instruction (0xCA) with the argument 0x00DE, which is the ID of the "Key Information" data object. The full OpenPGP card specification is available here: ftp://ftp.gnupg.org/specs/OpenPGP-smart-card-application-3.4.pdf

The meaning of the output is as follows:
```
KEY				STATE
01 (sig)			01 (generated)
02 (dec, called enc in ykman)	02 (imported)
03 (aut)			01 (generated)
81 (att)			02 (imported)
```
Attestation is failing for the encryption key because it was imported into the YubiKey. When the `generate` command in gpg is run, it will by default ask you if you want to make a backup of the encryption key. If you answer yes to that then it generates the key in software, and imports it into the YubiKey. Other uses of `generate` may do the same.

**Comment by tigernero79** [comment]
ah ok, I said yes for backup but I meant it to make a backup of the private one (albeit in partial "STUB" format) after having generated it by yubico itself. instead it is inverse. ok.
So this is all normal right?

Will ykman 4.0 release be arm compatible? or debian based arm64? because I have many raspberry and I would be pleasantly happy if yubico manager and yubico authenticator run on debian buster or next bullseye with armhf or arm64 architecture debian base

**Comment by dainnilsson** [comment]
Yeah, sounds like all is normal! About ARM, it's not one of the platforms we officially support, but I believe ykman 4.0 (at least in CLI) form should be able to run there. You could try installing the latest alpha using `pip install --pre yubikey-manager`. The build may require some additional tools to be installed for some of the dependencies, and pcscd will need to be installed as well, but I  see no immediate reason why it wouldn't work. I'd start with trying `$ sudo apt install swig pcscd libpcsclite-dev` and then seeing if the pip install works.

**Comment by tigernero79** [comment]
ok I'll try and let you know.

How can I verify that the attestation key is that of yubico and has not been replaced? I read that att is imported I think it is right since its ca was imported from yubico, but to verify that it is its there is some command?

**Comment by tigernero79** [comment]
@dainnilsson 
i reset yubico openpgp after revoking key, enabled kdf and unsaved backup and this is the situation :-)

```
C:\>ykman-main.exe apdu -a openpgp CA00DE
SELECT AID: D2 76 00 01 24 01
RECV (SW=9000)

SEND: 00 CA 00 DE
RECV (SW=9000):
01 00 02 00 03 00 81 02                           ········

C:\>ykman-main.exe apdu -a openpgp CA00DE
SELECT AID: D2 76 00 01 24 01
RECV (SW=9000)

SEND: 00 CA 00 DE
RECV (SW=9000):
01 01 02 01 03 01 81 02                           ········

C:\>
```

I believe that if I export the keys again and try to certify them with ca and yubico attestation key with openssl command if from ok it means that the ca is the original one yubico right?

**Comment by dainnilsson** [comment]
That sounds correct! The attestation key should indeed be `imported`, as that is what Yubico does at manufacturing. The CA used for OpenPGP is available here: https://developers.yubico.com/PGP/Attestation.html
To verify a single key, you need to verify the full chain of CA certificate -> Attestation key certificate -> Enc/Sig/Auth key certificate. OpenSSL should be able to do this, thought I don't recall the exact command to use.

**Comment by nevun** [comment]
> OpenSSL should be able to do this, thought I don't recall the exact command to use.

I had some notes laying around for that:

```
$ curl -O https://developers.yubico.com/PGP/opgp-attestation-ca.pem
$ ykman openpgp attest sig ./attest
$ ykman openpgp export-certificate att att.pem
$ cat opgp-attestation-ca.pem att > certs.pem
$ openssl verify -CAfile certs.pem ./attest
./attest: OK
```

**Comment by tigernero79** [comment]
@dainnilsson @nevun yes correct all

I use

```
❯ ykman openpgp attest sig yubikey-5c-attestation-signing.cert
Enter PIN:

❯ ykman openpgp attest enc yubikey-5c-attestation-encryption.cert
Enter PIN:

❯ ykman openpgp attest aut yubikey-5c-attestation-authentication.cert
Enter PIN:

❯ ls yubikey-5c-attestation*
yubikey-5c-attestation-authentication.cert yubikey-5c-attestation-encryption.cert     yubikey-5c-attestation-signing.cert
```

try

Securely download a copy of the Yubico OPGP CA: 

https://developers.yubico.com/PGP/opgp-attestation-ca.pem

Export your Yubikey's OpenPGP attestation certificate with: 

ykman openpgp export-certificate att yubikey-5c-attestation.cert

Append your Yubikey's attestation certificate with the Yubico OPGP CA: 

nano opgp-attestation-ca.pem yubikey-5c-attestation.cert > yubikey-attestation-ca-combined.cert

Run the following series of commands to verify each of the generated attestation certificates for your signing, encryption, and authentication keys.

```
❯ openssl verify -CAfile ./yubikey-attestation-ca-combined.cert ./yubikey-5c-attestation-signing.cert
./yubikey-5c-attestation-signing.cert: OK

❯ openssl verify -CAfile ./yubikey-attestation-ca-combined.cert ./yubikey-5c-attestation-encryption.cert
./yubikey-5c-attestation-encryption.cert: OK

❯ openssl verify -CAfile ./yubikey-attestation-ca-combined.cert ./yubikey-5c-attestation-authentication.cert
./yubikey-5c-attestation-authentication.cert: OK
```
