### ISSUE TITLE
Can't set the touch request option

### ISSUE THREAD

**Issue by xorcare** [Yubico/yubikey-manager#395]
- YubiKey Manager (ykman) version: 3.1.2
- How was it installed?: brew
- Operating system and version: macOS 10.15.7 (19H524)
- YubiKey model and version: YubiKey 5C Nano
- Bug description summary:

I want to make the touch mandatory, but I get a pincode error in the response.

Steps to reproduce
---

```
ykman openpgp set-touch SIG ON
```

On request, enter the correct PIN code of the administrator.

Expected result
---

Touch must be enabled for signature.

Actual results and logs
---
```
xor at ant in ~
> ykman openpgp info            
OpenPGP version: 3.4
Application version: 5.2.7

PIN tries remaining: 10
Reset code tries remaining: 0
Admin PIN tries remaining: 10

Touch policies
Signature key           Off
Encryption key          Off
Authentication key      Off
Attestation key         On
xor at ant in ~
> ykman openpgp set-touch SIG ON
Enter admin PIN: 
Set touch policy of signature key to on? [y/N]: y
Error: Invalid PIN, 9 tries remaining.
```

Other info
---
```
> gpg --card-status                               
Reader ...........: Yubico YubiKey OTP FIDO CCID
Application ID ...: D2760001240103040006147003450000
Application type .: OpenPGP
Version ..........: 3.4
Manufacturer .....: Yubico
Serial number ....:
Name of cardholder: Vasiliy Vasilyuk
Language prefs ...: ru
Salutation .......: 
URL of public key : [not set]
Login data .......: [not set]
Signature PIN ....: forced
Key attributes ...: ed25519 nistp521 ed25519
Max. PIN lengths .: 127 127 127
PIN retry counter : 10 0 9
Signature counter : 10
KDF setting ......: on
```

**P. S.** _There maybe a problem with the **KDF setting**?_

**Comment by dainnilsson** [comment]
I think you may be right that this is about the KDF. There's a know issue in the current version that prevents KDF from working correctly for some specific configurations. This should be fixed already in the upcoming ykman 4.0 version, if you want to try it out you can download one of our latest builds from here https://github.com/Yubico/yubikey-manager/actions/runs/602433667 and see if that resolves the issue. You can download the `ykman-builds-macos` archive, extract it, and run the extracted `ykman-main` executable: `./ykman-main openpgp keys set-touch SIG ON`.

**Comment by xorcare** [comment]
@dainnilsson Thank you there is no problem in the latest build.

**Comment by dainnilsson** [comment]
Great! Thanks for reporting back!
