### ISSUE TITLE
ykman list does not list connected yubikey

### ISSUE THREAD

**Issue by scottwn** [Yubico/yubikey-manager#397]
- YubiKey Manager (ykman) version: 4.0.0
- How was it installed?: `pip install yubikey-manager`
- Operating system and version: Red Hat Enterprise Linux 8.3 (Ootpa)
- YubiKey model and version: YubiKey FIPS (I think, based on https://www.yubico.com/products/identifying-your-yubikey/)
- Bug description summary: `ykman list` does not list attached yubikey

Steps to reproduce
---
`lsusb` shows the connected YubiKey, and the YubiKey works as designed to log in to VPN, but `ykman list` produces no output.

Expected result
---

I expect to see the yubikey listed

Actual results and logs
---

```
~ [1] $ lsusb                                                                                                                                                                                   18:07:25
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 006: ID 06cb:00bd Synaptics, Inc. 
Bus 001 Device 004: ID 13d3:56bc IMC Networks 
Bus 001 Device 007: ID 046d:c33b Logitech, Inc. 
Bus 001 Device 010: ID 28bd:0075  
Bus 001 Device 008: ID 046d:c52b Logitech, Inc. Unifying Receiver
Bus 001 Device 005: ID 05e3:0610 Genesys Logic, Inc. 4-port hub
Bus 001 Device 003: ID 05e3:0610 Genesys Logic, Inc. 4-port hub
Bus 001 Device 009: ID 8087:0029 Intel Corp. 
Bus 001 Device 011: ID 1050:0401 Yubico.com Yubikey 4 OTP
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
~ $ ykman list                                                                                                                                                                                  18:07:47
~ $
```

**Comment by dainnilsson** [comment]
This looks like a device permission issue to me, see this page for more info: https://github.com/Yubico/yubikey-manager/blob/main/doc/Device_Permissions.adoc

Based on the lsusb output it looks like the YubiKey is in "OTP only" mode, meaning the only USB interface available for ykman to connect to is the so called "OTP interface" (aka the keyboard interface). Adding the udev rule from the linked page (`69-yubikey.rules`) to `/etc/udev/rules.d/` to allow access will probably fix the issue. You'll probably have to run `udevadm trigger` to reload the rules before they'll take effect.

**Comment by scottwn** [comment]
that works, thanks!
