### ISSUE TITLE
Wish I didn't have to be a poet

### ISSUE THREAD

**Issue by edrozenberg** [Yubico/yubikey-manager#401]
Cloned and used `poetry build` to build a `whl`. Now it's not clear how to actually use the tool because all the instructions talk about using poetry to run it. I don't plan to use poetry - I'd like to run it normally as a python program `python3 something.py` to get a code from my key. Nothing fancy.

Also I'm avoiding the bloated QT "cross platform" GUI - so if I can use this python code in a normal way I'd enjoy that. Thanks.

(and I haven't come across any other project that uses poetry luckily, I build many python packages the normal way with setup.py).

**Comment by dainnilsson** [comment]
Poetry is only used to build and develop the project, it's not needed to install or run. The standard way to install by using `pip install yubikey-manager` should work just fine, and will get you the latest release from pypi.org. These are the instructions we provide in the README of this project.

If you do wish to build from the repository, poetry is required. Once you've built the package using Poetry (wheel or source tarball), you can install that using `pip install <file>`.
