### ISSUE TITLE
Yubikey-Manager sends non-standard-conforming APDU for selecting data

### ISSUE THREAD

**Issue by ya-isakov** [Yubico/yubikey-manager#403]
- YubiKey Manager (ykman) version: 4.0.0
- How was it installed?: Gentoo ebuild
- Operating system and version: Gentoo
- YubiKey model and version: YubiKey 5 NFC, 5.2.4
- Bug description summary:

I tried to find, why MR https://github.com/OpenSC/OpenSC/pull/2103 is not working with Yubikey, not showing any certificates, while I can extract certificate through ykman. I found that Yubikey-Manager uses uses APDU, which is not conforming to https://gnupg.org/ftp/specs/OpenPGP-smart-card-application-3.4.pdf, 7.2.5 - it adds additional length field.

From the standard:
```
CLA INS P1 P2 Lc                  Le
00  A5  00 04 06 60 04 5C 02 7F21 00
```
But ykman sends
```
CLA INS P1 P2 Lc                     Le
00  A5  00 04 07 06 60 04 5C 02 7F21 00
```
It seems that sending standard-conforming APDU doesn't work.

**Comment by dainnilsson** [comment]
Thanks for reporting! We've confirmed that the YubiKey here does not follow the specification correctly here. This will need to be changed in the YubiKey firmware before we can make any changes to this project. I've reported the issue to our firmware team.
