### ISSUE TITLE
ModuleNotFoundError: No module named 'smartcard' (arm64, pip installation) + Fix!

### ISSUE THREAD

**Issue by qadmus** [Yubico/yubikey-manager#406]
- YubiKey Manager (ykman) version: `4.0.2`
- How was it installed?: `pip`
- Operating system and version: `Linux 4.4.250 aarch64 / arm64, Ubuntu 20.04.2 LTS focal`

- YubiKey model and version: `5C`
- Bug description summary:

```> ykman oath code Namehere                                                       
Traceback (most recent call last):                                            
  File "/home/user/.local/bin/ykman", line 5, in <module>
    from ykman.cli.__main__ import main       
  File "/home/user/.local/lib/python3.8/site-packages/ykman/__init__.py", line 29, in <module>
    from .device import (  # noqa
  File "/home/user/.local/lib/python3.8/site-packages/ykman/device.py", line 54, in <module>
    from .pcsc import list_devices as _list_ccid_devices           
  File "/home/user/.local/lib/python3.8/site-packages/ykman/pcsc/__init__.py", line 33, in <module>
    from smartcard import System
ModuleNotFoundError: No module named 'smartcard'
```

**Fix:** `sudo apt install python3-pyscard`

I don't know enough about packages and dependencies. This is a bare-bones Ubuntu with almost no default packages. Maybe `python3-pyscard` needs to be added as a `yubikey-manager` dependency?

**Comment by dainnilsson** [comment]
Installation from `pip` should pull in all required python dependencies, including pyscard. You probably no longer have the output of running the `pip install` command, but do you recall if there were any errors during installation? Some additional packages are likely required on a fresh Ubuntu for the pyscard build to succceed. Of the top of my head I believe these are `swig` and `libpcsclite-dev` (both available via apt).

**Comment by qadmus** [comment]
Ah! I did have a broken dependency when using apt to install the PPA release, for something like `python3-yubikey-manager, 3.1.1-1 expected but 3.1.2-focal to be installed`

Thanks!

**Comment by dainnilsson** [comment]
Ok, sounds like you may have had a broken install of pyscard then. Glad you got it working!
