### ISSUE TITLE
ykman issue with mutiple security keys plugged in

### ISSUE THREAD

**Issue by notfoss** [Yubico/yubikey-manager#409]
- YubiKey Manager (ykman) version: 4.0.0a1
- How was it installed?: apt
- Operating system and version: Debian Sid
- YubiKey model and version: Yubikey 5 NFC
- Bug description summary: ykman issue with mutiple security keys plugged in

Issue details
---

I have 2 security keys plugged into my machine. One is a Yubikey 5 NFC and the other is a work issued, non-Yubikey model.

With both of the keys plugged in, every `ykman` command was failing with: `Error: 20518 is not a valid PID`. Even `ykman list --serials` failed to run, giving the same message.

I then removed the non-Yubikey security key and retrieved the serial number for my Yubikey.

After that, `ykman` ran fine, if used with the --device option. For e.g. `ykman --device <serial> oath accounts code`.

Expected result
---

`ykman` should not bail out if unknown security keys are detected.

Other info
---

`yubioath-desktop` 5.0.4 worked fine under the same conditions.

Also, I believe that this problem only started happening with 4.x.x version of `ykman`.

**Comment by dainnilsson** [comment]
Can you try this with the latest version (4.0.2) and see if the problem still exists there?

**Comment by notfoss** [comment]
Yes, it's working fine with 4.0.2! Thanks!

**Comment by dainnilsson** [comment]
Great! Thanks for confirming!
