### ISSUE TITLE
Touch eject disabled when attempting to increase autoeject timeout

### ISSUE THREAD

**Issue by ificator** [Yubico/yubikey-manager#416]
- YubiKey Manager (ykman) version: 4.02 (via yubikey manager qt 1.2.2)
- How was it installed: Installer downloaded from https://developers.yubico.com/yubikey-manager-qt/Releases/
- Operating system and version: Windows 10 21H1
- YubiKey model and version: YubiKey FIPS 4.4.4
- Bug description summary: Cannot enable touch eject

Steps to reproduce
---
I wanted to increase the auto-eject timeout so I ran:
`ykman config mode -f CCID --autoeject-timeout 3600`

Expected result
---
The key would auto-eject after 1 hour, and I would be able to manually eject it with touch

Actual results and logs
---
Now it doesn't timeout at all, and touch eject is not working

Other info
---
I tried just `--touch-eject` but that didn't do anything as far as I can tell. Looking at the source code I don't see how it could:
```
mgmt.set_mode(mode, chalresp_timeout, autoeject)
```
if `--autoeject-timeout` is not provided the value of `autoeject` is 0 whether `--touch-eject` is provided or not, and I don't see anyway the device flag for eject (`0x80`) can be passed via `set_mode`. Is there some other command I should be doing to keep touch eject working but with a timeout of 1 hour?

**Comment by dainnilsson** [comment]
Thanks for the report! I'm looking into this. Initial findings show that things definitely aren't working as they should here...

**Comment by dainnilsson** [comment]
This should now be fixed for the next release of ykman, thanks again!

**Comment by ificator** [comment]
Thanks for the fast turn around!
