### ISSUE TITLE
Unable to disable touch on signature

### ISSUE THREAD

**Issue by nicolamarella** [Yubico/yubikey-manager#424]
- YubiKey Manager (ykman) version: 4.0.3
- How was it installed?: pacman
- Operating system and version: arch - Python: 3.9.5
- YubiKey model and version: YubiKey 5C 5.2.6
- Bug description summary:

After setting the touch policy to fixed for signatures, I cannot revert it to off. 

Steps to reproduce
---

1. Enable touch upon signature with ` ykman openpgp keys set-touch SIG FIXED` (wanted to test the behaviour, since the docs is not clear)
2. Revert that with ` ykman openpgp keys set-touch SIG OFF` 

Expected result
---

Policy is updated corrected

Actual results and logs
---

```
yubikit.core.smartcard.ApduError: APDU error: SW=0x6600
Error: Failed to set touch policy
```

Other info
---
Here is debug info
```
2021-06-25T10:09:55+0200 DEBUG [ykman.cli.openpgp.set_touch:239] Failed to set touch policy
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ykman/cli/openpgp.py", line 235, in set_touch
    controller.set_touch(key, policy)
  File "/usr/lib/python3.9/site-packages/ykman/openpgp.py", line 436, in set_touch
    self._put_data(key_slot.uif, struct.pack(">BB", mode, TOUCH_METHOD_BUTTON))
  File "/usr/lib/python3.9/site-packages/ykman/openpgp.py", line 335, in _put_data
    self._app.send_apdu(0, INS.PUT_DATA, do >> 8, do & 0xFF, data)
  File "/usr/lib/python3.9/site-packages/yubikit/core/smartcard.py", line 177, in send_apdu
    raise ApduError(response, sw)
yubikit.core.smartcard.ApduError: APDU error: SW=0x6600
Error: Failed to set touch policy.
```

**Comment by dainnilsson** [comment]
The touch policies for OpenPGP (all of which are described by running `ykman openpgp keys set-touch --help`) that contain the word `fixed` cannot be disabled without performing a factory reset of the OpenPGP application (`ykman openpgp reset`, which will delete all keys and reset PINs to default values). The `on` policy is exactly the same as the `fixed` policy with the exception that it can be disabled.

**Comment by nicolamarella** [comment]
Oh, thanks @dainnilsson, guess that solves the issue :) my bad then!
