### ISSUE TITLE
ykman.cli.oath.py Need to provide details on [SECRET]

### ISSUE THREAD

**Issue by wagner-robert** [Yubico/yubikey-manager#428]
- YubiKey Manager (ykman) version: latest
- How was it installed?:
- Operating system and version: Windows
- YubiKey model and version:
- Bug description summary: When running 'ykman oath accounts add -h' the variable [SECRET] is mentioned under the usage, but no details are provided.

Steps to reproduce
---

run 'ykman oath accounts add -h'

Expected result
---

The variable [SECRET] needs to be explained ... Minimum length, maximum length, encoding.

Actual results and logs
---

Difficult to figure out min, max and encoding without looking at the code.

**Comment by dainnilsson** [comment]
Thanks! I've now included the SECRET and NAME arguments in the `--help` output for the command.
