### ISSUE TITLE
yubikey-manager/yubikit/oath.py  problem with def _hmac_shorten_key()

### ISSUE THREAD

**Issue by wagner-robert** [Yubico/yubikey-manager#432]
- YubiKey Manager (ykman) version: latest
- How was it installed?:  Git pull
- Operating system and version: Windows 10 latest Python
- YubiKey model and version: v4
- Bug description summary:

As used in the yubikey-manager, this function gets passed HASH_ALGORITH.SHA1 to the algo variable.  hashlib.new only understands getting passed SHA1.  To get it to work, I had to split the algo variable and use the second part.  If not, it will error out as algo.name does not exist.

def _hmac_shorten_key(key, algo):
    #Had to add this line as error without
    f = algo.split('.')[1]
    #Changed this from algo.name to f
    h = hashlib.new(f)

    if len(key) > h.block_size:
        h.update(key)
        key = h.digest()
    return key

Steps to reproduce
---

Just using the code normally.   Either yubikey-manager is messed up and is abusing the algo variable or this piece is messed up.

Expected result
---

The code should understand it is getting passed algo= HASH_ALGORITH.SHA1  and handle it correctly - only pass SHA1 to the hashlib.new() function.

Actual results and logs
---

[What actually happened?]

Other info
---

[Anything else you would like to add?]

**Comment by dainnilsson** [comment]
Please note that any function starting with an underscore (`_`) is considered private and not part of the public API. As such it is not intended to be used publicly and may change between versions of the package without prior notice. We strongly urge you do not call these functions directly.

The `algo` input parameter should be of type `HASH_ALGORITHM`, as defined in `yubikit.oath`. As such, it will have a `name` property, and the code will run properly.

**Comment by wagner-robert** [comment]
I don't call it.  The yubikit oath library calls it.  The gets called when calling put_credentials.  I fill in the variable algorithm exactly the same way you call it with ykman.cli

from the command line algorithm = "SHA1"

            algorithm_v = str(algorithm)

           cred_data = CredentialData(
                        oathname_v,
                        oathtype_v,
                        algorithm_v,
                        oathsecret_v,
                        digits_v,
                        totpperiod_v,
                        counter_v,
                        issuer_v,
                    )

            o = OathSession(connection)
            o.put_credential(cred_data, touch)

RW
________________________________

**Comment by wagner-robert** [comment]
@click.option(
    "-a",
    "--algorithm",
    type=EnumChoice(HASH_ALGORITHM),
    default=HASH_ALGORITHM.SHA1.name,
    show_default=True,
    help="Algorithm to use for code generation.",
)

def build(ctx,
    name,
    issuer,
    period,
    oath_type,
    digits,
    touch,
    algorithm,
    counter,

    ):

....Some additional information

RW
________________________________

**Comment by wagner-robert** [comment]
Is this causing me grief  ----?
algorithm_v = str(algorithm)

Should I send the algorithm straight through to cred_data?
FYI - I need this variable set to store in a database....

RW
________________________________

**Comment by dainnilsson** [comment]
The command line takes all input as strings, since that is what you can provide when typing into a terminal, but each of those arguments gets parsed and transformed to other types before calling the library functions. There is no need to go via a string when you are calling the library functions directly. Will you only be using TOTP and SHA1? If so, the absolutely easiest thing is to just use those constants directly:

```
CredentialData(
    oath_type=OATH_TYPE.TOTP,
    hash_algorithm=HASH_ALGORITHM.SHA1,
    ...
)
```
