### ISSUE TITLE
 yubikey-manager/yubikit/oath.py  error in def put_credential()

### ISSUE THREAD

**Issue by wagner-robert** [Yubico/yubikey-manager#433]
- YubiKey Manager (ykman) version: latest
- How was it installed?: git pull
- Operating system and version: windows 10, latest python
- YubiKey model and version: v5
- Bug description summary:

The function below expects d.oath_type and d.hash_algorithm to be numerical values.  They aren't.
by the time I arrive at this code
d.hash_algorithm = HASH_ALGORITHM.SHA1
d.oath_type = OATH_TYPE.TOTP

   def put_credential(
        self, credential_data: CredentialData, touch_required: bool = False
    ) -> Credential:
        d = credential_data
        cred_id = d.get_id()
        secret = _hmac_shorten_key(d.secret, d.hash_algorithm)
        secret = secret.ljust(HMAC_MINIMUM_KEY_SIZE, b"\0")
        data = Tlv(TAG_NAME, cred_id) + Tlv(
            TAG_KEY,
            struct.pack("<BB", **d.oath_type | d.hash_algorithm,** d.digits) + secret,
        )

Steps to reproduce
---

[Please explain what you did when the bug appeared, and if and how you have been
able to reproduce it.]

Expected result
---

[What did you expect to happen when you did the above?]

Actual results and logs
---

[What actually happened?]

Other info
---
I was able to get around this error by changing this to:

        #origninal line below
        #    struct.pack("<BB", d.oath_type | d.hash_algorithm, d.digits) + secret,
            struct.pack("<BB", int(OATH_TYPE[d.oath_type.split('.')[1]]) | int(HASH_ALGORITHM[d.hash_algorithm.split('.')[1]]), d.digits) + secret,   

While the key accepted the input, I don't know if the code actually works.  This code may not function correctly.

**Comment by dainnilsson** [comment]
The `HASH_ALGORITHM` and `OATH_TYPE` types are of type `IntEnum`, which are a subclass of int.
```
In [18]: cd=CredentialData("name", OATH_TYPE.TOTP, HASH_ALGORITHM.SHA1, b"secret")

In [19]: cd.oath_type
Out[19]: <OATH_TYPE.TOTP: 32>

In [20]: cd.hash_algorithm
Out[20]: <HASH_ALGORITHM.SHA1: 1>

In [21]: cd.oath_type | cd.hash_algorithm
Out[21]: 33
```

Maybe you're passing in incorrect values when creating the `CredentialData`?

**Comment by wagner-robert** [comment]
I pull straight from the command line and use SHA1 and TOTP when filling in

            tokenserial_v = str(info.serial)
            usetemplate_v = ""
            oathtype_v = str(oath_type)
            oathname_v = str(name)
            digits_v = int(digits)
            algorithm_v = str(algorithm)
            counter_v = int(counter)
            issuer_v = issuer
            totpperiod_v = int(period)
            touch_v = int(touch)
            upassword_v = ""
            oathsecret_v = base64.b32encode(secrets.token_bytes(32))
            oathlockcode_v = ""

            cred_data = CredentialData(
                        oathname_v,
                        oathtype_v,
                        algorithm_v,
                        oathsecret_v,
                        digits_v,
                        totpperiod_v,
                        counter_v,
                        issuer_v,
                    )

            o = OathSession(connection)
            o.put_credential(cred_data, touch)


These some from the command line options as SHA1 and TOTP or HOTP
After calling the put_credential, these get transformed into HASH_ALGORITHM.SHA1 and OATH_TYPE.TOTP when stored in d.



RW
________________________________

**Comment by dainnilsson** [comment]
The values you are giving to CredentialData are of the wrong type, which is what is causing these problems.
If you look at the definition of the class (https://github.com/Yubico/yubikey-manager/blob/main/yubikit/oath.py#L96) you can see the types of the members:
```
class CredentialData:
    name: str
    oath_type: OATH_TYPE
    hash_algorithm: HASH_ALGORITHM
    secret: bytes
    digits: int = DEFAULT_DIGITS
    period: int = DEFAULT_PERIOD
    counter: int = DEFAULT_IMF
    issuer: Optional[str] = None
```

Looking at your code, it should probably be something more like:
```
            cred_data = CredentialData(
                        name,
                        OATH_TYPE.TOTP,
                        HASH_ALGORITHM.SHA1,
                        secrets.token_bytes(32),
                        6,  
                        30,
                        0,
                        issuer,
            )

            o = OathSession(connection)
            o.put_credential(cred_data, touch)
```
