### ISSUE TITLE
https://github.com/Yubico/yubikey-manager/blob/main/doc/Library_Usage.adoc - Setting Config Options

### ISSUE THREAD

**Issue by wagner-robert** [Yubico/yubikey-manager#435]
- YubiKey Manager (ykman) version: latest
- How was it installed?:  Git
- Operating system and version: Win 10
- YubiKey model and version: v5 NFC
- Bug description summary:

Need details on writing the config to the device.  In particular, how it the SELF variable set when calling:
            try:
                ManagementSession.write_device_config(info ---??? my attempt at setting self - solved the version issue,
                    DeviceConfig({TRANSPORT.NFC: nfc_enabled}, None, None, None),
                    False,  # No need to reboot for NFC.
                    lock_code,
                    )

This appears buried in the ctx.  When I debug ykman config usb -e ...... I see the variable passed to write_device_config:
From line 464 of ykman/cli/config.py
------------------------config use
config	DeviceConfig: DeviceConfig(enabled_capabilities={<TRANSPORT.NFC: 'nfc'>: <CAPABILITY.FIDO2|OATH|PIV|OPENPGP|U2F|OTP: 571>}, auto_eject_timeout=None, challenge_response_timeout=None, device_flags=None)	
cur_lock_code	NoneType: None	
new_lock_code	NoneType: None	
reboot	bool: False	
self	ManagementSession: <yubikit.management.ManagementSession object at 0x000002B1AEC46D00>	
	backend	_ManagementSmartCardBackend: <yubikit.management._ManagementSmartCardBackend object at 0x000002B1AEC889D0>	
	version	Version: Version(major=5, minor=1, patch=2)	

Steps to reproduce
---

Just try and call management.write_device_config from a new python module

Expected result
---

[What did you expect to happen when you did the above?]

Actual results and logs
---

[What actually happened?]

Other info
---

[Anything else you would like to add?]

**Comment by wagner-robert** [comment]
I think I figured this out looking at: https://github.com/Yubico/yubikey-manager-qt/blob/master/ykman-gui/py/yubikey.py
Some documentation would still be helpful
      try:
                session = ManagementSession(connection)
                session.write_device_config(
                    DeviceConfig({TRANSPORT.NFC: nfc_enabled}, None, None, None),
                    False,  # No need to reboot for NFC.
                    lock_code,  #Lock code = when set
                    None,
                    )

**Comment by wagner-robert** [comment]
I would also be helpful to understand when to use which Session (SmartCard, OTP, other....)  I am a little confused why Smartcard works with v4, v5 FIPS, but OTPSession has to be used with v5 NFC. ... Provisioning Config + OTP settings:
`    for device, info in list_all_devices():
        if info.version == (5, 1, 2):  # The info object provides details about the YubiKey
            connection, _, _ = connect_to_device(serial=info.serial, connection_types=[OtpConnection])    #v5 NFC
        else:    
            connection, _, _ = connect_to_device(serial=info.serial, connection_types=[SmartCardConnection])  #V4,5 FIPS
        print("I found one: "+str(info.serial)+" Device: "+str(device))
`

**Comment by dainnilsson** [comment]
The `self` variable is a standard part of classes in Python. The vairable is set automatically when invoking a method on an instance. More information is available here: https://docs.python.org/3/tutorial/classes.html

This page explains a lot of the underlying concepts: https://developers.yubico.com/Mobile/Concepts.html
It explain the different types of Connections, and what Connection can be used to access a specific Application (Session). In short, each Application (OTP, PIV, etc.) is designed for a specific type of Connection, though some may support multiple Connections (like Management, which can use any Connection type). The Connection type used also depends on the Transport. The NFC transport only provides a SmartCardConnection, but still allows access to all Applications.
