### ISSUE TITLE
New Access Code is echoed to terminal

### ISSUE THREAD

**Issue by yubirob** [Yubico/yubikey-manager#437]
- YubiKey Manager (ykman) version: 4.0.5
- How was it installed?: poentry / GIT pull of tagged release
- Operating system and version: OSX 11.3
- YubiKey model and version: YK4 FIPS
- Bug description summary: The -A - argument opens a new line to enter new Access Code but this code is echo'd to the screen. 

Steps to reproduce
---
1. Install poentry and use to install 4.0.5 code
2. With FIPS key plugged in type poetry run ykman otp settings -A - 1
3. System drops down a single line and displays Enter new access code:
4. If you type a new access code it is displayed

Expected result
---
When a new access is typed to the screen it is not displayed
You should be required to type in twice to confirm the correct access code was entered

Actual results and logs
---

Enter new access code: 123456

Other info
---

**Comment by yubirob** [comment]
https://github.com/Yubico/yubikey-manager/commit/26563423fc9bf54c16d77f93e0a4c7af647a33af#r53979099

I modified my local copy with hide_input=True, confirmation_prompt=True, which seem to be valid kwargs for click. The new code is not displayed and I'm asked to reconfirm.

new_access_code = click_prompt("Enter new access code", hide_input=True, confirmation_prompt=True, show_default=False)

**Comment by emlun** [comment]
On its own this seems simple enough and is easy to change, but there are a lot of other secrets even in just the `otp` command group that work the same way (YubiOtp secret key, static password, chalresp secret, HOTP secret) so we'd need to decide whether we should change those too. Let's wait for @dainnilsson to return from vacation before we make any changes here.

**Comment by yubirob** [comment]
I agree. I had a specific issue I was trying to resolve. If this can go higher up the food chain to have wider implementation that seems like the right path.

**Comment by dainnilsson** [comment]
We've gone over the different inputs for the new release (4.0.7) and have changed the behavior of those that were inconsistent. We now mask input for anything we consider to be a PIN or password.
