### ISSUE TITLE
GUI crashes at start

### ISSUE THREAD

**Issue by tiresiasfromthebai** [Yubico/yubikey-manager#440]
- YubiKey Manager (ykman) version: 4.0.5
- How was it installed?: ubuntu ppa
- Operating system and version: linux mint 20.1 kernel 5.8.0-59-generic
- YubiKey model and version: Yubikey 5 NFC
- Bug description summary: GUI crashes at start 

Steps to reproduce
- Install the manager from ppa
- click on yubikey manager in the start menu

Expected result
- the GUI opens

Actual results and logs
- a window appears and disappears immediately

**Comment by fdennis** [comment]
Hi,

ykman is a command line interface, not a GUI. If you install with
`sudo apt install yubikey-manager`
you should be able to run it with
`ykman`
in a terminal.

If you are looking for the GUI, you can find it [here](https://github.com/Yubico/yubikey-manager-qt).
