### ISSUE TITLE
CCID\OATH Only - No YubiKey found with the given interface(s)

### ISSUE THREAD

**Issue by angry-bender** [Yubico/yubikey-manager#450]
- YubiKey Manager (ykman) version: YubiKey Manager (ykman) version: 4.0.2
- How was it installed?: Msi from website
- Operating system and version: Windows 10 20H2
- YubiKey model and version:
YubiKey 5 NFC (5.4.3) [OTP+FIDO+CCID] : 
YubiKey NEO (3.4.9) [OTP+CCID] : 
- Bug description summary:
OATH/CCID Not recognised

Steps to reproduce
---
- Yubico Authenticator version: 5.0.3, 5.0.5b, window store version, ykman-1.2.2
- Operating system and version: Windows 10 20H2
- YubiKey model and version: 
    - YubiKey 5 NFC (5.4.3) [OTP+FIDO+CCID]
     -YubiKey NEO (3.4.9) [OTP+CCID]
- Bug description summary: Windows 10 no longer recognises my the CCID/OATH interface in windows. This occurs in both the authenticator app and the ykman application. 

Steps to reproduce
---

Plug in Yubikey, and get 2FA OATH codes. 

GUI Application shows

![image](https://user-images.githubusercontent.com/18164137/130974910-a38c8565-b718-41db-b1b2-f781861c116f.png)
However, if I change to OTP, the device then shows
![image](https://user-images.githubusercontent.com/18164137/130975001-1a7af16d-edc0-452d-800a-81474aae8150.png)

running from the command line shows
```
 C:\..\YubiKey Manager  .\ykman.exe list
WARNING: PCSC not available. Smart card protocols will not function.
YubiKey 5 NFC (5.4.3) [OTP+FIDO+CCID] 
 C:\..\YubiKey Manager  .\ykman.exe info
WARNING: PCSC not available. Smart card protocols will not function.
Device type: YubiKey 5 NFC
Serial number: 
Firmware version: 5.4.3
Form factor: Keychain (USB-A)
Enabled USB interfaces: OTP, FIDO, CCID
NFC transport is enabled.
Applications    USB     NFC
FIDO2           Enabled Enabled
OTP             Enabled Enabled
FIDO U2F        Enabled Enabled
OATH            Enabled Enabled
OpenPGP         Enabled Enabled
PIV             Enabled Enabled
 C:\..\YubiKey Manager  .\ykman.exe oath accounts list
WARNING: PCSC not available. Smart card protocols will not function.
Error: No YubiKey found with the given interface(s)
 C:\..\YubiKey Manager  .\ykman.exe list
WARNING: PCSC not available. Smart card protocols will not function.
YubiKey NEO (3.4.9) [OTP+CCID] 
 C:\..\YubiKey Manager  .\ykman.exe info
WARNING: PCSC not available. Smart card protocols will not function.
Device type: YubiKey NEO
Serial number: 
Firmware version: 3.4.9
Enabled USB interfaces: OTP, CCID
NFC transport is enabled.

Applications    USB             NFC
FIDO2           Not available   Not available
OTP             Enabled         Enabled
FIDO U2F        Disabled        Enabled
OATH            Enabled         Enabled
OpenPGP         Enabled         Enabled
PIV             Enabled         Enabled
 C:\..\YubiKey Manager  .\ykman.exe oath accounts list
WARNING: PCSC not available. Smart card protocols will not function.
Error: No YubiKey found with the given interface(s)
```

Expected result
---

The device to be recognised and/or show 2FA Codes

Actual results
---

Device isn't recognised / cant read CCID/OTP interface

Other info
---

Troubleshooting steps taken

1. Clean reinstall
2. Application Downgrade
3. Driver uninstall from Device Manager
4. Removal of all *yubi* directories from PC, including %appdata%
5. Purchasing new key
6. Testing on another PC (Works fine on my Linux Machine, Works fine on my 2004 Machine, Havent been able to test on a 20H2 Machine.
7. Ran a procmon, to verify there was no other configuration file or registry key I might have missed that could cause the issue.

```


Expected result
---
See my 2FA Codes / Accounts

Actual results and logs
---
Nil 2FA Codes Accounts, Similar to https://github.com/Yubico/yubioath-desktop/issues/737


Other info
---
Have attempted a driver reinstall

**Comment by BuxtonWater** [comment]
Bless you for your foolish mistake, you saved me from the exact same thing lol. Cheers man
