### ISSUE TITLE
YubiKey 4's PIN counter cannot be reset due to "Error: PIN/PUK must be no longer than 8 bytes" error

### ISSUE THREAD

**Issue by zoltan-fedor** [Yubico/yubikey-manager#451]
- YubiKey Manager (ykman) version: 4.0.5
- How was it installed?: from ppa:yubico/stable
- Operating system and version: Linux Mint 20.2
- YubiKey model and version: YubiKey 4 Nano
- Bug description summary: I have a YubiKey 4 Nano which I am using for years. When I have set it  up, I have set it up with a 12 character long PIN and a 10 character long PUK. Unfortunately today I have typed in the PIN wrong 3 times. I thought no problem, I will reset the PIN counter, so I have installed the latest yubikey-manager and to my surprised when I have tried to unblock the PIN it didn't allow me due to "Error: PIN/PUK must be no longer than 8 bytes"!

Steps to reproduce
---
```
$ sudo add-apt-repository ppa:yubico/stable && sudo apt-get update
$ sudo apt install yubikey-manager
$ ykman piv access unblock-pin
Enter PUK: 
Enter a new PIN: 
Error: PIN/PUK must be no longer than 8 bytes
```

Expected result
---

It should allow me to unblock PIN if earlier versions of the Yubikey manager (ybucio-piv-tool ?) allowed the setting of PINs and PUKs longer than 8 bytes. Basically it seems that I cannot use an earlier created PUK if that was longer than 8 bytes to unlock a PIN.

**Comment by dainnilsson** [comment]
YubiKeys (as specified in the PIV standard) do not support a PIN/PUK longer than 8 bytes, so it's not possible to have such a PIN/PUK set. Are you possibly referring to the OpenPGP PIN and Reset Code instead (these can be longer)? If so, you can use the `gpg` command line tool to set a new PIN.

**Comment by zoltan-fedor** [comment]
Hmmm. I am referring to the PIN for which the counter is displayed via `PIN retry counter` when calling `gpg --card-status`, see below.

```
$ gpg --card-status
...
Max. PIN lengths .: 127 127 127
PIN retry counter : 0 0 3
...
```

I am trying to reset that PIN counter. I thought `$ ykman piv access unblock-pin` would do that.

**Comment by dainnilsson** [comment]
Ah, right. So that would be the OpenPGP applet then, which supports PIN and Access Code longer than 8 bytes. The `ykman` tool doesn't currently support managing that PIN, so instead you'll need to use the card edit menu of GnuPG,  which is accessed by running `gpg --card-edit`. It's an interactive command which lets you change and unblock the PIN, among other things.

**Comment by zoltan-fedor** [comment]
You are quite correct.
It seems I got confused by the two.
Closing this issue now, thanks for the quick help!

**Comment by dainnilsson** [comment]
Great, happy to help!
