### ISSUE TITLE
Version scheme change for python-cryptography causes installation issues

### ISSUE THREAD

**Issue by gbcox** [Yubico/yubikey-manager#458]
- YubiKey Manager (ykman) version: 4.0.7
- How was it installed?: dnf install
- Operating system and version: Fedora 35
- YubiKey model and version: N/A
- Bug description summary:

python3-cryptography has changed their version scheme.  The new version is not 3.5 it is now 35.  This is causing dependency issues, i.e.:

cannot install both python3-cryptography-35.0.0-2.fc35 and python3-cryptography-3.4.7.5
package python3-yubikey-manager-4.0.7 requires (python3.10dist(cryptography) < 4 with python3.10dist(cryptography) >= 2.1)

Fedora 35 is in beta now, that is how I discovered the issue and is scheduled to go into production in a few weeks.  

yubikey dependency checks need to be adjusted to allow for the new versioning scheme.

https://cryptography.io/en/latest/changelog/#v35-0-0

:-) Don't shoot the messenger...

Thanks!

**Comment by dainnilsson** [comment]
Thank you, added for the next release!
