### ISSUE TITLE
macOS: is there a packaged CLI-only download?

### ISSUE THREAD

**Issue by gnida-rada** [Yubico/yubikey-manager#463]
- Operating system and version: macOS
- YubiKey model and version: 4

On this page: https://docs.yubico.com/software/yubikey/tools/ykman/Install_ykman.html
I see it is possible to download macOS .pkg **of GUI** or download CLI-only using Homebrew.
Homebrew use is banned in my company and GUI is too large. 
Is there a pre-packaged download of CLI-only ykman for macOS?
Thanks!

**Comment by ricandr** [comment]
Do you absolutely need a packaged download or might `pip install --user yubikey-manager` work for your use case?

**Comment by gnida-rada** [comment]
we cannot rely on any package downloading system. So pip is as no-go as brew. Thanks

**Comment by dainnilsson** [comment]
We don't currently provide this, but we are discussing if this is something we should make available.

**Comment by mireille-raad** [comment]
I am using `Python 3.9.10` on a macOS 12.2 Monterey (all updates applied), M1 Machine. The machine is freshly erased with just python3 installed.

I get slightly different error related to `pyscard` if I run  `python3 -m pip install --user yubikey-manager` or if I use a virtual environment and run `pip install yubikey-manager`

## virtual env 
```
Installing collected packages: pyscard, six, pycparser, click, cffi, cryptography, pyOpenSSL, fido2, yubikey-manager
  Running setup.py install for pyscard ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for pyscard did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      running install
      /Users/xxxx/xxxx/env/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      running build_ext
      swig -python -outdir smartcard/scard -DPCSCLITE -D__APPLE__ -D__LION__ -o smartcard/scard/scard_wrap.c smartcard/scard/scard.i
      error: command 'swig' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pyscard

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```
 
## system wide install

if I run `python3 -m pip install --user yubikey-manager` 

```
Complete output (6 lines):
  running bdist_wheel
  running build
  running build_py
  running build_ext
  swig -python -outdir smartcard/scard -DPCSCLITE -D__APPLE__ -D__LION__ -o smartcard/scard/scard_wrap.c smartcard/scard/scard.i
  error: command 'swig' failed: No such file or directory
  ----------------------------------------
  ERROR: Failed building wheel for pyscard
  Running setup.py clean for pyscard
Successfully built fido2
Failed to build pyscard
Installing collected packages: pycparser, cffi, six, cryptography, pyscard, pyOpenSSL, fido2, click, yubikey-manager
    Running setup.py install for pyscard ... error
    ERROR: Command errored out with exit status 1:```

Are there known issues with MacOS version, M1 chips or Python3.9 ? should I just try again? any hint on how I can get a pre-built wheel or something that pip doesn't have to build on my machine? or a cli?

**Comment by mireille-raad** [comment]
Is this the `pyscard` that is failing ? is it a third party dependency?

This PyPi page is blank https://pypi.org/project/pyscard/

The GitHub repo I could find is this: https://github.com/LudovicRousseau/pyscard 

Is this the correct place to look for a fix?

**Comment by mireille-raad** [comment]
🤦‍♀️  Never mind, got it to work.

For any future person and future self, the pip install works, just make sure you do: `brew install swig` first.

**Comment by mireille-raad** [comment]
Here is the CLI - https://docs.yubico.com/software/yubikey/tools/ykman/Using_the_ykman_CLI.html#macos

So, maybe the answer is yes, there is a command line tool. 

Should this issue be closed?

**Comment by dainnilsson** [comment]
Just wanted to provide a quick update here: ykman 5.0 is now released, and we will have a standalone MacOS installer for it shortly.

**Comment by dainnilsson** [comment]
Mac installer now uploaded!
https://github.com/Yubico/yubikey-manager/releases/tag/5.0.0
