### ISSUE TITLE
Installation fails in F36 due to new release of python-cryptography

### ISSUE THREAD

**Issue by gbcox** [Yubico/yubikey-manager#467]
Thank you, added for the next release!

_Originally posted by @dainnilsson in https://github.com/Yubico/yubikey-manager/issues/458#issuecomment-936836555_

Error for F36 install:
Your package (yubikey-manager) Fails To Install in Fedora 36:

can't install python3-yubikey-manager:
  - nothing provides (python3.10dist(cryptography) < 36 with python3.10dist(cryptography) >= 2.1) needed by python3-yubikey-manager-4.0.7-5.20211006git9f342bc.fc36.noarch

Looks like patch 0f98c3e isn't sufficient for the next release of python3-cryptography

**Comment by dainnilsson** [comment]
What version is the cryptography package available in Fedora?

**Comment by squidpickles** [comment]
Just verified, Fedora 36 is using version 36 of `cryptography`.

Ran into this issue because nixpkgs also provides version 36 of `cryptography`, breaking the `yubikey-manager` package.

**Comment by alex** [comment]
This would be fixed by https://github.com/Yubico/yubikey-manager/pull/475

**Comment by gbcox** [comment]
> What version is the cryptography package available in Fedora?

This is the version for the forthcoming F36:  python-cryptography-36.0.0-2.fc36
Current Beta release target for F36 is March 15th, but the rawhide branch date is February 8th, and I'd like to have this built and submitted to make the branch date if possible.  Thanks!

**Comment by dainnilsson** [comment]
> > What version is the cryptography package available in Fedora?
> 
> This is the version for the forthcoming F36: python-cryptography-36.0.0-2.fc36 Current Beta release target for F36 is March 15th, but the rawhide branch date is February 8th, and I'd like to have this built and submitted to make the branch date if possible. Thanks!

That should be possible. Stay tuned!

**Comment by dainnilsson** [comment]
4.0.8 is now released which allows Cryptography < 39, so that should buy us more time in the future as new versions of cryptography are released. As long as we make sure we're not using any deprecated functionality we should be compatible with current+2, according to the versioning scheme they use.
