### ISSUE TITLE
Mac M1 platform support?

### ISSUE THREAD

**Issue by roycewilliams** [Yubico/yubikey-manager#468]
Are there any plans/timelines for native Apple Silicon / M1 support ?

**Comment by dainnilsson** [comment]
My understanding is that the build from Homebrew is fully arm64 when running on an M1 Mac, can you confirm if that is the case?

**Comment by roycewilliams** [comment]
@ridicolos Can you weigh on on the above?

**Comment by ridicolos** [comment]
So I got the latest version of the yubikey-manager installed. (1.2.4)

If I have a look into the acitvity-monitor the manager is running under rosetta.

![bild2](https://user-images.githubusercontent.com/25656713/144511589-704f285f-5966-4be9-8e3b-2bc20161fa7e.png)

I also reinstalled the app `brew reinstall yubico-yubikey-manager`, but it is still running under rosetta

**Comment by dainnilsson** [comment]
Ah. This repository is for the command line interface, ykman, which is what I was referring to. So to clarify, I believe the CLI tool is available as a native arm64 binary when installing from Homebrew.

The YubiKey Manager GUI project repository is `yubikey-manager-qt`. That said, the GUIs (both Yubico Authenticator and YubiKey Manager) while fully supported on the M1 architecture, are not currently available as native arm64 binaries. I can't give a timeline for this at the moment.
