### ISSUE TITLE
Yubikey manager isn't recognized in CLI

### ISSUE THREAD

**Issue by htd-tstepien** [Yubico/yubikey-manager#469]
- YubiKey Manager (ykman) version: 1.2.4
- How was it installed?: `QT GUI` (because it contains CLI too), after having issue with it reinstalled with `pip`
- Operating system and version: Windows 10 Pro, 20H2, build: 1942.1348
- YubiKey model and version: Yubikey 5 NFC, firmware 5.4.3
- Bug description summary: So I want to add key to my database in KeeWeb but it's not recognized at all. Turned out that my YubiKey CLI isn't installed/path to it isn't recognized. When trying to run `ykman help` in the cmd I get `'ykman' is not recognized as an internal or external command, operable program or batch file.`

Steps to reproduce
---
1. Install yubikey manager from [here](https://developers.yubico.com/yubikey-manager-qt/Releases/) (Admin CMD > run `.exe`)
2. Restart PC
3. Open cmd and type `ykman help`

Expected result
---
1. Answer that ykman is installed and help text

Actual results and logs
---
```
'ykman' is not recognized as an internal or external command,
operable program or batch file.
```

Other info
---

At first I tried to resolve this issue on KeeWeb github page, but turned out that's the problem of the installation probably. Issue is [here](https://github.com/keeweb/keeweb/issues/1952). Is there any hidden config to make after installation is complete to have `ykman` in CLI?

**Comment by dainnilsson** [comment]
For the `ykman` command to be runnable in a terminal from anywhere, you'll need to add the location of the executable to your computers PATH. I found this page which has instructions for several Windows versions: https://www.computerhope.com/issues/ch000549.htm

Using the default installation location, the path you'll want to add is: `C:\Program Files\Yubico\YubiKey Manager`

**Comment by htd-tstepien** [comment]
oh... @dainnilsson - shouldn't it be provided in YubiKey Manager installation guide?

**Comment by dainnilsson** [comment]
The installer is mainly for the GUI application, which has shortcuts created for it in the start menu. Adding additional items to the PATH isn't something most users will want or need (you don't have to have it added to the PATH to run it, only for it to be found from anywhere). We might make this an option at installation time in the future, or provide a separate installer specifically for the CLI tool.
