### ISSUE TITLE
Ykman Oath not working in Alpine - "No Yubikey found with the given interface(s)"

### ISSUE THREAD

**Issue by zpeterg** [Yubico/yubikey-manager#471]
- YubiKey Manager (ykman) version: 4.0.7
- How was it installed?: python3/pip
```
 sudo apk add py3-pip
sudo apk add build-base
sudo apk add python3-dev
sudo apk add libffi-dev
sudo apk add swig
pip install --upgrade pip
pip install --user yubikey-manager
```
Created /etc/udev/rules.d/70-u2f.rules with content:

`KERNEL=="hidraw*", SUBSYSTEM=="hidraw", MODE="0664", GROUP="plugdev", ATTRS{idVendor}=="1050", ATTRS{idProduct}=="0113|0114|0115|0116|0120"`

At this point, `ykman info` works fine.

- Operating system and version: postmarketos (Alpine)
- YubiKey model and version:  Yubikey NEO, firmware 3.0.0
- Bug description summary: 

Steps to reproduce
---

1. Install as per above
2. `ykman oath account list` yields "No YubiKey found with the given interface(s)"

Expected result
---

List of oath accounts. (I tested the same yubikey on another linux machine using the ykman -> oath command it works fine.)

Actual results and logs
---

`
2021-12-19T18:45:42-0600 ERROR [ykman.cli.__main__.main:386] Error
Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/ykman/cli/__main__.py", line 104, in retrying_connect
    _, state = _scan_changes(state)
  File "/root/.local/lib/python3.9/site-packages/ykman/cli/__main__.py", line 91, in _scan_changes
    raise TimeoutError("Timed out waiting for state change")
TimeoutError: Timed out waiting for state change
`

Other info
---

I also tried `apk add libu2f-host-dev` and `udevadm trigger` / restarts without change. PCSCD is verified running per `service pcscd status`. I also tried the yubikey rule per here https://github.com/Yubico/yubikey-personalization/blob/master/69-yubikey.rules - no difference there.

I do note that `ykman list --readers` yields nothing. I surmise that means the CCID isn't working??

**Comment by dainnilsson** [comment]
It does indeed sound like a problem with pcscd, it might be permissions related. You could try running `ykman --diagnose` to output additional information (this should be run with a YubiKey attached). You can try running the same with `sudo` as well, to see if it has with permissions to do. You might also want to install `pcsc-tools` and run `pcsc_scan`.

**Comment by Utopiah** [comment]
Same problem as root with a YubiKey 5Ci firmware 5.2.4 also with pscp on PostMarketOS.

**Comment by zpeterg** [comment]
@dainnilsson, thanks for your reply. 

Like Utopiah, I am getting nothing for PC/SC readers or for YubiKeys-over-PC/SC when I run `ykman --diagnose`. This is the same regardless of whether run as sudo or not - eg:
```
%m:%~%# ykman --diagnose
ykman: 4.0.7
Python: 3.9.7 (default, Nov 24 2021, 21:15:59) 
[GCC 10.3.1 20211027]
Platform: linux
Arch: aarch64
Running as admin: True

Detected PC/SC readers:

Detected YubiKeys over PC/SC:

Detected YubiKeys over HID OTP:
	OtpYubiKeyDevice(pid=0116, fingerprint='/dev/hidraw0')
	Failed to read device info via Management: CommandRejectedError('No data')
	DeviceInfo(config=DeviceConfig(enabled_capabilities={<TRANSPORT.USB: 'usb'>: <CAPABILITY.OATH|PIV|OPENPGP|U2F|OTP: 59>, <TRANSPORT.NFC: 'nfc'>: <CAPABILITY.OATH|PIV|OPENPGP|U2F|OTP: 59>}, auto_eject_timeout=0, 
...
 supported_capabilities={<TRANSPORT.USB: 'usb'>: <CAPABILITY.OATH|PIV|OPENPGP|U2F|OTP: 59>, <TRANSPORT.NFC: 'nfc'>: <CAPABILITY.OATH|PIV|OPENPGP|U2F|OTP: 59>}, is_locked=False, is_fips=False, is_sky=False)
	Device name: YubiKey NEO
	OTP: ConfigState(configured: (False, True), touch_triggered: (False, True), led_inverted: False)


Detected YubiKeys over HID FIDO:
	CtapYubiKeyDevice(pid=0116, fingerprint='/dev/hidraw1')
CTAP device version: 1.1.0
CTAPHID protocol version: 2
Capabilities: 1
	Failed to read device info via Management: CtapError('CTAP error: 0x01 - INVALID_COMMAND')
	DeviceInfo(config=DeviceConfig(enabled_capabilities={<TRANSPORT.USB: 'usb'>: <CAPABILITY.OATH|PIV|OPENPGP|U2F|OTP: 59>, <TRANSPORT.NFC: 'nfc'>: <CAPABILITY.OATH|PIV|OPENPGP|U2F|OTP: 59>}, auto_eject_timeout=0, challenge_response_timeout=0, device_flags=<DEVICE_FLAG.0: 0>), serial=None, version=Version(major=3, minor=0, patch=0), form_factor=<FORM_FACTOR.USB_A_KEYCHAIN: 1>, supported_capabilities={<TRANSPORT.USB: 'usb'>: <CAPABILITY.OATH|PIV|OPENPGP|U2F|OTP: 59>, <TRANSPORT.NFC: 'nfc'>: <CAPABILITY.OATH|PIV|OPENPGP|U2F|OTP: 59>}, is_locked=False, is_fips=False, is_sky=False)
	Device name: YubiKey NEO
	Couldn't get info: ValueError('Device does not support CTAP2.')

End of diagnostics
```

**Comment by dainnilsson** [comment]
If `pcsc_scan` isn't even able to see the YubiKey then the issue isn't with `ykman`. I'm not sure why the YubiKey wouldn't be detected by pcscd, but that's the problem you'll have to solve before `ykman` will have any chance of working.

**Comment by zpeterg** [comment]
Ok, thanks. I'll close this.
