### ISSUE TITLE
French layout: Unsupported character: #

### ISSUE THREAD

**Issue by WeetA34** [Yubico/yubikey-manager#480]
- YubiKey Manager (ykman) version:
v1.2.4
- How was it installed?:
package from support download page
- Operating system and version:
macOS Monterey 12.1
- YubiKey model and version:
YubiKey 5 NFC (firmware 5.1.2)
- Bug description summary:
Unable to use # in OTP Static password with French layout

Steps to reproduce
---

ykman otp static -k FR 1

Expected result
---

Static password saved to YubiKey

Actual results and logs
---

Error: Unsupported character: #

Other info
---

**Comment by dainnilsson** [comment]
Hi. The YubiKey is only able to output scan codes of single keys + the shift key modifier. This means that characters which require an additional key to be pressed (such as `#` which requires `Alt Gr`) cannot be supported for static passwords.

**Comment by WeetA34** [comment]
Hello @dainnilsson 
Ok. understood.
Thank you
