### ISSUE TITLE
YKMan 4.0.3 will not see more than 10 tokens

### ISSUE THREAD

**Issue by wagner-robert** [Yubico/yubikey-manager#481]
- YubiKey Manager (ykman) version:  4.0.3  (windows binary)
- How was it installed?:  Windows binary build
- Operating system and version:  Win 10
- YubiKey model and version:  v5 FIPS
- Bug description summary:

Running a batch script to manage tokens in a 16 port USB hub.  This queries the attached tokens with "ykman list -s"
However, the command will only show the first 10 tokens connected.

Steps to reproduce
---
Connect 16 tokens to USB-A hub.  run ykman list -s.

Expected result
---
Should be able to see all 16.  They show up in device manager, but not within ykman list -s.

**Comment by qpernil** [comment]
Windows has a 10 token limit in PCSC

**Comment by wagner-robert** [comment]
https://docs.microsoft.com/en-us/troubleshoot/windows/win32/limitation-10-smart-card-readers
Thanks, I see that now.  I assume that other OSs do not have such a limit - What have other's experienced?

RW
________________________________

**Comment by dainnilsson** [comment]
Closing this as there is nothing for us to do here.
