### ISSUE TITLE
How can I import my existing GPG keys

### ISSUE THREAD

**Issue by eastack** [Yubico/yubikey-manager#487]
- YubiKey Manager (ykman) version: 4.0.7
- How was it installed?: pacman
- Operating system and version: archlinux
- YubiKey model and version: YubiKey 5 NFC 5.2.7

**Comment by dainnilsson** [comment]
This project doesn't manage OpenPGP keys, you'll need to use gnupg for that. Here's a guide: https://support.yubico.com/hc/en-us/articles/360013790259-Using-Your-YubiKey-with-OpenPGP

**Comment by eastack** [comment]
Thanks for your help.
