### ISSUE TITLE
`ykman oath accounts add` fails with a message about enabling CCID, but CCID is enabled

### ISSUE THREAD

**Issue by ruuda** [Yubico/yubikey-manager#488]
- YubiKey Manager (ykman) version: 4.0.7
- How was it installed?: With [`pacman -S yubikey-manager`](https://archlinux.org/packages/community/any/yubikey-manager/)
- Operating system and version: Arch Linux, kernel 5.16.5-arch1-1
- YubiKey model and version: YubiKey 5 NFC, firmware version 5.4.3
- Bug description summary: `oath accounts add` fails with a message about needing ‘CCID’ to be enabled, but it is already enabled, and it is also not possible to enable this through `ykman config usb`.

Steps to reproduce
---

I want to add a new OATH account. In the steps below, I replaced my device serial with a dummy value.

First I tried just adding an account:

```console
$ ykman oath accounts add --touch test-for-repro AAAAAAAAAA======
WARNING: PC/SC not available. Smart card protocols will not function.
Error: No eligiable connections are available ([<class 'yubikit.core.smartcard.SmartCardConnection'>]).
```

Hmm, maybe I need to pass `--device`:

```console
$ ykman list  
WARNING: PC/SC not available. Smart card protocols will not function.
YubiKey 5 NFC (5.4.3) [OTP+FIDO+CCID] Serial: 0123456

$ ykman --device 0123456 oath accounts add --touch test-for-repro AAAAAAAAAA======
WARNING: PC/SC not available. Smart card protocols will not function.
Error: Command 'oath' requires one of the following USB interfaces to be enabled: 'CCID'.

Use 'ykman config usb' to set the enabled USB interfaces.
```

Hmm, okay, let’s check that out:
```console
$ ykman config usb --help
Usage: ykman config usb [OPTIONS]

  Enable or disable applications over USB.

Options:
  -f, --force                     Confirm the action without prompting.
  -e, --enable [OTP|U2F|FIDO2|OATH|PIV|OPENPGP|HSMAUTH]
                                  Enable applications.
  -d, --disable [OTP|U2F|FIDO2|OATH|PIV|OPENPGP|HSMAUTH]
                                  Disable applications.
  -l, --list                      List enabled applications.
  -a, --enable-all                Enable all applications.
  -L, --lock-code HEX             Current application configuration lock code.
  --touch-eject                   When set, the button toggles the state of the smartcard between ejected and inserted. (CCID only).
  --no-touch-eject                Disable touch eject (CCID only).
  --autoeject-timeout SECONDS     When set, the smartcard will automatically eject after the given time. Implies --touch-eject.
  --chalresp-timeout SECONDS      Sets the timeout when waiting for touch for challenge-response in the OTP application.
  -h, --help                      Show this message and exit.
```
It looks like there is no way to enable "CCID"? But I can enable "OATH". Is "CCID" enabled already?

```console
$ ykman config usb --list
WARNING: PC/SC not available. Smart card protocols will not function.
OTP
FIDO U2F
FIDO2
OATH
PIV
OpenPGP
YubiHSM Auth

$ ykman info
WARNING: PC/SC not available. Smart card protocols will not function.
Device type: YubiKey 5 NFC
Serial number: 0123456
Firmware version: 5.4.3
Form factor: Keychain (USB-A)
Enabled USB interfaces: OTP, FIDO, CCID
NFC transport is enabled.

Applications	USB    	NFC    
FIDO2       	Enabled	Enabled	
OTP         	Enabled	Enabled	
FIDO U2F    	Enabled	Enabled	
OATH        	Enabled	Enabled	
YubiHSM Auth	Enabled	Enabled	
OpenPGP     	Enabled	Enabled	
PIV         	Enabled	Enabled	
```

I am not sure what I am supposed to do here, but it looks like CCID is already enabled. Is the error message of `oath accounts add` just wrong? Or is there something else going on here?

Expected result
---

I expect `ykman oath accounts add` to succeed.

Actual results and logs
---

See output above.

Other info
---

I see that version 4.0.8 has been released. It is not yet available for my distro. But from the release page, it doesn’t look like it contains any changes related to OATH.

**Comment by dainnilsson** [comment]
Hi! The "PC/SC not available" warning means your system doesn't have a smartcard service running (or it's not accessible by your current user). This means that `ykman` will not be able to access the CCID interface of your YubiKey, regardless of if it is enabled or not. You need to install or enable `pcscd` for that to work, though `pacman`.

**Comment by ruuda** [comment]
Ah, of course! It wasn’t clear to me that PC/SC was needed for OATH. I should have checked [the wiki](https://wiki.archlinux.org/title/Yubikey), it literally says

> **Note:** After installation, enable `pcscd.service`

With that enabled, `ykman oath accounts add` works fine. Thanks a lot @dainnilsson, apologies for the noise.

I hope this issue will still be useful to future visitors searching for the error message :-)
