### ISSUE TITLE
Release 4.0.8 not available on a web page

### ISSUE THREAD

**Issue by jpalus** [Yubico/yubikey-manager#489]
Looking at [Releases](https://github.com/Yubico/yubikey-manager/releases) page at GitHub it appears that version 4.0.8 was released a while ago, however [Release Notes](https://developers.yubico.com/yubikey-manager/Release_Notes.html) still claims _Unreleased_ status and therefore tarball is not available at [Releases](https://developers.yubico.com/yubikey-manager/Releases/) at _yubico.com_.

**Comment by dainnilsson** [comment]
Thanks! Looks like an oversight on our part. I've updated the NEWS file with the release date, and have uploaded the release artifacts to the developers site. The site will refresh sometime later today and the changes will then be visible.
