### ISSUE TITLE
ykman reports that FIDO interface is not enabled when it is

### ISSUE THREAD

**Issue by shane-axiom** [Yubico/yubikey-manager#490]
- YubiKey Manager (ykman) version: 4.0.8
- How was it installed?: pip
- Operating system and version: Debian 11
- YubiKey model and version:  YubiKey 5 NFC 5.2.7
- Bug description summary:

ykman can't show info or configure FIDO settings even though key supports FIDO and the USB interface is enabled.

Steps to reproduce
---

* Plug in yubikey
* Run `ykman info` to view info and capabilities and verify FIDO is supported and enabled
* Run `ykman fido info` or `ykman fido credentials list`, get error

Expected result
---

FIDO info/credentials are displayed

Actual results and logs
---

```
(base) ➜  ~ ykman info     
Device type: YubiKey 5 NFC
Serial number: XXXXXXXX
Firmware version: 5.2.7
Form factor: Keychain (USB-A)
Enabled USB interfaces: OTP, FIDO, CCID
NFC transport is enabled.

Applications    USB             NFC          
FIDO2           Enabled         Enabled      
OTP             Enabled         Enabled      
FIDO U2F        Enabled         Enabled      
OATH            Enabled         Enabled      
YubiHSM Auth    Not available   Not available
OpenPGP         Enabled         Enabled      
PIV             Enabled         Enabled      
(base) ➜  ~ ykman -d XXXXXXXX fido info
Error: Command 'fido' requires one of the following USB interfaces to be enabled: 'FIDO'.

Use 'ykman config usb' to set the enabled USB interfaces.
```

**Comment by dainnilsson** [comment]
My first guess would be that this is permissions related. As a test you could try running the `... fido info` command as root and see if that makes a difference. If that works, then you probably just need to make sure your user has permission to access the device. See here: https://github.com/Yubico/yubikey-manager/blob/main/doc/Device_Permissions.adoc

**Comment by shane-axiom** [comment]
Thank you, running as root did indeed work. I did try with [`libyubikey-udev`](https://packages.debian.org/bullseye/libyubikey-udev) installed (and rebooted) but that rule didn't seem to work for me.

Rule from libyubikey-udev didn't work:
```
$ cat /usr/lib/udev/rules.d/69-yubikey.rules
ACTION!="add|change", GOTO="yubico_end"

# Udev rules for letting the console user access the Yubikey USB
# device node, needed for challenge/response to work correctly.

# Yubico Yubikey II
ATTRS{idVendor}=="1050", ATTRS{idProduct}=="0010|0110|0111|0114|0116|0401|0403|0405|0407|0410", \
    ENV{ID_SECURITY_TOKEN}="1"
```

This manual rule did the trick:
```
$ cat /etc/udev/rules.d/70-yubikey.rules 
ACTION!="add|change", GOTO="yubikey_end"

KERNEL=="hidraw*", SUBSYSTEM=="hidraw", ATTRS{idVendor}=="1050", ATTRS{idProduct}=="0113|0114|0115|0116|0120|0121|0200|0402|0403|0406|0407|0410", TAG+="uaccess", GROUP="plugdev", MODE="0660"

LABEL="yubikey_end"
```

Should a bug be filed somewhere? Maybe on [libyubikey-udev](https://packages.debian.org/bullseye/libyubikey-udev) or [yubikey-personalization](https://github.com/Yubico/yubikey-personalization)?

**Comment by shane-axiom** [comment]
Just another note, it seems like the working udev rule used to be installed by the [libu2f-udev](https://packages.debian.org/bullseye/libu2f-udev) package (older versions reference [70-u2f.rules](https://github.com/Yubico/libu2f-host/blob/master/70-u2f.rules). Newer versions of the package state

> This package is not necessary anymore, and can be safely removed: since udev v244, U2F devices are autodetected without needing 3rd party udev rules.

but this didn't seem to be the case for me on Debian 11 with udev 247

```
$ udevadm -V
247
```

**Comment by dainnilsson** [comment]
libyubikey and yubikey-personalization use the `OTP` (keyboard) interface to communicate with the YubiKey, not the `FIDO` one that you're having issues with (the relevant Udev rules for FIDO is `70-u2f.rules`, as you already found), so those projects aren't relevant to this issue.

As you stated, udev 244 (and later) shouldn't require additional rules for FIDO at all, so I'm not sure why it was needed in your case. We tried to reproduce this by testing a new VM with Debian 11, and we were able to access the YubiKey via the FIDO interface as a regular/unprivileged user, without needing to add any rules explicitly.

**Comment by shane-axiom** [comment]
Ok, I tested on another Debian 11 machine and things worked as expected (a non-root user was able to `ykman fido info` without any udev rules due to udev >= 244). My troubles must have been idiosyncratic to the machines I was testing on. Closing this for now, I'll comment if anything else comes up. Thanks for the pointers!
