### ISSUE TITLE
Can't remove discoverable FIDO credential with name that is a prefix of another discoverable FIDO credential.

### ISSUE THREAD

**Issue by valderman** [Yubico/yubikey-manager#491]
- YubiKey Manager (ykman) version: 4.0.0.1a
- How was it installed?: apt
- Operating system and version: Ubuntu Impish
- YubiKey model and version: Yubikey 5C, firmware version 5.2.7
- Bug description summary: Can't remove discoverable FIDO credential with name that is a prefix (or postfix, or infix) of another discoverable FIDO credential.

Steps to reproduce
---

1. Create an openssh FIDO credential which has `ssh:` as a prefix: `ssh-keygen -t ed25519-sk -Oresident -Oapplication=ssh:valderman@github`
2. Create an openssh FIDO credential without specifying `-Oapplication`; it will be named `ssh:`: `ssh-keygen -t ed25519-sk -Oresident`
3. Verifty that both credentials have been created: `ykman fido credentials list`
4. Attempt to delete the `-Oapplication`-less credential: `ykman fido credentials delete 'ssh:'`

Expected result
---

The `ssh:` credential is deleted.

Actual results and logs
---

`ykman` prints `Error: Multiple matches, make the query more specific.` and does not delete the credential.

Other info
---

This is caused by the partial matching in the delete command. If `in` is replaced with `==` in the `hits` list comprehension (`creds_delete` in `cli/fido.py`) the issue goes away, but then we don't get partial matching. Maybe add an `--exact-match` flag?

**Comment by dainnilsson** [comment]
Can you try the latest release (4.0.8)? I recall we changed the logic a bit around that, so this may no longer be an issue.

**Comment by valderman** [comment]
@dainnilsson I could certainly try, but the code in question (https://github.com/Yubico/yubikey-manager/blob/6a61db55a316aec374de8e80950918331bcc33d6/ykman/cli/fido.py#L549) still uses the same "get all credentials such that the query is a substring of its name, then error out if there is more than one match" logic as far as I can tell.

**Comment by fdennis** [comment]
@valderman When you run `ykman fido credentials list` the list of credentials shown should contain three fields. You can delete using any of these fields, i.e. you do not have to use only the username.  The second field should consist of an id and be unique, try using that instead of the username and see if it works better.

**Comment by valderman** [comment]
@fdennis Unfortunately, this doesn't seem to work in my case. Listing all credentials yields the following:
```
ssh:user1 0000000000000000000000000000000000000000000000000000000000000000 openssh
ssh:user1@github 0000000000000000000000000000000000000000000000000000000000000000 openssh
ssh:user2@github 0000000000000000000000000000000000000000000000000000000000000000 openssh
ssh:user3@github 0000000000000000000000000000000000000000000000000000000000000000 openssh
```
I don't know if this is because openssh messes up the credential ID or if there's an issue with listing credentials.

**Comment by dainnilsson** [comment]
I can confirm that this currently seems broken. I think we need to rethink the way this command works a bit.

**Comment by IceDops** [comment]
Any updates on this issue?

**Comment by dainnilsson** [comment]
I believe the proper fix here is to change the query format a bit (probably disallow partial matching of RP ID and maybe User Name). I'm not sure if we can do this in a "backwards compatible" way for the next point release, or if it will have to wait for 5.0.0. 

I realize now that there is a workaround which should already allow you to delete these credentials, which is to match the entire string as output by `fido list`:

Eg. (using the credentials from @valderman) the following should work:

```
ykman fido delete "ssh:user2@github 0000000000000000000000000000000000000000000000000000000000000000 openssh"
```

**Comment by dainnilsson** [comment]
ykman 5.0 is now released, and these commands have been changed to avoid any ambiguity. Credentials are now identified by (a substring of) their Credential ID, which is always unique.
