### ISSUE TITLE
Cannot install ykman with apt on upcoming Ubuntu LTS

### ISSUE THREAD

**Issue by wkaluza** [Yubico/yubikey-manager#496]
- YubiKey Manager (ykman) version: Latest (4.0.8)
- How was it installed?: not applicable
- Operating system and version: Ubuntu 22.04 LTS Beta
- YubiKey model and version: not applicable
- Bug description summary: Attempting to install ykman CLI vie the apt PPA fails (missing Release file)

Steps to reproduce
---

```
$ sudo add-apt-repository --yes ppa:yubico/stable
```

Expected result
---

I expected the above command to succeed.

Actual results and logs
---

```
$ sudo add-apt-repository --yes ppa:yubico/stable
[sudo] password for myusername: 
Repository: 'deb https://ppa.launchpadcontent.net/yubico/stable/ubuntu/ jammy main'
Description:
PPA for stable Yubico software.
More info: https://launchpad.net/~yubico/+archive/ubuntu/stable
Adding repository.
Adding deb entry to /etc/apt/sources.list.d/yubico-ubuntu-stable-jammy.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/yubico-ubuntu-stable-jammy.list
Adding key to /etc/apt/trusted.gpg.d/yubico-ubuntu-stable.gpg with fingerprint 3653E21064B19D134466702E43D5C49532CBA1A9
Hit:1 https://cli.github.com/packages stable InRelease
Hit:2 http://pl.archive.ubuntu.com/ubuntu jammy InRelease
Hit:3 http://pl.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:4 http://pl.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:5 https://brave-browser-apt-release.s3.brave.com stable InRelease
Hit:6 https://dl.google.com/linux/chrome/deb stable InRelease
Hit:7 https://download.docker.com/linux/ubuntu jammy InRelease
Hit:9 https://ppa.launchpadcontent.net/git-core/ppa/ubuntu jammy InRelease
Hit:8 https://cli-assets.heroku.com/apt ./ InRelease
Hit:10 http://security.ubuntu.com/ubuntu jammy-security InRelease
Ign:11 https://ppa.launchpadcontent.net/yubico/stable/ubuntu jammy InRelease
Err:12 https://ppa.launchpadcontent.net/yubico/stable/ubuntu jammy Release
  404  Not Found [IP: 91.189.95.85 443]
Reading package lists... Done                            
E: The repository 'https://ppa.launchpadcontent.net/yubico/stable/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Other info
---

I have nothing to add at this time, but I would be happy to provide additional information to help resolve the issue.

**Comment by adiroiban** [comment]
I tried a quick hack and tried to install the packages from 21.10 ... but they fail I guess due to openssl version 3 from Ubuntu 22.04

**Comment by atsuya** [comment]
Same here. Is Yubico going to support Ubuntu 22.04?

**Comment by dainnilsson** [comment]
Hi! We haven't yet published packages for 22.04, but hope to have them fairly soon.
In the meantime, you should still be able to install through `pip`, which you can read more a bout here: https://github.com/Yubico/yubikey-manager#installation

**Comment by atsuya** [comment]
@dainnilsson Thank you for sharing the update. Looking forward to it.

**Comment by dainnilsson** [comment]
We've now released packages for yubikey-manager 4.0.8 for 22.04 as well as 22.10, available through the PPA. 🎉

**Comment by adiroiban** [comment]
@dainnilsson thank for the update.

Do you know what is the status for Ubuntu 22.04 for the other packages like yubico-piv-tool and ykcs11 (PKCS#11 module for the YubiKey PIV applet)?

I see they are in Ubuntu repository, but they don't work

```
 $ yubico-piv-tool -a status
Failed to connect to yubikey.
Try removing and reconnecting the device.
```

I can report an issue over https://github.com/Yubico/yubico-piv-tool , no problem.

It is not clear if the problem should be report over GitHub or Ubuntu.

Thanks!

**Comment by dainnilsson** [comment]
I would report that to the yubico-piv-tool Github repo as a start, at least.
