### ISSUE TITLE
Cannot use OATH on YKv4 with PIV disabled

### ISSUE THREAD

**Issue by wagner-robert** [Yubico/yubikey-manager#497]
- YubiKey Manager (ykman) version: 1.2.3
- How was it installed?:  Windows GUI
- Operating system and version:
- YubiKey model and version: v4 FIPS 4.4.5
- Bug description summary:
Cannot disable PIV and OATH separately 

Steps to reproduce
--- - GOAL - Disable PIV while keeping OATH still functioning
---- NOTE - YK4 requires the MODE command which does not allow the fine grained access like YKv5
Remove CCID: ykman.exe config mode OTP+FIDO 

[Please explain what you did when the bug appeared, and if and how you have been
able to reproduce it.]
OATH are OTP codes, so one would think leaving OTP active would allow OATH to work.
After running and pulling up in the Yubico Authenticator I receive an error message
"Yubico Authenticator requires a CCID/OTP supported and compatible YubiKey."

From the command line:
ykman oath accounts add yubico f5up4ub3dw
"Command 'oath' requires one of the following USB interfaces to be enabled: 'CCID'."

Expected result
---
I would expect having OTP enable to allow access to OATH commands. V5 tokens allow one to manage USB interfaces separately for each protocol.

**Comment by dainnilsson** [comment]
OTP refers to the Yubico OTP application of the YubiKey, which is different from the OATH application. Selectively enabling and disabling individual applications is unfortunately not available on YubiKey 4, for that you need YubiKey 5.
