### ISSUE TITLE
Configure alwaysUv?

### ISSUE THREAD

**Issue by Manouchehri** [Yubico/yubikey-manager#499]
Not entirely sure if this the right place to ask, but is it possible to configure `alwaysUv`? i.e. to disable it.

Support for _listing_ `alwaysUv` was added in df1774a190c9588fc6f5fac69cebcb78f1471903.

https://github.com/Yubico/yubikey-manager/blob/df1774a190c9588fc6f5fac69cebcb78f1471903/ykman/cli/fido.py#L134-L139

cc @dainnilsson

**Comment by dainnilsson** [comment]
There is no command in ykman to configure always_uv, but the functionality is available in the `python-fido2` library: https://github.com/Yubico/python-fido2/blob/0.9.3/fido2/ctap2/config.py#L88 so you could potentially script it yourself.

**Comment by Manouchehri** [comment]
> There is no command in ykman to configure always_uv, but the functionality is available in the `python-fido2` library: https://github.com/Yubico/python-fido2/blob/0.9.3/fido2/ctap2/config.py#L88 so you could potentially script it yourself.

Do you know if any YubiKey models support setting it though?

**Comment by dainnilsson** [comment]
As far as I'm aware, any YubiKey that supports `alwaysUv` also supports toggling it. I believe that's only the YubiKey Bio at the moment.

**Comment by dainnilsson** [comment]
ykman 5.3.0 now supports toggling `alwaysUv` through the CLI.

**Comment by kathampy** [comment]
@dainnilsson Do you know if it works with 5 series keys on the latest firmware?

**Comment by dainnilsson** [comment]
AlwaysUV should be supported on YubiKey 5.5 and later.
