### ISSUE TITLE
Need building instructions

### ISSUE THREAD

**Issue by ctubbsii** [Yubico/yubikey-manager#5]
As an open source project, it'd be helpful to provide instructions to build from source, so that users can package it themselves, or so that downstream package maintainers can package it for their platform. (For example, I'd like to see yubikey-manager as an RPM in Fedora, but it's less likely to be provided by the Fedora community if there's no upstream build-from-source instructions).

**Comment by dainnilsson** [comment]
The current pip instructions are for installing from source. There isn't really a build step, as this is a pure python project. It has compiled dependencies, but building and installing those are out of the scope for this project (each dependency has instructions on how to build and install on their respective project pages). Note that there hasn't been a "1.0" release of this project, and the state should not yet be considered stable.
