### ISSUE TITLE
python library does not give out steam codes in correct format

### ISSUE THREAD

**Issue by sigboe** [Yubico/yubikey-manager#502]
- YubiKey Manager (ykman) version: 4.0.8
- How was it installed?: Fedora package and Arch Linux package
- Operating system and version: Fedora and Arch Linux
- YubiKey model and version: 5 NFC and 5C NFC
- Bug description summary:

Steps to reproduce
---

I am using this script which uses dmenu to display and type or copy OTP codes from the yubikey https://github.com/emlun/yubikey-oath-dmenu it uses the python libraries from yubikey manager, it shows a 6 digit numerical code instead of the 5 digit alphanumerical steam code. It works in ykman or the Qt desktop authenticator

Expected result
---

type or copy 5 digit alphanumerical steam code

Actual results and logs
---

types or copies a wrongly formated 6 digit numerical code

Other info
---

I also posted an issue here, including how I dumped my shared secret, but I believe the issue is upstream after reading the python script
https://github.com/emlun/yubikey-oath-dmenu/issues/24

**Comment by dainnilsson** [comment]
If it works in `ykman` as well as the Yubico Authenticator GUI, what makes you think it's an upstream issue? Without having looked at it closely, my thoughts are rather that this sounds like a missing feature in the `yubikey-oath-dmenu` project.

**Comment by sigboe** [comment]
@dainnilsson Thank you for the quick reply, I assumed that the python library had a bug that ykman, the qt application and the phone application didnt have. Sorry if I was wrong

**Comment by dainnilsson** [comment]
No problem, and I'm not saying that you *are* wrong, but I'll wait for confirmation from downstream before investigating further.

**Comment by sigboe** [comment]
@dainnilsson  I managed to produce the same issue with this very distilled python code (I am sure this can be condensed further, but I am not so quick on my feet with python) where STEAMUSERNAME has to be changed to the account name of the account

```python
#!/usr/bin/python3
import ykman.pcsc

from yubikit.core.smartcard import SmartCardConnection
from yubikit.oath import Credential
from yubikit.oath import OathSession

def format_cred_name(cred: Credential) -> str:
    return (f"{cred.issuer.strip()}: " if cred.issuer else "") + cred.name.strip()

controllers = {i: OathSession(driver.open_connection(SmartCardConnection))
               for i, driver in enumerate(
                   ykman.pcsc.list_devices())
               }

credentials = {
    k: {format_cred_name(cred): cred
        for cred in ctrl.list_credentials()
        }
    for k, ctrl in controllers.items()
}

credential_id_to_controller_idx = {
    cred_id: k
    for k, creds in credentials.items()
    for cred_id in creds.keys()
}

ctrl_idx = credential_id_to_controller_idx['Steam: STEAMUSERNAME']
ctrl = controllers[ctrl_idx]
code = ctrl.calculate_code(credentials[ctrl_idx]['Steam: STEAMUSERNAME']).value
print(code)
```

**Comment by dainnilsson** [comment]
Still, this is the library doing exactly what it is supposed to be doing.

`OathSession` knows nothing about Steam codes, as Steam isn't following the OATH standard. The library offers some [utility functions](https://github.com/Yubico/yubikey-manager/blob/main/ykman/oath.py) for formatting a Steam codes and for how ykman CLI determines when to do so, but that's nothing that happens "automatically", it needs to be invoked.

**Comment by sigboe** [comment]
Thank you very much for the very helpful information

**Comment by emlun** [comment]
Yeah, Steam codes are a [special case in the CLI layer](https://github.com/Yubico/yubikey-manager/blob/f31a3ec3918d9d977b139a8403c014268ab3f836/ykman/cli/oath.py#L610-L611), so the library is behaving as expected. This is a missing feature in `yubikey-oath-dmenu`.
