### ISSUE TITLE
 Cannot set auto eject timeout.

### ISSUE THREAD

**Issue by yuyue9284** [Yubico/yubikey-manager#506]
- YubiKey Manager (ykman) version: 4.0.8
- How was it installed?: By pip 
- Operating system and version: Win 11
- YubiKey model and version: Yubico Yubikey 4, version=Version(major=4, minor=4, patch=5)
- Bug description summary:
  Cannot set auto eject timeout.

Steps to reproduce
---
`python -m ykman.cli config mode ccid --touch-eject --autoeject-timeout 7200 -f`
Then the timeout is always set to 0.

Expected result
---
auto eject timeout should be set to 0 with touch-eject enabled.

[What did you expect to happen when you did the above?]

Actual results and logs
---
> config=DeviceConfig(enabled_capabilities={<TRANSPORT.USB: 'usb'>: <CAPABILITY.128|64|OATH|PIV|OPENPGP|4: 252>}, auto_eject_timeout=0, challenge_response_timeout=0, device_flags=<DEVICE_FLAG.0: 0>),

[What actually happened?]

Other info
---

[Anything else you would like to add?]

**Comment by dainnilsson** [comment]
The YubiKey 4 doesn't support reading the value of this setting, so the value shown in the DeviceConfig will always be 0 unfortunately. The command should still work and the setting should take effect after removal and re-insertion of the YubiKey. Can you confirm if that is the case?
