### ISSUE TITLE
New python-fido2 version for F37, now yubikey-manager won't build

### ISSUE THREAD

**Issue by gbcox** [Yubico/yubikey-manager#508]
- YubiKey Manager (ykman) version: 4.0.8 git6a61db5
- How was it installed?: Fedora RPM
- Operating system and version: Fedora 37
- YubiKey model and version: N/A
- Bug description summary:
Build fails for F37 because python-fido2 in F37 will be at 1.0.0
current limit you have specified is as follows and needs to be changed:  fido2 = ">=0.9, <1.0"

Here is the error message on build:
Problem: problem with installed package python3-yubikey-manager-4.0.8-1.20220131git6a61db5.fc36.noarch
  - package python3-yubikey-manager-4.0.8-1.20220131git6a61db5.fc36.noarch requires (python3.10dist(fido2) < 1~~ with python3.10dist(fido2) >= 0.9), but none of the providers can be installed
  - cannot install both python3-fido2-1.0.0-1.fc36.noarch and python3-fido2-0.9.3-1.fc36.noarch
  - cannot install both python3-fido2-1.0.0-1.fc36.noarch and python3-fido2-0.9.2-2.fc36.noarch

**Comment by dainnilsson** [comment]
Thanks, we'll try to get a 4.0.9 out soon to be compatible.

**Comment by dainnilsson** [comment]
4.0.9 is now out, and should work with python-fido2 1.x (as well as 0.9).
