### ISSUE TITLE
Feature: more detailed output for `ykman fido credentials list`

### ISSUE THREAD

**Issue by VannTen** [Yubico/yubikey-manager#512]
Using ykman version 4.0.8, I get the following output:

```console
$ ykman fido credentials list
Enter your PIN: 
ssh:all 0000000000000000000000000000000000000000000000000000000000000000 openssh
```

Would it be possible to either get a header line precising what those field are,
or modify the `--help` to specify it here ?

Related issue: #444

**Comment by dainnilsson** [comment]
ykman 5 is now released, which adds headers, as well as a `--csv` option to output complete credential data in csv format.
