### ISSUE TITLE
silently fails for openpgp set-touch commands

### ISSUE THREAD

**Issue by strcrzy** [Yubico/yubikey-manager#517]
- YubiKey Manager (ykman) version: 4.0.9
- How was it installed?: pip
- Operating system and version: MacOS 12.5
- YubiKey model and version: YubiKey 5C Nano (5.2.7)
- Bug description summary: `ykman openpgp set-touch aut on` and friends appear to work, but then don't

Steps to reproduce
1. run `ykman openpgp set-touch aut on`
2. see warning: 
```
WARNING: The use of this command is deprecated and will be removed!
Replace with: ykman openpgp keys set-touch aut on
```
3. see prompt for admin PIN:
```
Enter Admin PIN:
Set touch policy of authentication key to on? [y/N]: y
```
Expected result
---

touch protection for authentication is enabled
OR
command returns a definitive error

Actual results and logs
---

no errors, and touch protection for authentication is not toggled on (same for the other touch protection modes)

Other info
---
I understand that the command I was using is deprecated, but many guides like [this one](https://zach.codes/ultimate-yubikey-setup-guide/#setting-up-your-yubikey), [this one with 8.3k stars](https://github.com/drduh/YubiKey-Guide), and even the official [Yubico guide](https://docs.yubico.com/software/yubikey/tools/ykman/OpenPGP_Commands.html#examples) still reference the old command. Silent failure can confuse users, especially since the warning only indicates that the previous command was deprecated and would be removed, not that it would appear to succeed but not. The new command is effective, but this deprecation situation is not.

**Comment by strcrzy** [comment]
Just tried this on a different batch of Yubikeys -- the following Yubikey does not enable touch protection using the new `openpgp keys set-touch` command, but does enable it using the old `openpgp set-touch` one.

YubiKey 5C Nano (5.4.3) [FIDO+CCID] Serial: 17697617

**Comment by dainnilsson** [comment]
I have tried to reproduce this on a 5.4.3 version YubiKey, but I am not able to.

The deprecated commands should just be redirecting to the new ones, the actual functionality should be exactly the same. If this works on some of your YubiKeys, but not this one in particular, then I suspect it isn't a problem with the command, but something else. What is the output of `ykman openpgp info` for the affected YubiKey?

**Comment by strcrzy** [comment]
```
+ ykman openpgp reset
+ sleep 1
+ ykman openpgp keys set-touch enc on -f -a 12345678
+ ykman openpgp keys set-touch aut on -f -a 12345678
+ ykman openpgp keys set-touch sig on -f -a 12345678
+ ykman openpgp info
OpenPGP version: 3.4
Application version: 5.2.7

PIN tries remaining: 3
Reset code tries remaining: 0
Admin PIN tries remaining: 3

Touch policies
Signature key           On
Encryption key          On
Authentication key      On
Attestation key         Off
```

**Comment by strcrzy** [comment]
(though the touch policies are on, i can sign commits, ssh into things, and decrypt with a PIN prompt but not a tap)
