### ISSUE TITLE
4.0.9: no signed release tarball 

### ISSUE THREAD

**Issue by mkszuba** [Yubico/yubikey-manager#518]
Hello,

As of a few minutes ago there is still no official, signed release tarball of yubikey-manager-4.0.9 on https://developers.yubico.com/yubikey-manager/Releases/ - in spite of this version having been published over 2 months ago and being listed on https://developers.yubico.com/yubikey-manager/Release_Notes.html . I recall that it took some time for signed 4.0.8 tarballs to be published as well but I do not think it took _that_ long.

Having previously (Issue #217) been pointed to Yubico Web pages as the official source of yubikey-manager releases we (i.e. yubikey-manager maintainers in Gentoo Linux) would very much avoid the use of GitHub tarballs - but ended up significantly delaying the roll-out of 4.0.9 for our users as a result. Therefore, could you either let us know when to expect the official release tarball or clarify if it is now okay to use GitHub ones? Thanks in advance!

**Comment by dainnilsson** [comment]
Apologies for this, this has been an oversight. The release should be available from developers.yubico.com shortly!

The files on the Github release page can also be used as an official source as an alternative to the ones on developers.yubico.com. To clarify, the uploaded files on https://github.com/Yubico/yubikey-manager/releases/tag/4.0.9 should match those on developers.yubico.com The ones labeled "Source code" (zip and tar.gz) are the auto-generated files referred to in #217 which should not be used.

**Comment by dainnilsson** [comment]
The release is now available from developer.yubico.com in addition to via Github, closing this issue.
