### ISSUE TITLE
`ykman list` doesn't return yubikey information when pcscd is malfunctioning

### ISSUE THREAD

**Issue by gbdlin** [Yubico/yubikey-manager#520]
- YubiKey Manager (ykman) version: 4.0.9
- How was it installed?: pip, also confirmed with other installation methods
- Operating system and version: Linux Ubuntu 22.04
- YubiKey model and version: YubiKey 5C Nano (5.2.7)
- Bug description summary: `ykman list` doesn't return yubikey information, despite information being available in `ykman info`

Steps to reproduce
---

1. break your `pcscd` service somehow, so it lists devices, but can't connect to them
2. run `ykman list`
3. Observe the result

Expected result
---

`ykman` shouldn't rely only on smartcard protocol and despite `pcscd` malfunctioning, it should still give results

Actual results and logs
---

Only `YubiKey [OTP+FIDO+CCID] <access denied>` are listed

Other info
---

Problem relies in `ykman.device.list_all_devices` function. This function is marking yubikey PIDs as handled even if it failed to retrieve the information using the first protocol tried (and it's always the smart card protocol). It should add PIDs to `handled_pids` only when it actually retrieved the information, so fetching info can be retried using other protocols.

**Comment by dainnilsson** [comment]
The code in question has been changed quite substantially for the upcoming version. Can you try out the `next` branch and see if you still find potential improvements in the behavior?

**Comment by dainnilsson** [comment]
Closing this as the new code is released as part of ykman 5. Please open a new issue if you believe there are still improvements to be made.
