### ISSUE TITLE
After upgrade to 5.0.0 Yubikey-Authenticator 5.1.0 no longer working

### ISSUE THREAD

**Issue by gbcox** [Yubico/yubikey-manager#523]
- YubiKey Manager (ykman) version: 5.0.0
- How was it installed?: rpm
- Operating system and version: Fedora 37
- YubiKey model and version: yubikey 5 nano
- Bug description summary:
Upgraded on F37 to ykman 5.0.0... which seems to be working fine so far with my nano, but now yubikey-authenticator isn't reading the key.

**Comment by dainnilsson** [comment]
Yubico Authenticator should be bundling its own version of ykman, not using a system installation of it. I take it the Fedora package is different? We don't really intend to make Yubico Authenticator 5 compatible with ykman 5, as our efforts are on getting Yubico Authenticator 6 done.

**Comment by gbcox** [comment]
Bundling is against packaging guidelines.  No problem, I will cancel the
upgrade and resubmit when you are able to release the Authenticator
upgrade.

**Comment by dainnilsson** [comment]
Alright, I will leave this issue open until we ship the new app, as a reminder to ping you about it! Should be out before the end of the year.

**Comment by gbcox** [comment]
Thanks!  Much appreciated!

**Comment by amake** [comment]
FYI this affects MacPorts as well

**Comment by molecular** [comment]
Oh that's tremendous, so I can access my sites again before the end of the year ;-)))

Seriously, my yubikey oath just broke on archlinux update. See https://bugs.archlinux.org/task/76325

What's the interim solution? Downgrade ykman to 4???

**Comment by dainnilsson** [comment]
This is a problem with the Arch Linux package, which is not maintained or supported by Yubico. Until they resolve the issue I suggest you use the AppImage provided at https://developers.yubico.com/yubioath-desktop/Releases/. Downgrading to ykman 4 would also be a viable option.

All packages of Yubico Authenticator provided by Yubico have a compatible version of ykman included, and our recommendation is for third party packages to do the same. If this is against packaging guidelines they should at least be limiting dependencies within compatible versions according to [Semantic Versioning](https://semver.org/).

**Comment by molecular** [comment]
Thanks @dainnilsson, yes you're right. It's arch problem. I downgraded ykman to 4 and that works.

**Comment by dainnilsson** [comment]
No worries, your frustration is understandable! Glad you were able to downgrade without issue. We'll make sure to call this our more explicitly in both projects README's to hopefully avoid the same thing happening again in the future when ykman 6 is released.

**Comment by Foxboron** [comment]
Is the dependency in [yubioath-desktop](https://github.com/Yubico/yubioath-desktop) even correct? Currently it pins to one `yubikey-manager` minor release and this isn't kept in-sync with the upstream releases. Should this be relaxed?

https://github.com/Yubico/yubioath-desktop/blob/main/requirements.txt#L1

Not that this is well tested (nor correct), but it seems like this patch restores some functionality to the desktop app with the 5.x iteration of `yubikey-manager`: https://paste.xinu.at/M2dOf5QaB3442UMLfOp/

**Comment by dainnilsson** [comment]
Since the packages Yubico maintains bundle its dependencies we use exact pinned versions, which are the ones you'll see in the requirements.txt, it's pointing to the latest version at the time of release, typically. However, the projects follow semver, so it should be perfectly safe to depend on anything >= the pinned version, but < the next major version.

**Comment by dainnilsson** [comment]
[Yubico Authenticator 6.0.0](https://github.com/Yubico/yubioath-flutter/releases/tag/6.0.0) (note the repository name change!) is now released, supporting (and requiring) ykman 5.0.0.
