### ISSUE TITLE
Allow removing PIN from FIDO2 (WebAuthn)

### ISSUE THREAD

**Issue by deni** [Yubico/yubikey-manager#539]
- YubiKey Manager (ykman) version: 5.0.1
- How was it installed?: Homebrew
- Operating system and version: macOS 12.4 (Monterey)
- YubiKey model and version: Security Key C NFC FW v. 5.4.3
- Bug description summary:

Steps to reproduce
---

```
ykman fido access change-pin --pin 1234 --new-pin ""
```

Expected result
---

PIN code being removed from the applet.

Actual results and logs
---

The following prompt appeared, and did not accept an empty input:

```
Enter your new PIN: 
```

**Comment by emlun** [comment]
Sorry, even if we wanted to do this, this is not possible in the CTAP2 protocol. Once you've set a PIN, the only way to remove it is to completely factory-reset the authenticator.
