### ISSUE TITLE
No serial number shown in GUI version 1.2.5 on windows 10 x64 | Yubikey 5 NFC

### ISSUE THREAD

**Issue by nemuimaru** [Yubico/yubikey-manager#557]
- YubiKey Manager (ykman) version: 1.2.5. GUI
- How was it installed?: downloaded from the official website
- Operating system and version: Win10 Pro 22H2 19045.2788
- YubiKey model and version: 5 NFC Firmware 5.4.3
- Bug description summary: No serial number showing, no option to configure OTP

Steps to reproduce
---
Install manager after downloading x64 version from this website https://www.yubico.com/support/download/yubikey-manager/. Run as admin, plug in Yubikey

Expected result
---
Show Serial number and let me configure an OTP

Actual results and logs
---

Not showing serial number, not able to configure OTP

Other info
---
![yubikey](https://github.com/Yubico/yubikey-manager/assets/129535850/c3478341-1e34-48c3-bce3-bfd9ea36345d)

[Screenshot](https://imgur.com/a/Qj7pt9X) or see above

The personalization tool doesn't even recognize the key itself telling me "No Yubikey inserted" in the top right area.

Most recent GUI versions, both run as admin, my logged in user account also is admin, key verified [here](https://www.yubico.com/genuine/) .Also did the basics like reboot/try different usb port/try with and without a hub/restart the programs/etc, not run as admin

**Comment by nemuimaru** [comment]
Closed, vendor provided a security key instead of the Yubikey they should give me.
---

**Comment by influential-eliot** [comment]
I might have this issue, too.

I bought directly from YubiCo on Amazon UK, and I literally can't do anything with this redundant piece of silicon. :-(

**Comment by nemuimaru** [comment]
> I bought directly from YubiCo on Amazon UK, and I literally can't do anything with this redundant piece of silicon. :-(

Same. Not UK but Germany but also from the official YubiCo store on Amazon. I send it back and got a replacement shipped from Italy (weird) which again, was the security key. As I don't wanna pay 55€ for a security I send it back again and ordered an 5 NFC from a different website. 
I figure the problem could be the labeling. The Security Key is in a Security Key Blister, but the sticker on the back of the blister, which also has the product number/barcode/product ID states "YubiKey 5 NFC". So they probably just mislabeled the product.  Maybe you got better luck with the route I went and check out https://www.yubico.com/support/resellers/ to find a certified online or offlineshop that sells these. Fingers crossed!:D

**Comment by fdennis** [comment]
I'm sorry to hear that you received the wrong items. I hope Amazon can rectify the situation.
