### ISSUE TITLE
ykman has a check which prevents use of python >= 23.4 - F40 will use 24.2

### ISSUE THREAD

**Issue by gbcox** [Yubico/yubikey-manager#570]
- YubiKey Manager (ykman) version: 5.2.0
- How was it installed?: Fedora rpm
- Operating system and version: Fedora 40 (currently rawhide) - Scheduled production date approx. May, 2024
- YubiKey model and version: N/A
- Bug description summary:
Installation message:

can't install python3-yubikey-manager:
  - nothing provides (python3.12dist(keyring) < 24~~ with python3.12dist(keyring) >= 23.4) needed by python3-yubikey-manager-5.2.0-1.20230821gitd1bf843.fc40.noarch
 
FYI... F40 will be using :
[python-keyring-24.2.0-1.fc40](https://koji.fedoraproject.org/koji/buildinfo?buildID=2284107)
So python level check needs to be adjusted prior to May, 2024.
You probably are already aware, but thought I'd create a bug report, just in case.
Thanks much!

**Comment by musicinmybrain** [comment]
This seems to be fixed in https://github.com/Yubico/yubikey-manager/commit/a956fadbf3050208ca8bef7d36826dc418ef0180.

**Comment by gbcox** [comment]
@dainnilsson Can you please comment as to whether [a956fad](https://github.com/Yubico/yubikey-manager/commit/a956fadbf3050208ca8bef7d36826dc418ef0180) can be applied in isolation.  I'd hate to push it only to find out it caused unintended consequences.  Thanks!

**Comment by dainnilsson** [comment]
As in applying only that commit onto the latest release? I believe that should work, yes. If there isn't a big rush for it you may want to wait for the next release which will include the commit which will likely be in 1-2 weeks.

**Comment by gbcox** [comment]
@dainnilsson I noticed that for the keyring you specify ^24.  So, if I'm interpreting this correctly you're saying that version 23.+ is no longer compatible and version 24 is required?  Thanks!

**Comment by dainnilsson** [comment]
Well, it should still be fully compatible and maybe a less strict bump to include both major versions would be more appropriate. There were no changes to our code base required to support the new version, but we will stop testing with 23.x so it's possible that over time we will drop compatibility. Would continuing to have "official" support for 23.x be helpful then in this case, to better support more Fedora versions?

**Comment by gbcox** [comment]
@dainnilsson If both versions are still fully compatible it would definitely be helpful to have both versions allowed.

**Comment by gbcox** [comment]
@dainnilsson Great.  Thank you very much!

**Comment by dainnilsson** [comment]
5.2.1 is now released with this.
