### ISSUE TITLE
Static password does not input properly for BIOS/SystemPartition prompts

### ISSUE THREAD

**Issue by SolomonHD** [Yubico/yubikey-manager#571]
- YubiKey Manager (ykman) version: 5.2.0
- How was it installed?: Windows installer
- Operating system and version: Win 11
- YubiKey model and version: 5 NFC/USB A
- Bug description summary:
- Static password failing to unlock Veracrypt encrypted system partition. This necessitates a password right at boot up after bios. The static password will not type correctly I've tried with the "enter" and "no enter" settings neither worked.
- The only other time I've seen this is with KeePassAndroid and Inputstick, with that setup I usually had to select a "slow type" option for it to work.  

Steps to reproduce
---
Veracrypt system partition, requiring password to unlock on boot up
Set yubikey to static password, with "no enter"
Attempt to unlock system partition with Yubikey

Expected result
---
System unlocks

Actual results and logs
---

System says password is incorrect

Other info
---

I suggest adding a slow type option

**Comment by dainnilsson** [comment]
You can use the `ykman otp settings --pacing [0|20|40|60]` command to change the rate at which characters are output.

**Comment by SolomonHD** [comment]
Thank you that worked perfectly!
