### ISSUE TITLE
Works on Raspberry Pi 4B but doesn't on Raspberry Pi Zero (latest buster version for both)

### ISSUE THREAD

**Issue by mrbpp** [Yubico/yubikey-manager#578]
- YubiKey Manager (ykman) version: yubikey-manager/now 2.1.0+debi0u1 all [installed. local]
- How was it installed?: sudo dpkg -i yubikey-manager*.deb
- Operating system and version:  Debian/2021-05-07-raspios-buster-armhf
- YubiKey model and version: Standart Yubikey 5 NFC
- Bug description summary: ykman command not working

Steps to reproduce
---

First check on my Raspberry Pi 4b 8gb latest buster version the same as the version on the Raspberry Pi Zero for the package that I need:

~$ sudo apt list scdaemon yubikey-manager libpam-yubico libpam-u2f libu2f-udev

Then download them:

~$ sudo apt-get download scdaemon yubikey-manager libpam-yubico libpam-u2f libu2f-udev

Then move them on brand new USB drive.

~$ mv scdaemon*.dpkg yubikey-manager*.dpkg libpam-yubico*.dpkg  libpam-u2f*.dpkg  libu2f-udev*.dpkg  /media/pi/<usb-long-name>

Move to my Raspberry Pi Zero and install the packages:

~$ sudo dpkg -i yubikey-manager*.deb
~$ sudo dpkg -i libpam-yubico*.deb
~$ sudo dpkg -i libpam-u2f*.deb
~$ sudo dpkg -i libu2f-udev*.deb

Expected result
---

~$ ykman - To work properly without errors. I want to change Yubikey PIN and Admin PIN on my air-gapped device (Raspberry PI Zero Buster)

Actual results and logs
---

Errors in /usr/lib/python3 

In the end error: The 'yubikey-manager==2.1.0' distribution was not found and is required by the application

Other info
---

What I am thinking of doing but I still haven't done, because I am afraid that I'll mess something up:

Im not sure but i thing I need to install yubikey-manager first on my Raspberry Pi 4B with:

~$ sudo apt install yubikey-manager

Then i need to go to /var/cache/apt/archives/ and to copy files yubikey new .deb files with the packages that I first was downloaded and to move them to the USB drive. 

On Raspberry Pi Zero:
----

Copy the contents of the USB’s deb directory to any new directory of your choice.

In the terminal, navigate to that directory and type sudo dpkg -i *.deb to install the dependencies.

Install other packages and delete the directory with the *.deb files.

**Comment by dainnilsson** [comment]
ykman 2.1.0 is extremely old. Please try installing 5.2.1 which is the latest version. You can find installation instructions (including required dependencies) in the README file.

**Comment by mrbpp** [comment]
Ok, I will try with the new version of ykman.

Thanks 😊
