### ISSUE TITLE
Issue with registering a new yubikey

### ISSUE THREAD

**Issue by Boris-Droz** [Yubico/yubikey-manager#582]
- YubiKey Manager (ykman) version: I have a Security key NFC by Yubico 
- How was it installed?: no installation it's plug on usb
- Operating system and version: window11, Firefox 115.5.0esr 
- YubiKey model and version: Security Key NFC by Yubico I have a SKU number if it help 5060408465295
- Bug description summary:
I have issue with registering a new yubikey. I change recently of computer and the key was not responding so. I delet it and tried to re installed with the new computer. The old computer was in window 10.

Steps to reproduce
---
- From my account security setting I clic on "Register a new security key"
- I write a new name clic add
- A window opened I choose key
- When I have to clic on my yubikey (the key button is green so definitively the key is recognized)
- When I have a next window with "continue setup" that stay forever
- It look that the key or the computer did not get anything from github.
- I use the same key for my university network, dropbox, google.. no issue with all.
- Not sure what to do next?

**Comment by dainnilsson** [comment]
This issue does not seem to have anything to do with the YubiKey Manager command line application. I suggest you open a  ticket with Yubico Support instead,
