### ISSUE TITLE
Device Not Detected on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by tornupnegatives** [Yubico/yubikey-manager#597]
- YubiKey Manager (ykman) version: 4.0.7
- How was it installed?: "jammy" repo
- Operating system and version: Ubuntu 22.04.1 (6.5.0-21-generic)
- YubiKey model and version: YubiKey 5C NFC (Firmware 5.4.3)
- Bug description summary: When I plug my YubiKey 5C NFC into my computer, the LED flashes rapidly and then stops. However, the system does not detect it. It does not appear listed with `lsusb`, and the YubiKey Manager does not detect it.

Steps to reproduce
---

1. Install YubiKey Manager from Ubuntu repos
`sudo apt install libpam-yubico pcscd libccid libu2f-udev yubikey-manager`
2. List devices:
`ykman list`

Expected result
---

I expect to see a device listed!

Actual results and logs
---

Nothing :(

**Comment by dainnilsson** [comment]
I would recommend you instead install the package through `pip` so that you can get a more recent one. The current release as of writing is 5.3.0. Instructions for this are in the README. If you update ykman to the latest version and still have this issue, please let me know and we will continue from there.

Unfortunately we can't really support you if you wish to continue using the older version, but if you want to troubleshoot the issue yourself, a good starting point would be to run `ykman --diagnose` while the YubiKey is connected, and inspecting the output for any errors.

**Comment by tornupnegatives** [comment]
@dainnilsson Okay, I have installed the latest version of `ykman`

```shell
$ sudo apt install python3-pip python3-venv
$ python3 -m venv ~/.local/venv

$ sudo apt install pcscd swig libpcsclite-dev
$ source ~/.local/venv/bin/activate

$ pip3 install yubikey-manager
$ ~/.local/venv/bin/ykman --diagnose
```

```
ykman:            5.3.0
Python:           3.11.6 (main, Oct  8 2023, 05:06:43) [GCC 13.2.0]
Platform:         linux
Arch:             x86_64
System date:      2024-03-24
Running as admin: False
Detected PC/SC readers:

Detected YubiKeys over PC/SC:

Detected YubiKeys over HID OTP:

Detected YubiKeys over HID FIDO:

End of diagnostics
```

As before, the YubiKey 5C NFC flashes rapidly for a few moments when I plug it in, but it does not register in the system...

**Comment by dainnilsson** [comment]
That's very strange, it really seems to not be detected *at all*. Does it make any difference if you run the command with `sudo`?

**Comment by tornupnegatives** [comment]
Running with `sudo` does not make a difference. The key _does_ appear and function normally on my MacBook Pro (2019)

**Comment by dainnilsson** [comment]
Since the key works on another computer I think we can rule out it being defective, and since even `lsusb` doesn't see the key, we can also rule out yubikey-manager itself. It would seem to me that this is some issue with the host. Do other USB devices function properly with that same USB port?

**Comment by tornupnegatives** [comment]
Now, that's where I'm stumped. My first suspicion after trying all the software fixes was that my USB port was somehow faulty. However, every other device I've plugged into it works just fine! Do you by chance know if the YubiKey has very specific voltage or current requirements?

**Comment by dainnilsson** [comment]
Nothing out of the ordinary as far as I know.

One thought that struck me: Are you running any virtualization software that supports USB redirection? Could it be possible that the YubiKey is being redirected somewhere else?

**Comment by tornupnegatives** [comment]
I am not running any virtualization software, nor should anything be redirecting USB.

**Comment by tornupnegatives** [comment]
After working my way through the software, firmware, OS, etc. with no luck; I requested a replacement USB-C port from the manufacturer of my computer case. That did the trick!

**Comment by dainnilsson** [comment]
Very glad you got to the bottom of that, and thanks for sharing the update!
