### ISSUE TITLE
ykman crashes resetting openpgp after failed NFC key creation

### ISSUE THREAD

**Issue by nimbius** [Yubico/yubikey-manager#607]
- YubiKey Manager (ykman) version: 5.3.0
- How was it installed?: pacman
- Operating system and version: arch
- YubiKey model and version: neo 5.3.0
- Bug description summary:
ykman openpgp reset fails with python error after failed attempt to generate keys over NFC

Steps to reproduce
---
ykman openpgp reset

[Please explain what you did when the bug appeared, and if and how you have been
able to reproduce it.]

Expected result
---
reset openpgp app.
[What did you expect to happen when you did the above?]

Actual results and logs
---
WARNING! This will delete all stored OpenPGP keys and data and restore factory settings. Proceed? [y/N]: y
Resetting OpenPGP data, don't remove the YubiKey...
ERROR: An unexpected error has occurredTraceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ykman/_cli/__main__.py", line 421, in main
    cli(obj={})
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ykman/_cli/openpgp.py", line 115, in reset
    ctx.obj["session"].reset()
    ~~~~~~~^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ykman/_cli/util.py", line 197, in __getitem__
    self.resolve()
  File "/usr/lib/python3.11/site-packages/ykman/_cli/util.py", line 194, in resolve
    self._objects[k] = f()
                       ^^^
  File "/usr/lib/python3.11/site-packages/ykman/_cli/util.py", line 218, in <lambda>
    click.get_current_context().obj.add_resolver(str(f), lambda: f(*args, **kwargs))
                                                                 ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ykman/_cli/openpgp.py", line 84, in openpgp
    ctx.obj["session"] = OpenPgpSession(conn)
                         ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yubikit/openpgp.py", line 1005, in __init__
    self._version = self._read_version()
                    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yubikit/openpgp.py", line 1018, in _read_version
    bcd = self.protocol.send_apdu(0, INS.GET_VERSION, 0, 0)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yubikit/core/smartcard.py", line 229, in send_apdu
    raise ApduError(response, sw)
yubikit.core.smartcard.ApduError: APDU error: SW=0x6985

[What actually happened?]
it looks like we can brick the OpenPGP app over NFC?  maybe a nice little Denial of Service?

Other info
---
this error started happening after a botched attempt to generate keys on the neo over NFC.  gpg shows card status is in PIV.  any attempt to change the status results in the same error.

[Anything else you would like to add?]

ugh. not sure how much i really even care about this.  the neo 5.3.0 has a pretty nasty pin-bypass vulnerability and it looks like the suits quit shipping replacement hardware five years ago :\  

is recovery from APDU error: SW=0x6985 possible at all?

**Comment by nimbius** [comment]
ykman openpgp reset
WARNING! This will delete all stored OpenPGP keys and data and restore factory settings. Proceed? [y/N]: y
Resetting OpenPGP data, don't remove the YubiKey...
ERROR: Failed to connect to YubiKey.

sadly looks like no.  i guess this little neo was a good key for 12 years.

ykman info
Device type: YubiKey NEO
Serial number: 4558393
Firmware version: 3.4.9
Enabled USB interfaces: OTP, FIDO, CCID
NFC transport is enabled.

Applications    USB             NFC
Yubico OTP      Enabled         Enabled
FIDO U2F        Enabled         Enabled
FIDO2           Not available   Not available
OATH            Enabled         Enabled
PIV             Enabled         Enabled
OpenPGP         Enabled         Enabled
YubiHSM Auth    Not available   Not available

**Comment by dainnilsson** [comment]
Did you follow the steps in the link under the heading **Option 2 - Manual Reset Using GPG**? Using `gpg-connect-agent` to perform the reset may work better if the applet is in a broken state.

**Comment by nimbius** [comment]
gpg --card-status
gpg: selecting card failed: No such device
gpg: OpenPGP card not available: No such device

**Comment by dainnilsson** [comment]
Closing this issue as I don't think there's anything more we can do in this repo.
