### ISSUE TITLE
[question] How to validate the downloaded software authenticity?

### ISSUE THREAD

**Issue by epoberezkin** [Yubico/yubikey-manager#609]
E.g., by validating downloaded software hash and/or signature.

**Comment by emlun** [comment]
Hi! Signatures are included in the [release channels listed in the README](https://github.com/Yubico/yubikey-manager?tab=readme-ov-file#pre-built-packages) and at [developers.yubico.com](https://developers.yubico.com/yubikey-manager/Releases/). Release signing keys are also [listed on developers.yubico.com](https://developers.yubico.com/Software_Projects/Software_Signing.html).

**Comment by epoberezkin** [comment]
Thank you, to be more precise, I was looking to validate signature for appimage that is available via the website, and it's not available in the release page.

**Comment by emlun** [comment]
In that case I assume you mean the [YubiKey Manager GUI](https://github.com/Yubico/yubikey-manager-qt), not the CLI (which is what's hosted in this repository). Those releases and their signatures are listed [here](https://developers.yubico.com/yubikey-manager-qt/Releases/). However, for most use cases I would recommend using [Yubico Authenticator](https://developers.yubico.com/yubioath-flutter/) instead, which now has almost all the capabilities of the YubiKey Manager GUI.

**Comment by epoberezkin** [comment]
thank you!
