### ISSUE TITLE
Allow running against keyring-25

### ISSUE THREAD

**Issue by mkszuba** [Yubico/yubikey-manager#612]
- YubiKey Manager (ykman) version: 5.4.0
- How was it installed?: with pip in a venv
- Operating system and version: Gentoo Linux, up-to-date rolling release
- YubiKey model and version: YubiKey 5 NFC (5.4.3)
- Bug description summary:

At the moment, _i.e._ up to and including the current state of the main Git branch, yubikey-manager depends on keyring < 25. However, running the 5.4.0 test suite - including integration tests against a dedicated YK5 - produces no errors against keyring-25.1.0 (_i.e._ the latest version currently available from PyPI), and I have yet to observe any run-time errors of this configuration. I would therefore like to suggest removing this version cap.

Steps to reproduce
---

* Download yubikey-manager sources
* Edit pyproject.toml so that it no longer requires using an older version of keyring
* Install yubikey-manager using the modified source tree
* Run the test suite

Expected result
---

yubikey-manager pulls keyring-25, installs fine, passes all tests and produces no run-time errors during normal use.

Actual results and logs
---

yubikey-manager pulls keyring-24.3.1.

Other info
---

The aforementioned testing has been conducted against a py3.11 venv configured _not_ to use system site-packages.

**Comment by dainnilsson** [comment]
This is resolved in the latest version (5.5.0).
