### ISSUE TITLE
[Ubuntu/Debian] Yubico's PPA (Personal Package Archive) Causes Weak Algorithm (rsa1024) Warning on Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by m33x** [Yubico/yubikey-manager#613]
- YubiKey Manager (ykman) version: 5.4.0
- How was it installed?: Yubico's PPA
- Operating system and version: Ubuntu 24.04 (Noble Numbat)
- YubiKey model and version: Irrelevant
- Bug description summary: The PPA signature key is based on a weak and deprecated algorithm (RSA 1024 bits), which causes a warning message in Ubuntu 24.04.

Steps to reproduce
---

1) Visit https://www.yubico.com/support/download/yubikey-manager/ click on "Linux – Ubuntu Download"
2) Follow the tutorial and try to add Yubico's PPA
3) Run `sudo apt-get update`

Expected result
---
No error message appears.

Actual results and logs
---
The following error message appears:

`W: https://ppa.launchpadcontent.net/yubico/stable/ubuntu/dists/noble/InRelease: Signature by key 3653E21064B19D134466702E43D5C49532CBA1A9 uses weak algorithm (rsa1024)`

Other info
---

Please update your repository key to something stornger than RSA 1024bit.

![Terminal - maxi@box: ~_001](https://github.com/Yubico/yubikey-manager/assets/883685/b00244e5-435a-4522-a24e-bd337b0daba9)

**Comment by dainnilsson** [comment]
This is an issue with Launchpad, unfortunately there is nothing we can do other than wait for them to complete the work. Please see https://answers.launchpad.net/launchpad/+question/809194

**Comment by m33x** [comment]
@dainnilsson It looks like there is finally some progress on this issue. Can you please have a second look?

**Comment by dainnilsson** [comment]
Thanks!

Based on the latest comment in that thread:
```All the affected Launchpad PPAs have been signed with a more secure key and Launchpad now serve that key. So for fixing this issue for PPAs already added to a system, just remove and re-add them.```

I read this as each user will have to remove and re-add the PPA manually to get rid of the warning, so nothing really for us to do?

**Comment by m33x** [comment]
Can confirm. Workaround fixed the issue for me. This can be closed.

$ `sudo apt update`
```
...
Fetched 19.7 MB in 5s (3,979 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
64 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: https://ppa.launchpadcontent.net/yubico/stable/ubuntu/dists/noble/InRelease: Signature by key 3653E21064B19D134466702E43D5C49532CBA1A9 uses weak algorithm (rsa1024)
```


$ `sudo add-apt-repository --remove ppa:yubico/stable`
```
Repository: 'Types: deb
URIs: https://ppa.launchpadcontent.net/yubico/stable/ubuntu/
Suites: noble
Components: main
'
Description:
PPA for stable Yubico software.
More info: https://launchpad.net/~yubico/+archive/ubuntu/stable
Removing repository.
Press [ENTER] to continue or Ctrl-c to cancel.
Removing entry from /etc/apt/sources.list.d/yubico-ubuntu-stable-noble.sources
```

$ `sudo add-apt-repository ppa:yubico/stable`
```
Repository: 'Types: deb
URIs: https://ppa.launchpadcontent.net/yubico/stable/ubuntu/
Suites: noble
Components: main
'
Description:
PPA for stable Yubico software.
More info: https://launchpad.net/~yubico/+archive/ubuntu/stable
Adding repository.
...
Fetched 22.1 kB in 2s (12.9 kB/s)          
Reading package lists... Done
```

**Comment by gene1wood** [comment]
I had luck replacing the signing key's public key on my local machine with the current key located at https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3f80cba8e2cb976c9448bed839a069dd66c3c7f1

In my case this was located at `/etc/apt/keyrings/yubico.asc` because my `/etc/apt/sources.list.d/yubico.list` contained

```
deb [signed-by=/etc/apt/keyrings/yubico.asc] http://ppa.launchpad.net/yubico/stable/ubuntu noble main
```
