### ISSUE TITLE
No package metadata was found for ykman : 5.5.1~ppa1~jammy1 apt install

### ISSUE THREAD

**Issue by jutomation** [Yubico/yubikey-manager#626]
**user@machine:$ apt-cache policy yubikey-manager**
    

> yubikey-manager:
>       Installed: 5.5.1~ppa1~jammy1
>       Candidate: 5.5.1~ppa1~jammy1
>       Version table:
>      *** 5.5.1~ppa1~jammy1 500
>             500 https://ppa.launchpadcontent.net/yubico/stable/ubuntu jammy/main amd64 Packages
>             100 /var/lib/dpkg/status
>          5.2.1-1 500
>             500 http://archive.ubuntu.com/ubuntu noble/universe amd64 Packages
>             500 http://archive.ubuntu.com/ubuntu noble/universe i386 Packages

**user@machine:$ lsb_release -rd**
>     No LSB modules are available.
>     Description:	Linux Mint 22
>     Release:	22

**Bug description summary:**

> user@machine:$ ykman
> Traceback (most recent call last):
>   File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 397, in from_name
>     return next(cls.discover(name=name))
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> StopIteration
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/bin/ykman", line 33, in <module>
>     sys.exit(load_entry_point('ykman==5.5.1', 'console_scripts', 'ykman')())
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/bin/ykman", line 22, in importlib_load_entry_point
>     for entry_point in distribution(dist_name).entry_points
>                        ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 862, in distribution
>     return Distribution.from_name(distribution_name)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 399, in from_name
>     raise PackageNotFoundError(name)
> importlib.metadata.PackageNotFoundError: No package metadata was found for ykman

Steps to reproduce
---

Scratch install of linux mint
```bash
sudo apt-add-repository ppa:yubico/stable
sudo apt update
sudo apt install yubikey-manager
```

Expected result
---

Ykman to display

**Comment by dainnilsson** [comment]
I'm unable to reproduce this using a stock Ubuntu 22.04 image. I see that Python 3.12 is part of the path in your stacktrace, which isn't normally available in Ubuntu 22.04. Are you manually installing a newer Python version, and if so, through which method?

**Comment by dainnilsson** [comment]
I did a little digging and I am able to reproduce the issue by forcing ykman to use Python 3.12, which can happen if you for example change the `/usr/bin/python3` binary on your system:
```
$ ls -lah /opt/venvs/yubikey-manager/bin/
total 52K
drwxr-xr-x 2 root root 4.0K Aug  5 12:53 .
drwxr-xr-x 5 root root 4.0K Aug  5 12:41 ..
-rw-r--r-- 1 root root 8.9K Jul  1 12:17 Activate.ps1
-rw-r--r-- 1 root root 2.0K Jul  1 12:17 activate
-rw-r--r-- 1 root root  941 Jul  1 12:17 activate.csh
-rw-r--r-- 1 root root 2.2K Jul  1 12:17 activate.fish
-rwxr-xr-x 1 root root  231 Jul  1 12:17 keyring
-rwxr-xr-x 1 root root  243 Jul  1 12:17 pip
-rwxr-xr-x 1 root root  243 Jul  1 12:17 pip3
-rwxr-xr-x 1 root root  243 Jul  1 12:17 pip3.10
lrwxrwxrwx 1 root root    7 Jul  1 12:17 python -> python3
lrwxrwxrwx 1 root root   16 Jul  1 12:17 python3 -> /usr/bin/python3
lrwxrwxrwx 1 root root    7 Jul  1 12:17 python3.10 -> python3
-rwxr-xr-x 1 root root  991 Aug  5 12:53 ykman
```

The PPA installation is tied to Python 3.10, so you will either have to manually adjust the symlink in /opt/venvs/yubikey-manager/bin/ to point to python3.10, or install yubikey-manager using a different method, such as `pip`.

**Comment by dainnilsson** [comment]
Ubuntu 24.04 (or derivatives) should use the correct PPA package, but your first post shows the package for `jammy` being installed rather than for `noble`. With a fresh Ubuntu 24.04 and the correct package installed the proper Python version will be used:
```
ls -lah /opt/venvs/yubikey-manager/bin/
total 52K
drwxr-xr-x 2 root root 4.0K Aug  5 14:56 .
drwxr-xr-x 5 root root 4.0K Aug  5 14:56 ..
-rw-r--r-- 1 root root 8.9K Jul  1 12:17 Activate.ps1
-rw-r--r-- 1 root root 2.2K Jul  1 12:17 activate
-rw-r--r-- 1 root root  942 Jul  1 12:17 activate.csh
-rw-r--r-- 1 root root 2.2K Jul  1 12:17 activate.fish
-rwxr-xr-x 1 root root  231 Jul  1 12:17 keyring
-rwxr-xr-x 1 root root  243 Jul  1 12:17 pip
-rwxr-xr-x 1 root root  243 Jul  1 12:17 pip3
-rwxr-xr-x 1 root root  243 Jul  1 12:17 pip3.12
lrwxrwxrwx 1 root root    7 Jul  1 12:17 python -> python3
lrwxrwxrwx 1 root root   16 Jul  1 12:17 python3 -> /usr/bin/python3
lrwxrwxrwx 1 root root    7 Jul  1 12:17 python3.12 -> python3
-rwxr-xr-x 1 root root  239 Jul  1 12:17 ykman
```
