### ISSUE TITLE
ykman failing with pyscard / smartcard 2.1.0

### ISSUE THREAD

**Issue by rhertzog** [Yubico/yubikey-manager#634]
- YubiKey Manager (ykman) version: 5.4.0
- How was it installed?: apt install yubikey-manager
- Operating system and version: Debian Unstable
- YubiKey model and version: YubiKey 5 NFC FIPS
- Bug description summary: ykman fails to connect to the yubikey

In Debian unstable, the pyscard / smartcard dependency got upgraded to version 2.1.0 (https://tracker.debian.org/pkg/pyscard) and it breaks ykman:

```
$ ykman info
WARNING: Failed opening device
ERROR: Failed to connect to YubiKey.
```

I verified that switching back to version 2.0.10 fixes the issue and I diagnosed this because in the debug output you can see this:

```
DEBUG 17:00:47.882 [ykman.device.add:165] Add device for <class 'yubikit.core.smartcard.SmartCardConnection'>: ScardYubiKeyDevice(pid=0404, fingerprint='Yubico YubiKey CCID 00 00')
WARNING 17:00:47.900 [ykman.device.add:179] Failed opening device
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ykman/device.py", line 171, in add
    with dev.open_connection(conn_type) as conn:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ykman/pcsc/__init__.py", line 88, in open_connection
    return self._open_smartcard_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ykman/pcsc/__init__.py", line 96, in _open_smartcard_connection
    return ScardSmartCardConnection(self.reader.createConnection())
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/smartcard/pcsc/PCSCReader.py", line 101, in createConnection
    return CardConnectionDecorator(PCSCCardConnection(self.name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Can't instantiate abstract class CardConnectionDecorator without an implementation for abstract methods 'doControl', 'doGetAttrib', 'doTransmit'
```

**Comment by dainnilsson** [comment]
Thanks for the report. It looks like this is an issue with pyscard 2.1.0, as far as I can tell we're not doing anything that shouldn't work. See https://github.com/LudovicRousseau/pyscard/issues/175

**Comment by Zaptyp** [comment]
Update pyscard to 2.1.1: https://github.com/LudovicRousseau/pyscard/releases/tag/2.1.1

**Comment by rhertzog** [comment]
Thank you for pointing out the issue on pyscard's side. I'm closing this issue since a fixed version is available.

**Comment by solomon-b** [comment]
I'm having what appears to be a similar issue with `ykman 5.5.1` and `psycog 2.0.9`, only `ykman info` works consistenly but `ykman oath` commands are failing:

```
➜ ykman info     
Device type: YubiKey 5C Nano
...

➜ ykman oath accounts code $OATH_ARN 
ERROR: Failed to connect to YubiKey.
```
