### ISSUE TITLE
YubiKey is not detected unless NFC reader is explicitly specified

### ISSUE THREAD

**Issue by Nhowka** [Yubico/yubikey-manager#646]
- YubiKey Manager (ykman) version: 5.5.1
- How was it installed?: pip install
- Operating system and version: Ubuntu 24.04.1 LTS
- YubiKey model and version: YubiKey 5C NFC (5.7.1)
- Bug description summary: YubiKey is not detected unless reader is specified

Steps to reproduce
---

YubiKey is not detected when running `ykman info` or `ykman --diagnose`, but is detected when I pass my reader name in the `--reader` option 

Expected result
---

Key should be detected regardless

Actual results and logs
---

```
nhowka@menho:~$ /home/nhowka/.local/bin/ykman info
ERROR: No YubiKey detected!
nhowka@menho:~$ /home/nhowka/.local/bin/ykman --diagnose
ykman:            5.5.1
Python:           3.12.3 (main, Nov  6 2024, 18:32:19) [GCC 13.2.0]
Platform:         linux
Arch:             x86_64
System date:      2024-12-20
Running as admin: False
Detected PC/SC readers:
  ACS ACR1552 1S CL Reader [ACR1552 1S CL Reader PICC] ( RR631-000815) 00 00: Success
  ACS ACR1552 1S CL Reader [ACR1552 1S CL Reader SAM] ( RR631-000815) 01 00:  <NoCardException>

Detected YubiKeys over PC/SC:

Detected YubiKeys over HID OTP:

Detected YubiKeys over HID FIDO:

End of diagnostics
nhowka@menho:~$ /home/nhowka/.local/bin/ykman -r "ACR1552 1S CL Reader PICC" info
Device type: YubiKey 5C NFC
Serial number: <removed>
Firmware version: 5.7.1
Form factor: Keychain (USB-C)
NFC transport is enabled

Applications	USB    	NFC    
Yubico OTP  	Enabled	Enabled
FIDO U2F    	Enabled	Enabled
FIDO2       	Enabled	Enabled
OATH        	Enabled	Enabled
PIV         	Enabled	Enabled
OpenPGP     	Enabled	Enabled
YubiHSM Auth	Enabled	Enabled
```

Other info
---

System is mostly clean, trying to configure the reader to use my passkeys. Reader is working fine on windows.

**Comment by dainnilsson** [comment]
Are you saying you can't connect to the YubiKey via USB? That only NFC works? I'm not sure I follow.

**Comment by dainnilsson** [comment]
The --reader flag is what tells ykman that it should use an NFC reader. If you don't supply the --reader flag, it will only use USB.

**Comment by Nhowka** [comment]
So I was understanding it wrong. How can I make my system then use the reader for authentication with passkeys? Yubico Authenticator is detecting the YubiKey when I select the reader.

**Comment by Nhowka** [comment]
I understand now that browser support is the main problem. Issue is somewhat solved by using https://github.com/BryanJacobs/fido2-hid-bridge
