### ISSUE TITLE
Allow Deleting/Listing Windows Hello credentials 

### ISSUE THREAD

**Issue by tprasadtp** [Yubico/yubikey-manager#67]
Under certain cases, it might be necessary to delete oath credentials for windows hello.
Currently there seems to be no way of deleting it other than resetting the entire applet.  (or using older version of Yubikey authenticator.) 
`ykman oath list` does not list stored credentials either.  At the lease user should be able to delete the set of credentials.

**Comment by dagheyman** [comment]
The Windows Hello app prefixes the credential with `_hidden` to be able to hide them in Yubico Authenticator. You can show these credentials in `ykman` using the `-H/--show-hidden` flag.

List credentials, including hidden:
`$ ykman oath list --show-hidden` 

Delete credentials:
`$ ykman oath list delete [QUERY]`
