### ISSUE TITLE
No handlers could be found for logger "ykman.driver_otp"

### ISSUE THREAD

**Issue by akerl** [Yubico/yubikey-manager#71]
It looks like there's a logging config step missing for:

```
❯ ykman -v
No handlers could be found for logger "ykman.driver_otp"
YubiKey Manager (ykman) version: 0.6.0
Libraries:
    libykpers not found!
    libu2f-host 1.1.4
    libusb 1.0.21

~
❯ ykman oath list
No handlers could be found for logger "ykman.driver_otp"
github
google
```

**Comment by dagheyman** [comment]
Thanks. There might be an issue here, but it also looks like you don't have the `libykpers` library installed. How did you install the tool?

**Comment by akerl** [comment]
I ran `pip install ykman`

It's correct that I don't have the ykpers library installed, but since I'm only using the OTP/OATH functionality, it didn't seem required / it didn't cause pip any concerns

**Comment by akerl** [comment]
Confirmed that adding libykpers makes handler error vanish. I suspect this means that the code path taken if that lib is missing skips some log initialization

**Comment by akerl** [comment]
Amusingly, on python3 this scenario (libykpers being absent) does print a traceback (my above logs are from python2):

```
❯ ykman oath list
libykpers not found
Traceback (most recent call last):
  File "/opt/brew/lib/python3.6/site-packages/yubikey_manager-0.6.1.dev0-py3.6.egg/ykman/driver_otp.py", line 57, in <module>
    ykpers = Ykpers('ykpers-1', '1')
  File "/opt/brew/lib/python3.6/site-packages/yubikey_manager-0.6.1.dev0-py3.6.egg/ykman/native/util.py", line 68, in __init__
    self._lib = use_library(libname, version, extra_paths)
  File "/opt/brew/lib/python3.6/site-packages/yubikey_manager-0.6.1.dev0-py3.6.egg/ykman/native/util.py", line 36, in use_library
    lib = load_library(libname, version, extra_paths)
  File "/opt/brew/lib/python3.6/site-packages/yubikey_manager-0.6.1.dev0-py3.6.egg/ykman/native/libloader.py", line 67, in load_library
    raise ImportError('%s not found.' % libname)
ImportError: ykpers-1 not found.
github
google
```

**Comment by akerl** [comment]
It looks like the issue is this line: https://github.com/Yubico/yubikey-manager/blob/master/ykman/driver_otp.py#L63

It happens during initial import of driver_otp.py, so if the ykpers setup fails, it tries to call logger.error before https://github.com/Yubico/yubikey-manager/blob/master/ykman/cli/__main__.py#L44 has run

**Comment by akerl** [comment]
Opened a PR that seems to fix this
