### ISSUE TITLE
yubikey-manager and yubikey-manager-qt packages not available via Ubuntu PPA for Trusty release

### ISSUE THREAD

**Issue by virento** [Yubico/yubikey-manager#74]
I'm running Ubuntu 14.04 Trusty on my desktops and have the Yubico stable PPA installed.  I've looked for the yubikey-manager and yubikey-manager-qt packages within the repo and cannot locate them (I can see all of the other packages just fine and verified their repo location via 'apt-cache policy <packagename>').  I checked out the ppa via the web @ launchpad.net and notice the build has failed for those two packages.

Any ideas that can help me resolve this issue?

**Comment by dagheyman** [comment]
Unfortunately we don't publish these packages for trusty, because of missing dependencies. See https://github.com/Yubico/yubioath-desktop/issues/181#issuecomment-329073086

**Comment by pdknsk** [comment]
It's not too difficult to build (non-distributable) packages on _Trusty_. The main obstacle is installing _Qt5_ from [qt.io](https://www.qt.io/). Other than that only minor modifications are necessary, such as replacing `subprocess.run`, which is not available in _Python 3.4_. I can write it up if people are interested.
