### ISSUE TITLE
`ykman piv generate-csr` seems to generate certificate signing requests with wrong signatures

### ISSUE THREAD

**Issue by davidepedranz** [Yubico/yubikey-manager#94]
I generated a key on my Yubikey using `ykman` as follows:
```bash
ykman piv generate-key 9a client.key
```

Then, I generated a certificate signing request in order to obtain a valid certificate from a CA:
```bash
ykman piv generate-csr 9a client.key client.csr -s "my-subject"
```

When I try to sign the certificate signing request, I obtain the following error from OpenSSL:
`Signature did not match the certificate request`

I use the following command for OpenSSL:
```bash
openssl x509 -req -days 365 -sha256 -in client.csr -CA ca.crt -CAkey ca.key -set_serial 1 -out client.crt
```

The tool `yubico-piv-tool` seems to work just fine:
```
yubico-piv-tool -a generate -s 9a -o client.key
yubico-piv-tool -a verify -a request -S "/CN=my-subject" -s 9a -o client.csr -i client.key
```
Now OpenSSL is able to correctly sign the certificate request.

**Comment by dagheyman** [comment]
Thanks for the report. There is a fix for this on master that will be included in the next release. See: https://github.com/Yubico/yubikey-manager/issues/55

**Comment by davidepedranz** [comment]
All right, thanks!
